### PR TITLE
[Feature:InstructorUI] Course material sorting

### LINKED ISSUE #4713: Manual sorting of course materials
Allow an instructor to assign a floating point number to each course material. The course materials will be sorted by these floating point numbers in ascending order. Ties are broken by alphabetical ascending order. Default to 99.0. This will appear in the upload and edit course materials modals (when edit is complete)

### PR DESCRIPTION
**Pull request by jportorreal00**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #4713 - Course materials are sorted alphabetically with smaller directories above another (file, folder, folder within a folder, etc).
image

### What is the new behavior?
Custom sorting available with floating point number (lower the number the higher up it is). Folders and files can be given a priority within their directory.
image

image

### Other information?
Tested by adding new files, folders within folders, and switching up the priorities.

### CODE REVIEW

**Comment by shailpatels** [comment]
@jportorreal00 

You're having a PHP static analysis issue around this section of code


```php

foreach ($files_to_modify as $file) {
            $file_path = $file['path'];
            $file_path_release_datetime = empty($release_time) ? $json[$file_path]['release_datetime'] : $release_time;
            $external_link = isset($json[$file_path]['external_link']) ? $json[$file_path]['external_link'] : false;

            $json[$file_path] =  ['release_datetime' => $release_time, 'sections' => $sections_exploded, 'hide_from_students' => $hide_from_students, 'external_link' => $external_link];
        }
        $json[$requested_path] =  ['release_datetime' => $file_path_release_datetime, 'sections' => $sections_exploded, 'hide_from_students' => $hide_from_students, 'sort_priority' => $sort_priority];
```

Its complaining that `file_path_release_datetime` may not be defined since its declared inside the for loop but used oustide (since its technically possible for the `for` loop to not execute. It looks like you're setting the value of `release_datetime` to whatever the last value is given to `file_path_release_datetime`, i.e the release datetime of the last file in the files to modify list.

Is this correct, should it always be the value for the last file? If so you can just initialize `file_path_release_datetime` to any value before the for loop like to `release_time` to `null`

**Comment by bmcutler** [comment]
Also...  can you add on-page documentation that larger numbers will be later in the sort?
Thanks!

**Comment by jportorreal00** [comment]
@bmcutler sounds good! I'll add a note under the input field

**Review by shailpatels — CHANGES_REQUESTED** [review]
Seems like floating point numbers do not work.
Had 2 files one as `20.2` and `20.1` and the file marked as 20.2 was above the other.

Nested folders may not store/display their ordering correctly
Here was my folder structure:
image


When I gave a nested file or folder a ranking it updated the ordering but when I clicked edit again the ranking I gave was blank:

image

Rest of the PR works well with integers and top level files. Existing course materials before this PR also work fine and can be updated with a ranking successfully

**Review by shailpatels — APPROVED** [review]
Changes look good and works as described, re-tested floating point numbers with files and folder and nested course materials

**Pull request merged**
