### PR TITLE
Added Unique Id's to primary buttons improving E2E testing. Referencing Issue #2660

### PR DESCRIPTION
**Pull request by duggalrd**
Many of the tests created for the discussion forum (and one in test_simple_grader) in E2E tests were using xpath selectors to find corresponding elements. As mentioned in Issue #2660, I added unique ID's to many of the buttons replacing xpath selectors with ID selectors, simplifying the E2E tests.

### CODE REVIEW

**Comment by MasterOdin** [comment]
Thanks for the PR. Would you be able to merge master in and then we can better (and more easily) review this?

**Comment by duggalrd** [comment]
Hey, sorry about that. I merged the master in: https://github.com/Submitty/Submitty/pull/3388

**Comment by MasterOdin** [comment]
Alright, so we can close this one and leave open your new PR to fix the #2660 issue?

**Comment by duggalrd** [comment]
Yes absolutely!

**Pull request closed without merging**
