### PR TITLE
[Testing:Developer] Parallelize integration test suite

### PR DESCRIPTION
**Pull request by wusatosi**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?

Currently the integration testing driver executes every test module sequentially, spending ~30mins on each run 

### What is the new behavior?
- [x] Integration testing

This pr implement parallel testing for integration testing, it is a apart of effort for #6390.
This reduces time for each execution down to ~15mins, a 2x speed up.
This patch enables integration test to be run parallelly on a test module level.
This patch has no impact on client code.

### Other information?

I've also cleaned up the script a bit as well, concurrency notes are put in for future maintainers where appropriate.

### CODE REVIEW

**Review by shailpatels — APPROVED** [review]
Ran updated tests locally and looking at the output of GitHub actions this PR makes good improvements to the integration test suite. It does knock off about 10+ minutes on the integration tests step on GH actions which is great.

I looked over the code and it looks readable clear to me but I'm not an expert in python multiprocessing code, @MasterOdin do you want to take a quick look?

**Comment by MasterOdin** [comment]
Looks like the test output is slightly borked:
```
--- BEGIN TEST MODULE TUTORIAL_12_SYSTEM_CALLS AT PROCESS 32404 ---
* Starting compilation...
* Starting prebuild for tutorial_12_system_calls... Done
* Finished compilation
* Starting testcase {modname}.{func.__name__}... PASSED
* Starting testcase {modname}.{func.__name__}... PASSED
* Starting testcase {modname}.{func.__name__}... PASSED
* Starting testcase {modname}.{func.__name__}... PASSED
* Starting testcase {modname}.{func.__name__}... PASSED
All testcases passed
--- END TEST MODULE TUTORIAL_12_SYSTEM_CALLS ---
```

**Comment by wusatosi** [comment]
> Looks like the test output is slightly borked:
> 
> ```
> --- BEGIN TEST MODULE TUTORIAL_12_SYSTEM_CALLS AT PROCESS 32404 ---
> * Starting compilation...
> * Starting prebuild for tutorial_12_system_calls... Done
> * Finished compilation
> * Starting testcase {modname}.{func.__name__}... PASSED
> * Starting testcase {modname}.{func.__name__}... PASSED
> * Starting testcase {modname}.{func.__name__}... PASSED
> * Starting testcase {modname}.{func.__name__}... PASSED
> * Starting testcase {modname}.{func.__name__}... PASSED
> All testcases passed
> --- END TEST MODULE TUTORIAL_12_SYSTEM_CALLS ---
> ```

Missed an f on the template string, its now fixed

**Comment by wusatosi** [comment]
> One gain for the integration test suite would be to move the compilation step of configure.out from a per-test instance to once per suite run. As part of the "prebuild" step, [build_main_configure.sh](https://github.com/Submitty/Submitty/blob/master/tests/integrationTests/build_main_configure.sh) is run where the compilation step of `configure.out` in it takes a number of seconds. This file is the same for all modules, and so could be safely hoisted to be compiled at the start of run.py to some temp location and then copied into place as needed for each test suite. This would save something like ~16s per module.

Speed up advise from matt (source: https://github.com/Submitty/Submitty/issues/6390#issuecomment-841946751)

**Comment by wusatosi** [comment]
I also want to have a look into utilizing CMake cache, I presume this can increase our test speed by a large margin as well, and could also be used in the main e2e pipeline.

**Comment by shailpatels** [comment]
> I also want to have a look into utilizing CMake cache, I presume this can increase our test speed by a large margin as well, and could also be used in the main e2e pipeline.

The CMake's cache is for storing environment variables, I'm not sure how this would speed of the tests? Unless you're thinking of something else

https://cmake.org/cmake/help/latest/variable/CACHE.html

**Comment by wusatosi** [comment]
> > I also want to have a look into utilizing CMake cache, I presume this can increase our test speed by a large margin as well, and could also be used in the main e2e pipeline.
> 
> The CMake cache is for storing environment variables, I'm not sure how this would speed of the tests? Unless you're thinking of something else
> 
> 

okay, I thought cmake have compilation cache built in, I am refering to compilation cache, something similar to this: https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/

**Comment by MasterOdin** [comment]
Two notes:
   
1. Please try and draw lines in what a PR does, keeping a PR focus as minimal as possible. This helps in two big ways: (1) makes it easier to review as the reviewer does not need to context switch (like right now I need to context switch between GH action and Python multiprocessing, very different things) and less code and (2) makes it easier to rollback code if somewhere where to break. For example, let's say the multiprocessing stuff broke something subtle and we revert it, we'd still want to keep the GH action changes and they're unrelated so could be kept.

1. > Speed up advise from matt (source: #6390 (comment))
   
   I don't see a change relating to this? I'd also like not to per the note above.

**Comment by wusatosi** [comment]
> Two notes:
> 
> 1. Please try and draw lines in what a PR does, keeping a PR focus as minimal as possible. This helps in two big ways: (1) makes it easier to review as the reviewer does not need to context switch (like right now I need to context switch between GH action and Python multiprocessing, very different things) and less code and (2) makes it easier to rollback code if somewhere where to break. For example, let's say the multiprocessing stuff broke something subtle and we revert it, we'd still want to keep the GH action changes and they're unrelated so could be kept.
> 2. > Speed up advise from matt (source: #6390 (comment))
>    
>    
>    I don't see a change relating to this? I'd also like not to per the note above.

Understood, I was making notes to myself as I clean up my work yesterday, and you are right.

**Comment by wusatosi** [comment]
CI Related code reverted.

**Comment by wusatosi** [comment]
This is reverted back to commit `Logging fix`, bda8be4.
CI-related code will be opened in another PR.
Ready for review

**Review by MasterOdin — APPROVED** [review]
Works as expected, can still one individual modules and testcases.

Something to consider (but not necessarily fix yet) is that in the move to multiprocessing, our test output is going to get "jumbled" up such that we may have multiple tested modules printing out at the same time. Perhaps better would be to mimic what other test suites do (e.g. jest) where it implements a TUI that lists out each module name if it passed or not, and then a little text to indicate that it's "running", and then once a given module finishes, it updates the line for that module. The modules may finish in any order, and once a module does finish, we output the error. Hopefully that makes sense, but that is very much a "wouldn't that be swell" kind of thing, and not really a priority in anyway.

**Pull request merged**
