### PR TITLE
[Dependency] replace our usages of withConsecutive() in /site

### LINKED ISSUE #8833: Replace usage of withConsecutive in phpunit tests
In the [9.6.0](https://github.com/sebastianbergmann/phpunit/blob/9c1d35553417e1ea333ce278885d3f853bc4efdb/ChangeLog-9.6.md?plain=1#L24) release of phpunit, it had:

> https://github.com/sebastianbergmann/phpunit/issues/5063: Deprecate withConsecutive()

Where this function will be removed in phpunit 10. We use this in a number of places in Submitty, so we'll want to replace it in whatever is the recommended way for phpunit 9.6+.

### PR DESCRIPTION
**Pull request by saumyaborwankar**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Replaced withConsecutive() with switch statements
Closes #8833

### Other information?
 I don't think its a breaking change.
 Tested it with phpunit using `php vendor/bin/phpunit tests/app/controllers/course/CourseMaterialsControllerTester.php` and `php vendor/bin/phpunit tests/app/controllers/admin/ConfigurationControllerTester.php`.

I have made changes according to [this
](https://github.com/wikimedia/mediawiki-libs-Equivset/commit/50a1d95212cb10c4a67f0d5cbc7cc2de3ccf31a2)

### CODE REVIEW

**Comment by williamjallen** [comment]
This PR should be re-titled.  You seem to be attempting to replace our usages of `withConsecutive()`, not bumping the version of PHPUnit as stated in the title.

**Comment by MasterOdin** [comment]
Hm, `$this->logicalOr` weakens the check here as it would just allow the args in any order, and not a specific one.

I think that we'd be maybe better off using `$this->returnCallback`, where we have something like https://github.com/sebastianbergmann/phpunit/issues/4026#issuecomment-1417794311, but using a switch statement as opposed to `match` since we target PHP 7.4. https://github.com/sebastianbergmann/phpunit/issues/4026#issuecomment-1418205424 provides an alternative approach using traits, but I think better to use the builtins of phpunit for simplicity sake.

**Comment by saumyaborwankar** [comment]
Hey, guys don't mind the last 2 commits, I was just playing around with git. I'll work on this right now and update a final commit. Sorry for the confusion.

**Comment by saumyaborwankar** [comment]
I ran the tests and all tests pass. @MasterOdin can you review this PR?

image

**Review by mohdwajahat — APPROVED** [review]

**Comment by saumyaborwankar** [comment]
@MasterOdin could you review this PR?

**Comment by bmcutler** [comment]
@saumyaborwankar Can you please resolve conflicts that have developed while this PR is awaiting review?  Thanks.

**Comment by bmcutler** [comment]
@cjreed121 please review

**Pull request merged**
