### PR TITLE
Table for rotating section history

### LINKED ISSUE #705: rotating section pattern table
We used to have a small table next to the assignment of TAs to rotating sections that showed the assignments of previous gradeables (so the instructor can establish a regular rotation pattern)

Please add it back :)

### PR DESCRIPTION
**Pull request by bdrumheller**
Adds a table above TAs showing how TAs were assigned to previous gradeables' rotating sections. 

Closes #705

### CODE REVIEW

**Comment by bmcutler** [comment]
Suggested improvements:
* The order of the graders in the table is different than the order of the graders for data entry
* The table includes **all** gradeables, would be better to just have the gradeables that have TA grading AND are graded by rotating section.

**Comment by bmcutler** [comment]
Also...  only show the graders that match the selected type in the drop down menu (e.g., don't show the limited access graders in the table nor in the data entry place if full access is selected)

**Comment by bdrumheller** [comment]
Okay.  I will make these improvements before we merge.

**Comment by bmcutler** [comment]
The list of full access graders (below the table) is still not sorted.

Also, can we add instructor users to be able to grade rotating?

**Pull request merged**
