### PR TITLE
[Refactor:InstructorUI] Refactor queries to collect data earlier

### PR DESCRIPTION
**Pull request by cjreed121**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
The instructor gradeables page makes 108 queries each page load. A lot of these queries are repetitive and can be refactored to use significantly less queries.

### What is the new behavior?
The gradeables page now uses 82 queries per page load which is about a 20% improvement. The gradeable canDelete function can be pretty expensive so I made it collect some data earlier and only query team info if it is a team gradeable.

### Other information?
There is still more work to be done here. The most expensive thing on the page is loading all of the status bars for grading but it uses a lot of query and PHP logic.

### CODE REVIEW

**Comment by bmcutler** [comment]
Is there a performance benefit for the student or TA users?

**Comment by cjreed121** [comment]
> Is there a performance benefit for the student or TA users?

There might be slight depending on if students or TAs ever call the team function. But this is mainly to increase performance of instructor page. The student page is pretty good right now and only gets bad if peer grading happens. That would see improvement for the refactor of progress bars.

**Review by ziesski — APPROVED** [review]
Looks good to me :)

**Review by williamjallen — APPROVED** [review]

**Comment by bmcutler** [comment]
@cjreed121 
Please look into failing cypress test

**Comment by cjreed121** [comment]
> @cjreed121 Please look into failing cypress test

That error is one of the flaky errors. I just re-ran the job so hopefully it passes this time.

**Pull request merged**
