### PR TITLE
GradedGradeable query gets data for all teams/users requested

### PR DESCRIPTION
**Pull request by KevinMackenzie**
Now all teams / users requested will get data returned regardless of if any grade data exists for that submitter.  This is important for pages like the nav page, where gradeable instances for all gradeables for a given user are required.  Another important page is the grades list page, where all grades for a gradeable are required for all users, even if grading hasn't been done for them yet.

### CODE REVIEW

**Comment by CouleeApps** [comment]
Is getGradedGradeables() with user ids on a team assignment supposed to return the gradeables for the teams those users are in? Because it is. Whether that is good or bad I don't know.

**Comment by CouleeApps** [comment]
If you query user ids on a team assignment you only get one gradedgradeable per team. Seems like this should be either none (because you should query by team) or have multiple copies of the same gradedgradeable to line up with the users requested.

**Comment by KevinMackenzie** [comment]
The intended behavior is for it to get the graded gradeables for the teams the users are on, so something like the nav page would get a grade for the team gradeables without having to get the teams the user is on for all gradeables

**Comment by CouleeApps** [comment]
Opinion on the second comment?

**Comment by KevinMackenzie** [comment]
I think it makes sense to only return one result per team, but I am hesitant to say that we won't want to return one instance per user.  

A bigger issue i'm seeing is that these changes don't return results for team gradeables where the requested user is not on a team.  I'm still thinking about how this case should be handled.

**Comment by CouleeApps** [comment]
If you don't have a team, you can't submit, and you don't have a Submitter. So you can't have a graded gradeable. I think that's acceptable.

**Comment by CouleeApps** [comment]
Yeah. I was trying to come up with the weirdest case to see what would happen. Rest of this looks pretty much good to me.

**Comment by CouleeApps** [comment]
Sounds like you had one other thing you wanted to do, I'll review/approve after that or if you decide not to.

**Comment by KevinMackenzie** [comment]
I think I've resolved/thought out all of the comments/issues I've had.

**Pull request merged**
