### PR TITLE
Twig last few views

### LINKED ISSUE #2053: Migrate all of the PHP views to Twig
Views to do (mid-summer):

- [x] TA Grading
   - [x] Information Panel (waiting on a pull request)
   - [x] Regrade Panel
- [x] Autograding
   - [x] Checks list

Waiting on changes and for a later issue:

- Forums (by @scopeInfinity)
   - Thread
   - Create Thread
   - Statistics
   - Search
- Plagiarism (currently unfinished)
- ~~Diff viewer~~ (unlikely)

### PR DESCRIPTION
**Pull request by CouleeApps**
Biggest part of this PR is the autograding checks view. Also included is the student info panel and the regrade panel of TA grading. Closes #2053

Merge this after #2238 and #2198

### CODE REVIEW

**Comment by KevinMackenzie** [comment]
My autograding isn't run, so I can't check that right now, but the other two forms look good

**Comment by CouleeApps** [comment]
I'm adding that to the laundry list... Should be better now.

**Comment by jchulton** [comment]
Getting this after I created a gradable, submit for a student, grade it, then attempt to edit the gradable (using the edit button)
autogradingerror2

**Comment by CouleeApps** [comment]
Last I heard the verdict on that error was that it is also present on master, and thus not a problem for this PR.

**Comment by KevinMackenzie** [comment]
Can someone who's encountered this problem make a new issue for it?

**Pull request merged**
