### PR TITLE
[VPAT:Forum] Improve New Post Background in Dark Mode

### LINKED ISSUE #6543: Background color for new forum posts in dark/black mode
**Describe the bug**
new posts in dark mode should be highlighted with a background color.
(In light mode they are light blue vs white for old posts)

Also, when modified, please update documentation:
https://submitty.org/student/communication/forum

### PR DESCRIPTION
**Pull request by eddiekrystowski**
### Please check if the PR fulfills these requirements:
* [x] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #6543 
Currently, in dark mode new/unread posts/threads are marked by a background color that is barely different from the main site background color.

Screen Shot 2021-06-01 at 10 30 37 AM

### What is the new behavior?
* The viewed-content color has been adjusted to give better contrast in dark mode

Screen Shot 2021-06-01 at 10 29 09 AM

### CODE REVIEW

**Review by HenrikLam — APPROVED** [review]
Looks good! Works as described.

**Comment by bmcutler** [comment]
Is it just me or do other people have a hard time seeing the difference between new & old, even with the new color choices?  It is hard to describe in words (like for the documentation page, or doing verbal tech support) which color is which.

(I'm not a regular dark mode user, so if most everyone likes this we can keep it.)

**Comment by HenrikLam** [comment]
> Is it just me or do other people have a hard time seeing the difference between new & old, even with the new color choices? It is hard to describe in words (like for the documentation page, or doing verbal tech support) which color is which.
> 
> (I'm not a regular dark mode user, so if most everyone likes this we can keep it.)

My first thought was that it isn't obvious which color represents new vs which represents old. However, I wasn't able to come up with a better solution. I can see why the difference might not be obvious though! Perhaps we can use an even darker background?

**Comment by eddiekrystowski** [comment]
Yea, I thought so as well, but when I went with darker backgrounds, it starts to be hard to tell on black mode. Perhaps we can add some kind of indicator like this:

image
image

image
image

**Comment by HenrikLam** [comment]
> Yea, I thought so as well, but when I went with darker backgrounds, it starts to be hard to tell on black mode. Perhaps we can add some kind of indicator like this:
> 
> image
> image
> 
> image
> image
> 
> This way, besides the colors, there is a clear visual indicator that a post should be looked at.

Yeah that looks good! It's a very clear indication that a thread is new and very intuitive as well. Still perhaps the background color issue can be brought up during the meeting to see if anyone has any ideas.

**Review by HenrikLam — COMMENTED** [review]
Yeah that looks good! It's a very clear indication that a thread is new and very intuitive as well. Still perhaps the background color issue can be brought up during the meeting to see if anyone has any ideas, if not I can approve it.

**Comment by eddiekrystowski** [comment]
Okay, I tried making the background color as light as it could go while still maintaining 7:1 contrast ratio with the white text. Let me know what you think.

image
image

**Comment by HenrikLam** [comment]
Is the viewed threads the one that is the same color as the background? That is what I intuitively think but I'm getting a little confused, sorry. Otherwise the contrast is very nice and obvious!

**Comment by eddiekrystowski** [comment]
Yes, that is how it works on light mode, the viewed ones are white like the background and the rest are light blue.

**Review by HenrikLam — APPROVED** [review]
Good contrast between viewed threads and new threads, intuitive too that new threads stand out from the background.

**Pull request merged**
