### PR TITLE
[Feature:InstructorUI] Option to collect contact information for office hours queue

### PR DESCRIPTION
**Pull request by elihschiff**
### Please check if the PR fulfills these requirements:

* [X] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [X] Tests for the changes have been added/updated (if possible)

### What is the current behavior?

RPI has shut down the campus and we have no way to run office hours

### What is the new behavior?

I added a setting to the course settings page to enable the ability for students to add contact info to the office hours queue.
image
Once checked, students will not be required to add their contact info to join the office hours queue for that class.
image
Contact info is just a required textbox, so you can send an email, a url, or anything else.
For instructors/mentors/tas they will see this contact info under the student in the queue
image

### CODE REVIEW

**Comment by matgar1997** [comment]
I think it would be helpful for the student view to also see the instructions for contacting on their page incase they put in a type. Or perhaps a more dynamic approach would allow the instructor to ask for clarification and the student could edit on their page without needing to leave and re-enter the queue. Sort of like a chat system but only keep track of one editable string for simplicity.

I also probably wouldn't specifically mention pandemic under the instructor settings. Leave it for any case which would need a remote queue. 

Other then the suggestions the functionality looks good.

**Comment by elihschiff** [comment]
I feel like if the problem can be solved by a text question they can just use the discussion forum. The only reason to join the office hours queue is if you need to screen share or voice chat. So I cannot think of a time when you would need more clarification that you cannot hear in person once you connect to them.

Also I do not think it is smart to put instructor contact info on the student page. I as a mentor do not want students contacting me, I cannot see how that will end well, I want to contact them when it is their turn.

The use of "pandemic" is very important :frowning:, I vote to keep it

**Comment by shailpatels** [comment]
Is this an actual issue that was discussed in person? The mentions of pandemic make this feel like a joke PR but it looks like a lot of work has gone into it.
I don't see the point of implementing a method to contact students through the queue virtually since the queue was originally designed for managing people in a physical space.

If a school decides to run a course online while using Submitty I think the existing infrastructure they are/will using be able to handle students who want help. I image jumping between Slack/WebEx/Zoom and then to Submitty office hours Q and then back to whatever isn't very intuitive...

**Comment by elihschiff** [comment]
Ok the use of pandemic I just added. I can remove it 😢

But the rest of this pr was discussed over slack. Because rpi is going fully online for classes we need a way for students to let mentors know how to contact them when it is their turn for help. Students would put in their webex, skype, discord, etc. Account and a mentor would then contact them.

**Comment by bmcutler** [comment]
Thanks @elihschiff!

**Pull request merged**
