### PR TITLE
Fixed empty button in seating

### PR DESCRIPTION
**Pull request by mktung**
We were accidentally hiding the wrong element

### CODE REVIEW

**Comment by zjxiaohan** [comment]
I am a bit confused about this... See: https://github.com/Submitty/Submitty/pull/4097

It looks like we are waiting for a whole page UI refresh?

**Comment by MasterOdin** [comment]
This also retains the button inside a button design which looks (to me) weird:
Screen Shot 2019-07-14 at 9 29 28 PM

**Comment by mktung** [comment]
I fixed the button border, but like Han said I'm not sure if we should be merging this or not? Unclear what the objective is

**Comment by bmcutler** [comment]
Maya,
Please address this issue when you refactor the page for mobile.  
Thanks

**Pull request closed without merging**
