### PR TITLE
Replace broken clean_string* functions with htmlspecialchars

### PR DESCRIPTION
**Pull request by bdrumheller**
clean_string and clean_string_javascript didn't work as intended and have been removed or replaced with htmlspecialchars(); 

This will prevent code written in comments from being executed.

### CODE REVIEW

**Comment by MasterOdin** [comment]
I'm fine with these changes.I'd like the pull request name to be changed to "Replace broken clean_string* functions with htmlspecialchars" as the current title is not very clear as to what you did.

**Comment by bdrumheller** [comment]
I changed the name as requested.

**Comment by MasterOdin** [comment]
I'm good with this being merged now.

**Comment by MasterOdin** [comment]
I'm good with this being merged now.

**Pull request merged**
