### PR TITLE
[Feature:TAGrading] change Cancel to Discard

### LINKED ISSUE #9018: “OK” and “Cancel” buttons in alert for canceling a rubric item are confusing
**What problem are you trying to solve with Submitty**
When you’re editing the grade for a particular rubric item in the grading interface, there’s a “Cancel” button to discard the changes to the grade. (See the first screenshot, in which I’ve drawn a red box around the relevant button.) Clicking this button triggers a browser-native alert that asks that you confirm that you do indeed want to discard the changes. (See the second screenshot.) This alert has an “OK” button as well as its own “Cancel” button, which is separate from the original “Cancel” button. As a result, the alert’s “OK” button really means “yes, do indeed discard the changes”, whereas the alert’s “Cancel” button really means “never mind, don’t discard the changes”. In other words, “OK” means “cancel”, and “Cancel” means “cancel the cancelation”. This is very confusing.

**Describe the way you'd like to solve this problem**
The “Cancel” button in the grading interface (not the alert) should be retitled to “Discard”, the “OK” button in the alert should also be retitled to “Discard”, and the “Cancel” button in the alert should stay as “Cancel”. These new button titles would make it obvious what the respective buttons will actually do. This scheme follows Apple’s [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts#buttons), which are widely regarded as the gold standard of design guidelines, even for general principles that aren’t specific to Apple’s own platforms.

**Describe any potential alternatives you'd tried to solve the problem**
I considered other combinations of button titles, but they all had less clarity and went against established general design principles.

**Additional context**
Screenshot 2023-03-08 at 11 21 04 PM
Screenshot 2023-03-08 at 11 20 20 PM

### PR DESCRIPTION
**Pull request by saumyaborwankar**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

The current issue was that the button named 'Cancel' was misleading. So it was expected to be 'Discard' instead.
closes #9018 
### What is the new behavior?
Changed 'Cancel' to 'Discard'

### Other information?

Tested locally.
image

### CODE REVIEW

**Review by ch3nnyj — CHANGES_REQUESTED** [review]
I tested your changes, the cancel button still seems to not be changed. Perhaps you are not editing the right file related to grade rubrics. I've linked a screen shot below. The Cancel/Save should be Discard/Save
Screenshot 2023-03-21 at 1 47 54 PM

**Comment by saumyaborwankar** [comment]
Hi @ch3nnyj can you tell me how to reproduce your issue, because I'm able to see the change in my local environment.
Steps to see my changes:
1) Log in as 'ta' 
2) Go to 'sample' course and choose 'Gradeables' from the left panel
3) Under 'GRADING IN PROGRESS', under 'Closed Peer Team Homework', select 'GRADE' button (blue color)
4) Click on blue 'GRADE' button for a user '00109_aphacker' 
5) Select 'Rubric' and see the Discard button.

image

**Comment by williamjallen** [comment]
@ch3nnyj You may need to "force refresh" when observing UI changes in the TA grading interface.  Twig.js is very aggressive about caching things, and it's used quite a bit throughout the TA grading interface.

**Comment by ch3nnyj** [comment]
@williamjallen I have forced refreshed and it still hasn't changed on Safari. Even closed and restarted the browser.

**Comment by ch3nnyj** [comment]
I've rechecked it and I looks good now. Probably an issue on my end, since it seemed to be fixed now!

**Review by hansongu123 — APPROVED** [review]
Fairly simple change. I don't know if the change was needed in the first place for consistency, but looks good to me now so I'm approving.

**Review by ch3nnyj — APPROVED** [review]
Ready to merge looks good

**Pull request merged**
