### PR TITLE
[BugFix:InstructorUI] Course Material Colors Safari

### PR DESCRIPTION
**Pull request by matgar1997**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?

In course materials page on safari, no matter when something was due it appeared yellow for when an item should be released.
Screen Shot 2020-02-04 at 9 09 30 PM

### What is the new behavior?
It comes up as the correct color, after a refresh. Red if due 10+ years away, green if open now, yellow if somewhere in between
Screen Shot 2020-02-04 at 9 24 37 PM

### Other information?

Nothing changes on chrome, but safari still requires the page to reload

Tested on all three time ranges in safari and chrome

### CODE REVIEW

**Comment by shailpatels** [comment]
@matgar1997 Can you make the same requested changes to the `setNewDateTime` function in server.js .

**Comment by bmcutler** [comment]
@matgar1997 Please resolve conflicts and address requested changes

**Comment by matgar1997** [comment]
Not experienced with merge conflicts, might have broken something

**Comment by matgar1997** [comment]
Resolving the second merge conflict caused database issues related to duplicate key errors on courses_fkey, so I was not able to test the most recent commit. but the previous one which changes server.js does work

**Pull request merged**
