### PR TITLE
[Bugfix:Forum] Hide future categories

### LINKED ISSUE #10903: unreleased forum categories shown in filter
**Describe the bug**

I  have set my future homework categories to release on future dates:
Screenshot 2024-08-31 at 1 32 42 PM

The unreleased categories are removed fromt the create thread list:
Screenshot 2024-08-31 at 1 33 48 PM

But they are still visible in the filter:
Screenshot 2024-08-31 at 1 34 58 PM

**Expected behavior**
The filter should only contain released categories.

### PR DESCRIPTION
**Pull request by itsashishrath**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current  #behavior?
unreleased forum categories shown in filter Fixes #10903

### What is the new behavior?
Its not showing now. 
I checked `threadpostform.twig` file, where the behavior was right. It was simply checking if the visible date is null or less than current time.
Therefore I added the same logic in `ForumBar.twig` file, I checked it worked fine, 

### Other information?
I have attached the screenshot
Unreleased Future category
Screenshot 2024-09-05 121233

Now its not present in filters inside forum.
Screenshot 2024-09-05 115243

### CODE REVIEW

**Review by williamschen23 — CHANGES_REQUESTED** [review]
The number in Filter (X) does not reflect this change

**Comment by williamschen23** [comment]
image
I have one hidden thread and 8 visible ones

**Comment by itsashishrath** [comment]
> image I have one hidden thread and 8 visible ones

Actually, I am not able to reproduce this bug, Can you tell me how to hide the thread, The X in Filter(X) shows the number of threads below, Also if I select a particular category, it doesn't show only that threads, it keeps on showing all threads. Can you help me or point out where should i look? Thank you

**Comment by williamschen23** [comment]
You are right I am a little dumb my bad

**Review by williamschen23 — APPROVED** [review]

**Pull request merged**
