### PR TITLE
[Bugfix:TAGrading] Submission file half line bug

### LINKED ISSUE #4525: 'Open/Close Submissions' button shows half of one line of code
**Describe the bug**
When clicking the 'Open/Close Submissions' button after opening the submission folder manually, the embedded code box only displays half of one line of code. Only way to fix is to reload page.

**Expected behavior**
If some part of the submissions tree is open, a click of the 'Open/Close Submissions' button should either toggle the whole tree open or closed, with the files displaying at their normal size.

**To Reproduce**
1. Go to grading interface, as you do when grading a single student's code submission
2. Open the "Submissions" folder in the "Submissions and Results Browser"
3. Click the "Open/Close Submissions" button to close submissions tree
4. Click the "Open/Close Submissions" button again to open submissions tree

**Configuration**
 - OS: Ubuntu 18
 - Browser: Firefox

**Screenshots**
image

### PR DESCRIPTION
**Pull request by HenrikLam**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?

Fixes #4525 

It was possible to produce a bug where when viewing the files submitted by a student in a gradeable, the frame for the file only shows half of a line.  The bug is also not fixable on the client's side without reloading the page or editing the html elements. The steps to produce this is the following:
 1. Go to the grading interface as a TA for a student
 2. Open the files panel in any panel viewing mode
 3. Open the Submissions folder
 4. Click the Open/Close Submissions button
 5. Open the Submissions folder again
 6. Each file is now displayed with only half a line of display
image

### What is the new behavior?
The bug is fixed and following the above steps does not automatically open the files when you open the submissions folder a second time.
When you open the Submissions folder a second time:
image
When you open each file inside the folder:
image

### CODE REVIEW

**Review by eddiekrystowski — CHANGES_REQUESTED** [review]
Works for the submission folder, but if you do it with the results folder, only the first level seems to work correctly:
image

**Comment by bmcutler** [comment]
In addition to the submission & results top level directories, if this is a submission by git, there will also be a checkout directory at the top level with files.  (We usually forget to test this.)

**Review by eddiekrystowski — APPROVED** [review]
Looks like both the submission and results folder work properly now. I tried testing the checkout folder like @bmcutler mentioned, but it kept trying to clone https://www.github.com/eddiekrystowski/undefined no matter what I put for the repo name. Perhaps there is an issue there, unless I am doing something wrong. Either way, it generated a folder with a single text file and that folder didn't seem to have the issue.

**Comment by HenrikLam** [comment]
I tested the git submission as well, and the pull request seems to also work for that case.

**Comment by bmcutler** [comment]
Note: 
We only regularly use git submission by server-hosted private git repos.
(for RPI PSoft and a few other courses).  Using public github repos has been tested a bit, but perhaps not recently.  Using private github repos (some form of credentials required) is future work.

https://submitty.org/instructor/managing_git
(these instructions likely need revision)

**Pull request merged**
