### PR TITLE
[Refactor:TAGrading] TA status page refactor

### PR DESCRIPTION
**Pull request by jportorreal00**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

The status page for a gradeable was previosuly all combined onto one massive twig file.

### What is the new behavior?
Each tab of the navigation bar is now in its own .twig (much like the admin_gradeable .twig files)

### CODE REVIEW

**Review by shailpatels — CHANGES_REQUESTED** [review]
I'm seeing the following error on electronic gradeables under the `closed` and `grades released` sections

```
 Oh no! Something irrecoverable has happened...

Error (Code: 0) thrown in /usr/local/submitty/site/app/controllers/grading/ElectronicGraderController.php (Line 76) by:
                if ($ov->getTaGradedGradeable()->getGradedGradeable()->getSubmitter()->getRegistrationSection() != NULL) {


Message:
Call to a member function getGradedGradeable() on null

Stack Trace:
#0 /usr/local/submitty/site/app/controllers/grading/ElectronicGraderController.php(642): app\controllers\grading\ElectronicGraderController->generateHistogramData(Array)
#1 unknown file(unknown line): app\controllers\grading\ElectronicGraderController->showStatus('open_homework')
#2 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(217): call_user_func_array(Array, Array)
#3 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(195): app\libraries\routers\WebRouter->run()
#4 /usr/local/submitty/site/public/index.php(128): app\libraries\routers\WebRouter::getWebResponse(Symfony\Component\HttpFoundation\Request, app\libraries\Core)
```

**Comment by jportorreal00** [comment]
@shailpatels I wasn't able to replicate the error, but I added null checks every time the TA gradeable is called

**Review by emaicus — APPROVED** [review]
This PR is a great step in the right direction. Future work can further simplify the individual twig files/decide whether logic should be done in `javascript` or moved to `php`. I did not experience the same issues as @shailpatels, so it would be appreciated if he could follow up. Otherwise, once tests are passing and merge conflicts are fixed, I think that this is good to go.

**Review by emaicus — APPROVED** [review]
Still looks to be in good shape.

**Pull request merged**
