### PR TITLE
[Feature:Calendar] Changed Calendar Cells Based on View

### PR DESCRIPTION
**Pull request by arougey**
Changed the calendar cells to be larger based on the viewing mode(month, two-week, week)

Screenshot from 2024-03-25 15-29-22

Screenshot from 2024-03-25 15-29-09

The current behavior is that if you change viewing modes from 'Month' to 'Two Week' or 'Week', it simply hides the extra weeks. The purpose of the other view modes is to make cells larger to fit more information and be less crammed for users who have many items on their calendar.

The new behavior is that the cells will expand based on the viewing mode as well as the number of items in each cell. 

This is not a breaking change and was tested on instructor and student accounts.

### CODE REVIEW

**Review by ArnavPawar — APPROVED** [review]
Looks good the size is bigger. Code makes sense. Just fix lint fix and you should be good.

**Review by jeffrey-asm — APPROVED** [review]
The changes look good. The weekly and bi-weekly calendar views are much larger, allowing more items for a given day.

**Review by JoJo-ESC — COMMENTED** [review]
I couldn't the changes due to a. pop up error

**Review by RayReyRam — CHANGES_REQUESTED** [review]
When reviewing there was an error popup shown in the screenshot below, if this gets fixed the calendar looks good and works as intended
image

**Review by ryvaru — APPROVED** [review]
Works, each time I change the view it gets noticeably larger or smaller depending on each view and allowing for more cells to fit on the screen.

**Comment by ryvaru** [comment]
> Works, each time I change the view it gets noticeably larger or smaller depending on each view and allowing for more cells to fit on the screen.

There seems to be an fatal issue disclosed above, I rechecked and it appears to be there.

**Comment by arougey** [comment]
> When reviewing there was an error popup shown in the screenshot below, if this gets fixed the calendar looks good and works as intended image

This error is not related to my PR and can be reproduced on the main branch.

**Comment by arougey** [comment]
> > Works, each time I change the view it gets noticeably larger or smaller depending on each view and allowing for more cells to fit on the screen.
> 
> There seems to be an fatal issue disclosed above, I rechecked and it appears to be there.

The issue is on main and not related to my PR

**Comment by arougey** [comment]
> I couldn't see the changes due to a pop up error

What was the error? The AbstractDatabase error is not related to my PR.

**Comment by IDzyre** [comment]
> > I couldn't see the changes due to a pop up error
> 
> What was the error? The AbstractDatabase error is not related to my PR.

https://github.com/Submitty/Submitty/pull/10318 should fix that error.

**Review by williamjallen — APPROVED** [review]

**Review by JoJo-ESC — APPROVED** [review]
Despite the abstract database error (which isn't apart of your PR) the changes do seem to not have broke anything and the sizes of the boxes do seem responsive to changes based on length requested.

**Pull request merged**
