### PR TITLE
[Testing:TAGrading] Peer anonymization testing

### PR DESCRIPTION
**Pull request by jchulton**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
There is no testing in place to ensure that students cannot use inspect element to extract the ids of the student(s) they are grading
### What is the new behavior?
Testing has been added to ensure students cannont extract the ids of the students they are grading

### CODE REVIEW

**Comment by jchulton** [comment]
This branch introduces and relies on sample peer gradeables. In order to test this branch, you will have to run sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh if you have not run it on another branch that introduces sample peer gradeables

**Review by Kevin-MM — DISMISSED** [review]
Hi @jchulton , on the new TA grading interface the grade inquiry button is visible but doesn't appear to do anything.

I ran all the e2e tests you have modified in this PR and attached logs for any failures (this done immediately after recreate_sample_courses completed):

```
python3 -m unittest e2e.test_anon_mode.TestAnonMode
.F
======================================================================
FAIL: test_peer_team_anon (e2e.test_anon_mode.TestAnonMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_anon_mode.py", line 41, in test_peer_team_anon
    self.assertFalse("thompc" in page_source_processed)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 2 tests in 20.526s

FAILED (failures=1)
```

```
python3 -m unittest e2e.test_pdfs.TestPDFs
EEEE
======================================================================
ERROR: test_pdf_basic_access (e2e.test_pdfs.TestPDFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 13, in test_pdf_basic_access
    self.pdf_access("instructor", "bechta", "grading_homework_pdf", "words_249.pdf", "2")
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 53, in pdf_access
    self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/'+gradeable_id+'/grading/grade?who_id='+student_id+'&sort=id&direction=ASC")]').click()
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,"/sample/gradeable/grading_homework_pdf/grading/grade?who_id=bechta&sort=id&direction=ASC")]"}
  (Session info: chrome=84.0.4147.105)


======================================================================
ERROR: test_pdf_peer_access (e2e.test_pdfs.TestPDFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 30, in test_pdf_peer_access
    self.pdf_access("instructor", "bechta", "grading_pdf_peer_homework", "words_249.pdf", "1")
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 53, in pdf_access
    self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/'+gradeable_id+'/grading/grade?who_id='+student_id+'&sort=id&direction=ASC")]').click()
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,"/sample/gradeable/grading_pdf_peer_homework/grading/grade?who_id=bechta&sort=id&direction=ASC")]"}
  (Session info: chrome=84.0.4147.105)


======================================================================
ERROR: test_pdf_peer_team_access (e2e.test_pdfs.TestPDFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 40, in test_pdf_peer_team_access
    self.pdf_access("instructor", "00006_bechta", "grading_pdf_peer_team_homework", "words_1463.pdf", "1")
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 53, in pdf_access
    self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/'+gradeable_id+'/grading/grade?who_id='+student_id+'&sort=id&direction=ASC")]').click()
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,"/sample/gradeable/grading_pdf_peer_team_homework/grading/grade?who_id=00006_bechta&sort=id&direction=ASC")]"}
  (Session info: chrome=84.0.4147.105)


======================================================================
ERROR: test_pdf_team_access (e2e.test_pdfs.TestPDFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 22, in test_pdf_team_access
    self.pdf_access("instructor", "00002_aphacker", "grading_homework_team_pdf", "words_881.pdf", "1")
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 53, in pdf_access
    self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/'+gradeable_id+'/grading/grade?who_id='+student_id+'&sort=id&direction=ASC")]').click()
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,"/sample/gradeable/grading_homework_team_pdf/grading/grade?who_id=00002_aphacker&sort=id&direction=ASC")]"}
  (Session info: chrome=84.0.4147.105)


----------------------------------------------------------------------
Ran 4 tests in 136.613s

FAILED (errors=4)
```

**Review by Kevin-MM — CHANGES_REQUESTED** [review]
I did a recreate sample courses and then ran the e2e tests for which there were changes in this PR.  Everything is working except for the pdf tests.

Here are my results from the PDF tests (ran in headless mode).
```
python3 -m unittest e2e.test_pdfs.TestPDFs
.E.E
======================================================================
ERROR: test_pdf_peer_access (e2e.test_pdfs.TestPDFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 27, in test_pdf_peer_access
    self.pdf_access("grader","2", "8", "grading_pdf_peer_homework", "words_249.pdf", "1")
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 44, in pdf_access
    (self.driver.find_element_by_xpath("//tbody[@class='details-content panel-content-active']/tr["+tr_number+"]/td["+td_number+"]").find_elements_by_tag_name("a")[0]).click()
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//tbody[@class='details-content panel-content-active']/tr[2]/td[8]"}
  (Session info: headless chrome=85.0.4183.102)


======================================================================
ERROR: test_pdf_team_access (e2e.test_pdfs.TestPDFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 19, in test_pdf_team_access
    self.pdf_access("instructor", "1", "8", "grading_homework_team_pdf", "words_881.pdf", "1")
  File "/home/kevin/Submitty/Submitty/tests/e2e/test_pdfs.py", line 48, in pdf_access
    self.driver.find_element_by_id('open_file_'+pdf_name).click()
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kevin/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="open_file_words_881.pdf"]"}
  (Session info: headless chrome=85.0.4183.102)


----------------------------------------------------------------------
Ran 4 tests in 131.167s

FAILED (errors=2)
```

**Comment by bmcutler** [comment]
closing due to inactivity and merge conflicts

**Pull request closed without merging**
