### PR TITLE
Switching to/from edit mode won't close component

### PR DESCRIPTION
**Pull request by KevinMackenzie**
Part of #2680 

when toggling the 'edit mode' of the TA grading rubric, the component will not close/open itself.  This changes some pretty important parts of the code, so marked as WIP so it can be more thoroughly tested.

Changes that should be made:
- [x] 'Loading' message should show up when switching modes since it takes a a couple seconds

### CODE REVIEW

**Comment by KevinMackenzie** [comment]
My solution prevents the user from rapidly toggling the edit mode button, which is the root cause of many potential problems.

**Comment by emaicus** [comment]
Just tested the PR again. The problem is still present. Better than stopping rapid toggling, can we look into why marks are duplicated to begin with, and the source of the ```Error saving component! Missing mark id in order array and duplicates all new marks.``` message?

**Comment by KevinMackenzie** [comment]
From what I can tell, the event for saving the components is being triggered multiple times before the first one completes.  Multiple identical events are being handled while the asynchronous ajax requests are being completed, so the data is getting into a bad state and the same 'new' marks are being submitted as 'new' every time.  The solution I'm trying to employ is preventing multiple simultaneous events from firing.  I'll find a more robust way to do this.

**Comment by KevinMackenzie** [comment]
I found the source of your mark order error @emaicus.  There was some function composition that wasn't done correctly.  Now you should be able to toggle edit mode as quickly as you want and it shouldn't give you the same errors (or at least not for the same reason).  This should also fix some similar problems when trying to verify a component and edit the rubric in rapid succession.

**Pull request merged**
