### PR TITLE
User can now collapse posts.

### PR DESCRIPTION
**Pull request by saxocellphone**
One of the elements of #1827, can possibly add animation, but that's up for discussion.

### CODE REVIEW

**Comment by andrewaikens87** [comment]
Overall pretty good, here are some of the initial things I noticed. Take a look at the screenshots below:

Take for example a thread that looks like this:
collapseexample

If we collapse the third reply it works well.
onecollapsed

But notice if we then try to collapse the second post, it breaks, displaying the fourth post again.
second collapse

Also, we probably should not be displaying the `[-]` unless it has functionality. So for a post that doesn't have any replies to it, it probably shouldn't have a `[-]` as it won't have any functionality. Also take a look at [https://fontawesome.com/icons?d=gallery&m=free](https://fontawesome.com/icons?d=gallery&m=free), it might be nice to use this for the +/-. I can take a look at and provide more specific feedback on the code once this is resolved.

**Comment by saxocellphone** [comment]
I tried to recreate the bug, but I can't seem to do it. Here is what I have
capture

**Comment by MasterOdin** [comment]
I think I'd like to add a new CSS class to handle the brackets in the text:
```
.brackets {
    text-indent: 0px;
    white-space: nowrap;
}
.brackets:before {
    content: "[";
}
.brackets:after {
    content: "]";
}
```
to make it easier for us to change this in the future (if we want) or apply this similar setup elsewhere.

**Comment by andrewaikens87** [comment]
I stress tested it and couldn't make the collapsing break so I think we are good as it now has the button. But before we merge did we agree on "hide children" and "[show NUM]" for the button text? It might be more appropriate to do "Hide replies" and possibly "Show replies (NUM)" (the parenthesis can be interchanged with brackets). Also should the button in the instructor view be on the right of the x and edit buttons? What do you think?

positioning

**Pull request merged**
