### PR TITLE
[Feature:InstructorUI] Turn off gradeable due/release date

### PR DESCRIPTION
**Pull request by jportorreal00**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

#5846 
Currently we are able to turn off submission due dates, but not release dates. The placement of gradeables on the homepage is also less than ideal when it comes to the gradeable placement. Gradebles with no due date end up in the "RELEASED" section.

### What is the new behavior?
Turn on or off due dates and release dates. The placement of of gradeables is now improved based on the recommendations in the issue.

### Other information?

~~This could be a breaking change since the "NOT NULL" constraint was dropped in the database. I found a few places where we rely on these dates existing so I have been changing them.~~
The database now holds an additional boolean for storing whether or not the gradeable has a due date. If a gradeable has a due date then it cannot have a release date. Instructors must add a due date and release date later if they plan to release grades overall. Grades can still be accessed and grade inquiries can be made during the open period if a gradeable has no due date. This would be for a work as you go class.

### CODE REVIEW

**Review by shailpatels — CHANGES_REQUESTED** [review]
When submissions are closed with a gradable with no release date but grading is still occurring the "Release Grades Now" button shows up still. Pressing this gives an error message "saying grades already released" so I think this button should be removed for this type of gradeable

Are gradeables supposed to be in the "Released Section" I've only been able to see them in the "Closed for grading" section. Do all students need to submit and get graded before it moves ?

**Comment by shailpatels** [comment]
@jportorreal00 I'm still seeing the same issue where the option to release a gradeable exists for a gradeable with no release date. I was testing by creating a new gradeable

**Review by shailpatels — CHANGES_REQUESTED** [review]
See above comment

**Comment by shailpatels** [comment]
When switching to this branch and creating gradeables with null dates, then reverting or switching to an older branch causes the following frog error:

@jportorreal00 , @bmcutler this might be a case where we would want a down migration to replace any null dates with a real date set way in the past or future or something

```
app\exceptions\ValidationException (Code: 0) thrown in /usr/local/submitty/site/app/models/gradeable/Gradeable.php (Line 717) by:
            throw new ValidationException('Date validation failed', $errors);


Message:
Date validation failed

Stack Trace:
#0 /usr/local/submitty/site/app/models/gradeable/Gradeable.php(791): app\models\gradeable\Gradeable->assertDates(Array)
#1 /usr/local/submitty/site/app/models/gradeable/Gradeable.php(300): app\models\gradeable\Gradeable->setDates(Array)
#2 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(4453): app\models\gradeable\Gradeable->__construct(app\libraries\Core, Array)
#3 unknown file(unknown line): app\libraries\database\DatabaseQueries->app\libraries\database\{closure}(Array)
#4 /usr/local/submitty/site/app/libraries/database/DatabaseRowIterator.php(56): call_user_func(Closure, Array)
#5 /usr/local/submitty/site/app/models/gradeable/GradeableList.php(72): app\libraries\database\DatabaseRowIterator->next()
#6 /usr/local/submitty/site/app/controllers/NavigationController.php(32): app\models\gradeable\GradeableList->__construct(app\libraries\Core)
#7 unknown file(unknown line): app\controllers\NavigationController->navigationPage()
#8 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(217): call_user_func_array(Array, Array)
#9 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(195): app\libraries\routers\WebRouter->run()
#10 /usr/local/submitty/site/public/index.php(128): app\libraries\routers\WebRouter::getWebResponse(Symfony\Component\HttpFoundation\Request, app\libraries\Core)
Extra Details:
submission_due_date: Invalid date-time value!
```

**Comment by bmcutler** [comment]
@cjreed121 
Can you please fix the merge conflicts?

**Comment by bmcutler** [comment]
Clicking "show all dates" and then toggling "will this assignment have a due date" shows bugs in the display of the complete set of (greyed out) dates:

Screen Shot 2021-07-19 at 9 31 20 AM
Screen Shot 2021-07-19 at 9 31 35 AM

**Comment by bmcutler** [comment]
might not be directly from this PR: clicking on rainbow grades -> web based rainbow grades generation:

Screen Shot 2021-07-19 at 9 43 55 AM

**Comment by cjreed121** [comment]
> might not be directly from this PR: clicking on rainbow grades -> web based rainbow grades generation:
> 
> Screen Shot 2021-07-19 at 9 43 55 AM

Fixed in https://github.com/Submitty/Submitty/pull/6768

**Review by bmcutler — APPROVED** [review]
The display of "Show All Dates" is still sorta buggy/unclear, but that's only for debugging so I'll let it go.  Quick test seemed to work fine :)

**Pull request merged**
