### PR TITLE
[Feature] TA/Instructor can lock Thread

### LINKED ISSUE #2269: Forum: Instructor/full access ta can lock thread
Separated from #1677

Instructor/full access ta can specify a 'lock' date for a thread.
After that date, all can view, but the only instructor can edit.

### PR DESCRIPTION
**Pull request by drumilpatel2000**
Continuation of #3444 

Fixes #2269

### CODE REVIEW

**Comment by drumilpatel2000** [comment]
@andrewaikens87 Thanks for reviewing. I solved the first issue but I don't get what is the point of second issue. Can you explain in detail about the problem?

**Comment by andrewaikens87** [comment]
Sure! Please let me know if this is unclear.

Here are two examples of the unexpected behavior (the following screenshots are from a student user):

- When creating a thread as a student, if I post a timestamp with my thread data (refer the the image below), I can set a lock thread date.

studentLocked

Then when the form is submitted: 

ah

- Another example is when the student edits their thread. The same behavior occurs. Please refer to the images below.

test2

Then when the form is submitted: 

studentLockedFromEdit

We shouldn't allow students to modify this field. This ability should be left for privileged users (TA/Instructors) only.

**Comment by drumilpatel2000** [comment]
Screenshot from 2019-05-25 14-43-42
@andrewaikens87  Is this okay?

**Comment by andrewaikens87** [comment]
@drumilpatel2000 I agree that we should not display the edit / delete buttons after we lock a thread. 

Although, we need to make sure that the corresponding functionality doesn't work (i.e. using the `deletePostToggle` JavaScript function I am still able to delete posts from a locked thread).

Also, the explained issue above with students being able to change a thread they've created to being locked still persists. I will post a video in the slack channel demonstrating a simple way of recreating the issue.

**Comment by drumilpatel2000** [comment]
@andrewaikens87 Can you please review it again?
Now user cannot delete using javascript and student cannot set thread lock date

**Pull request merged**
