### PR TITLE
New Gradeable model integration into ajax SubmissionController methods

### PR DESCRIPTION
**Pull request by KevinMackenzie**
(see #2317).

The ajax methods in the `SubmissionController` now use the new Gradeable model.  This also means that an entire `GradeableList` does not need to be constructed for these routes.  The `HomeworkView`-rendering route still constructs the `GradeableList` as to not break it.

This conversion is designed to modify as little of the code as possible, so improvements that can be made by having access to the new model will be made in later PR's.

### CODE REVIEW

**Comment by KevinMackenzie** [comment]
marked WIP until I get the tests passing

**Comment by jchulton** [comment]
Getting the following error when I try to resubmit
teamsaveerror

if I try to resubmit as a team, I see this on the instructor grading page 
teamsaveerrorp2

**Comment by KevinMackenzie** [comment]
The first error you're seeing should be fixed now, but I couldn't reproduce the second error.

**Comment by KevinMackenzie** [comment]
The second error you're seeing is a reason why we should have #2371

**Comment by bmcutler** [comment]
@KevinMackenzie please fix merge conflicts

**Pull request merged**
