### PR TITLE
consider: add external url to lab instructions

### PR DESCRIPTION
**Pull request by JerameyATyler**
There are 3 sql commands that would have to be ran in order on each course's database. 

1) This would need to be ran before installing these changes. It adds the new column to gradeable table:

ALTER TABLE gradeable
  ADD g_instructions_url VARCHAR(255) not null;

2) This would need to be ran after installing the changes. Nothing should break if this isn't ran quickly after the update, just no one would see the URL instructions. This copies all of the url instructions from the corresponding table in electronic_gradeable into gradeable:

UPDATE
  gradeable
SET
  g_instructions_url = eg.eg_instructions_url
FROM
  electronic_gradeable AS eg
WHERE
  gradeable.g_id = eg.g_id;

3) This command would need to be ran last. It actually doesn't need to be ran at all but it will be irrelevant after the previous 2 commands are ran. It deletes the now unnecessary column from the electronic_greadable table.

ALTER TABLE electronic_gradeable
    DROP eg_instructions_url;

### CODE REVIEW

**Comment by MasterOdin** [comment]
Please actually give the pull request a meaningful name as it's what will be used for the commit message when we squash/merge it into the master

**Comment by bmcutler** [comment]
I'm going to wait until Monday morning to install this commit on the live server.
So please let's not merge it to master branch before then.

**Comment by MasterOdin** [comment]
I'm good with this otherwise.

**Comment by bmcutler** [comment]
Works!

**Pull request merged**
