### PR TITLE
[Feature:InstructorUI] Allow instructors to view student Rainbow Grades data

### LINKED ISSUE #736: View all of students grades in one place
There should be a way to view all students' grades from a centralized place and be taken to any particular grade from this interface. 

The easiest place to put it right now is on the admin-only "View Students" area as an additional button next to the pencil that shows a popup (like the edit user one) that shows all grades.

Should be implemented in a similar fashion to the edit user box as well (opening the box sends an ajax request to the server to get the details to populate it with).

### LINKED ISSUE #4789: Allow instructors to view the summary rainbow grades report file for a specific student
Obviously need to make sure the security is 100% on this.
Only instructor users have this access.

### PR DESCRIPTION
**Pull request by BenKelly99**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the new behavior?
On the manage student page, instructors now have the ability to click a button for each student that renders their current rainbow grades profile is.

Closes #4789 
Closes #736

### CODE REVIEW

**Comment by BenKelly99** [comment]
I added a new feature that allows instructors to view the full rainbow grade view from within the "Grade Report" page.

**Comment by bmcutler** [comment]
[student_rainbow_grades.pdf](https://github.com/Submitty/Submitty/files/4604381/student_rainbow_grades.pdf)
[all_rainbowgrades.pdf](https://github.com/Submitty/Submitty/files/4604382/all_rainbowgrades.pdf)

**Comment by bmcutler** [comment]
Discussed with @emaicus and @Kevin-MM 


Let's have the breadcrumb for the instructor viewing specific student X be:
Submitty > sample > Manage Students > Delphia Aufderhar
(with "manage students" a link back to that page)
Initially (for this PR), the only way to reach this page per student is from the manage students page, but maybe in the future we'll have links from the full gradebook, or from the student photos page, or ...


But lets' add a new item to the left sidebar for instructors
"Gradebook", right after "Student Photos".  
It should only be available to instructor-level users.
(And only if rainbow grades is enabled in course settings)
And it should show the complete rainbow grades file.
So the breadcrumb for this page is:
Submitty > sample > Gradebook
So we can remove button / navigation from where I first asked it to be placed on Grade Reports.

**Comment by bmcutler** [comment]
@BenKelly99 
Also php linting is failing now...

**Comment by BenKelly99** [comment]
Added requested changes to breadcrumbs and labels on the pages as well as moving the gradebook access location to the sidebar. Ready for review.

**Pull request merged**
