### PR TITLE
[UI/UX:RainbowGrades] Redirect reports to customization

### PR DESCRIPTION
**Pull request by zacharymnp**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

The sidebar item 'Grade Report' currently directs instructors to the following page. The only item remaining on this page directs the user to the Rainbow Grades Customization page.
image

### What is the new behavior?
'Grade' Report' is renamed to 'Rainbow Customization' and directs the instructor directly to the Rainbow Grades Customization page.
image

### Other information?

Follows PR #10931 (Move grade summaries to customization)

### CODE REVIEW

**Review by fausta4303 — COMMENTED** [review]
Code looks fine, I'm trying to test the UI on my end but my virtual machine broke. Trying to fix it, will update when I test the UI as well

**Comment by IDzyre** [comment]
The only thing I have a question about is would it be too long of a sidebar name to have it be `Rainbow Grades Customization` or something similar, instead of just `Rainbow Customization`? I don't have a strong opinion one way or the other, it's just newer instructors might not know what Rainbow Customization is, and since the title when you get into the page is Rainbow Grades Customization, it might be nice to have the button match.

**Comment by zacharymnp** [comment]
During meeting, we decided on the following: we will use 'Rainbow Configuration' for the sidebar item and 'Rainbow Grades Configuration' for the page title.

**Review by fausta4303 — APPROVED** [review]
UI looks good on my end. I'll get back to you on that unrelated bug when I figure out how to replicate it.

**Review by williamjallen — APPROVED** [review]
Code looks good to me.

**Review by ziesski — APPROVED** [review]
Tested, Reviewed the code.

**Comment by bmcutler** [comment]
@zacharymnp 

We agreed on "Grades Configuration" not "Rainbow Customization"

**Comment by williamjallen** [comment]
Moving to "Work in Progress" until @zacharymnp makes the requested changes.

**Pull request merged**
