### PR TITLE
Annotation bar redo + bunch of fixes

### LINKED ISSUE #2623: PDF Annotation applies to multiple pdfs in one submission
When adding annotations to a pdf, changes also seem to be applying to another pdf in that submission.

The case that it happened on for me was when editing upload.pdf also applied changes to upload_version_2.pdf.

### LINKED ISSUE #2686: PDF annotator focus / overlap
Sort out what should happen when other panels overlap the pdf annotator window.  If cursor is inside of 2 panels, but pdf is lower, PDF annotator should not still have focus, ability to draw/add text/etc.

### PR DESCRIPTION
**Pull request by saxocellphone**
New annotation bar design, fixed overlapping problem, new selection menu, eraser works better. 
  Closes #2686, Closes #2623

### CODE REVIEW

**Comment by saxocellphone** [comment]
About the active version warning, currently the PDF doesn't show up when you are not grading the active version, I will make it work in the future.

**Comment by saxocellphone** [comment]
Turns out I forgot to add touch event handlers to the eraser. Now erasers should support touch. Please test it again to make sure.

**Comment by holzbh** [comment]
Eraser in Chrome still doesn't work with touchscreen.

**Comment by holzbh** [comment]
Oh, also Saving still appears to not be working...

**Comment by saxocellphone** [comment]
That's a bit weird, are there any errors being thrown for the eraser? Also I can't seem to reproduce the saving problem.

**Comment by holzbh** [comment]
Eraser with touchscreen I see many instances of

```VM372:952 Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.
    at findAnnotationAtPoint (eval at globalEval (jquery.min.js?v=1532711469:2), <anonymous>:952:29)
    at HTMLDocument.handleDocumentMouseMove (eval at globalEval (jquery.min.js?v=1532711469:2), <anonymous>:3794:52)```

Saving seemed to work though after a destroy & up. Yes I did previously clear my cache/history for "all time"... maybe something wasn't picked up properly on just an `INSTALL_SUBMITTY.sh clean`? Anyway, saving in Chrome functions correctly now.

**Comment by holzbh** [comment]
Still seeing the same error after pulling and then doing a destroy/up and clearing local browser cache.

**Comment by saxocellphone** [comment]
I am so sorry I made a stupid naming mistake. Now THIS should do it

**Pull request merged**
