### PR TITLE
[Bugfix:InstructorUI] Fix bulk upload not showing options

### PR DESCRIPTION
**Pull request by TusharPuri10**
fixes https://github.com/Submitty/Submitty/issues/10106

## What is the current behavior?
A bug exists in the initial view of the "BULK UPLOAD" feature on the gradeables page, preventing users from specifying QR code or page count for student PDFs. Instructors can temporarily fix it by toggling "Make submission for student" before switching back to "Bulk PDF Upload," revealing the correct options. 

image

## What is the new behavior?
This new logic checks for a previous setting in session-Storage, and if found, it sets the appropriate radio button accordingly. If there is no previous setting, it defaults to clicking the "Bulk Upload" radio button. **( The logic is,  it must be clicked if it exists at first place )** .This modification ensures that the correct view is displayed, resolving the problem identified in the initial rendering of the "BULK UPLOAD" feature.

image

### CODE REVIEW

**Comment by powe97** [comment]
Tested, looks good.

**Review by powe97 — APPROVED** [review]

**Review by ziesski — APPROVED** [review]
Didn't test the functionality, but the code seems minimal change, fixing the introduced issue.

**Review by IDzyre — CHANGES_REQUESTED** [review]
The tests need to pass before this is good to merge.

**Comment by bmcutler** [comment]
I don't understand why this code would fix the problem.  Did you test both bulk upload gradeables and regular submission gradeables?  I think this change will probably break regular submission gradeables.

**Review by bmcutler — CHANGES_REQUESTED** [review]
Code may fix the problem but breaks regular gradeables, this can be seen in the Cypress tests.

**Comment by williamjallen** [comment]
Superseded by https://github.com/Submitty/Submitty/pull/10108, as per the PR description.

**Pull request closed without merging**
