### PR TITLE
[Bugfix:Autograding] Grade Inquiries Graders make posts

### LINKED ISSUE #9053: Limited Access Graders can not Make Posts on Grade Inquiry
**Describe the bug**
When a limited access grader attempts to make an inquiry post, they are told they have "Insufficient permissions to make grade inquiry post". 

**Expected behavior**
If they can see posts they should be able to make a post

**To Reproduce**
1. Have a student ask for a grade inquiry
2. Login as "grader"
3. Click on the student and go to the "grade Inquiry" button 
4. Try to add a post 
5. See error

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by 04vmatsibekker**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #9053. Originally limited Access Graders can view posts being made about a grade inquiry, but they could not actually post themselves.

### What is the new behavior?
Before
image

Now
image

They are able to make posts for grade inquires.

### CODE REVIEW

**Comment by williamjallen** [comment]
This line appears to have gone through several iterations, including as recently as December in https://github.com/Submitty/Submitty/pull/8481.  Shail may have comments on this change.

**Comment by shailpatels** [comment]
> This line appears to have gone through several iterations, including as recently as December in #8481. Shail may have comments on this change.

@04vmatsibekker yeah the most recent change was fixing up the authentication on the different backend endpoints that give different fragments of the grade inquiry conversation since it uses websockets. 

I think the area you want to look at is under https://github.com/Submitty/Submitty/blob/main/site/app/libraries/Access.php#L156 and have that handle letting limiting access graders do whatever

Part of the confusion comes from both the student and grader are hitting the same backend point to make a post so the authentication for it becomes a bit tricky. I think the internet of the full access grader was preventing students from making posts onto other conversations by URL hacking the id for example

**Review by mahi-pas — APPROVED** [review]
Works on my end, although I don't know the ins and outs of the system

**Comment by bmcutler** [comment]
@shailpatels  Can you please review?  Thanks

**Pull request merged**
