### PR TITLE
Fixed 'TA grade not available' for no-TA grading

### PR DESCRIPTION
**Pull request by scopeInfinity**
_"TA grade not available"_ should not be present after _View Grade_ selection for electronic gradeable with no TA grading. Issue : #1460

### CODE REVIEW

**Comment by scopeInfinity** [comment]
Hi @bmcutler @saxocellphone 

I have two ways in mind of solving _"View Grade" button should never be green_ Issue #1460 and I would like some help on deciding how to proceed.

# Method 1
Here I'm checking for the condition `$g_data->useTAGrading()` which should solve the issue. For this I'll add the following to  [NavigationView.php:304](https://github.com/Submitty/Submitty/blob/master/site/app/views/NavigationView.php#L304)

```php
else if($title_save == "GRADED" && !$g_data->useTAGrading()) { 
        $button_text = "{$title_to_prefix[$title]} {$submission_status["SUBMITTED"]} {$submission_status["AUTOGRADE"]} {$display_date}";
        $title_to_button_type_submission['GRADED'] = "btn-default";
 } // electronic gradeable with no ta grading                    
```


# Method 2

Alternatively, I could assign `GRADED` to `btn-default` at initialization to make 'View Grade' button non green for which I'll be editing [NavigationView.php:109](https://github.com/Submitty/Submitty/blob/master/site/app/views/NavigationView.php#L109):

```php
 $title_to_button_type_submission = array(
            "FUTURE" => "btn-default",
            "BETA" => "btn-default",
            "OPEN" => "btn-primary" ,
            "CLOSED" => "btn-danger",
            "ITEMS BEING GRADED" => "btn-default",
            "GRADED" => 'btn-default'    //Modified from "GRADED" => 'btn-success'
        );
```
In method 2 there won't be any need of `$title_to_button_type_submission['GRADED'] = "btn-default";` in upcoming lines.

**Comment by bmcutler** [comment]
These are the Selenium tests we need:

When the grades released date has passed for an electronic gradeable (the gradeable is in the grades available category):

If the student did not submit to the assignment, the button should be red & say "overdue submission" and list the due date.

If the gradeable does not have TA grading (it is autograde only) the button is white and says "VIEW GRADE".

If the gradeable includes TA grading, but the TA grade is not available (the TA missed the grading deadline the ta grade is missing or incomplete), the button is white and says "VIEW GRADE".

If the gradeable includes TA grading, and the TA grade is available, and the student has not yet viewed the grade (or the TA has edited/regraded the assignment since the student viewed the grade), the button is green and says "VIEW GRADE".

If the gradeable includes TA grading, and the TA grade is available, and the student has viewed the most recent TA edits to the grade, the button is white and says "VIEW GRADE".

The green check / red X on the instructor/TA "grading details" page should match the student color.  When the student button is green, there should be a red X.  When the student button is white, there should be a green checkmark.  The "viewed grade" status should reset to red X (unviewed) if the TA/instructor edits a students grade.   

BUG: reset on regrade does not appear to be implemented

----

BUG:  For the "Joe Student" user on a fresh install, I see a green button for "Autograder Hidden & Extra Credit" and "Autograde and TA Homework".  But when I click, I see "TA grade not available".  When I view from the instructor, I see that there is a grade for Joe student for both gradeables.  If I edit the grade for that student for these gradeables, then refresh the student page, the ta grade displays.  Why is it not displaying initially?  Is it a bug related to hwreports that we have deleted?  It should be loading the info from the database, not from a file (the hwreport file in /var/local/submitty/courses/s18/sample/reports/XXX/student.XXX will go away soon).

**Comment by bmcutler** [comment]
BUG: For TA Grade Only Homework, even though "joe student" has not viewed the TA grade, the button is still white.  Also it says "TA grade not available" on a fresh install.

**Comment by saxocellphone** [comment]
I'll start working on the selenium tests.
For the PR, I think Barb's comment basically listed out all of them

**Comment by scopeInfinity** [comment]
Implemented for resetting userViewedDate on regrading + Bug Fixes

**Pull request merged**
