### PR TITLE
[Bugfix:TAGrading] Hide Non-Peer Components

### LINKED ISSUE #10107: Peer Grading status buttons inconsistent
**Describe the bug**
I'm a peer grader, I've been assigned to grade 2 students.
The assignment has 5 TA graded components and 1 peer graded component
Both students have submitted.
One of the students has been graded by the TA, the other has not.

This is my view:

Screenshot 2024-01-15 at 7 06 31 PM

I have done my peer grading, but why am I seeing the white status buttons for the TA graded components for the student who hasn't been graded yet?  
BTW, when I go into the UI for the TA and complete the grading, then the white buttons disappear

BTW: If I grade 4 of the 5 TA grading components then only 1 of the white TA status buttons is visible.
Screenshot 2024-01-15 at 7 09 53 PM

### PR DESCRIPTION
**Pull request by Xiayucheng1212**
fixes #10107 
### Please check if the PR fulfills these requirements:
* [✅] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

The following image shows that a closed team assignments have 5 components, which contains 4 peer components and 1 non-peer component.
截圖 2024-01-19 下午3 00 06

The 4 peer components is visible by the student grader, but the last one "Problem 5" cannot be seen. 
截圖 2024-01-19 下午2 59 16

However, all components are visible for an instructor.
截圖 2024-01-19 下午3 00 38

### What is the new behavior?
1. Hide non-peer components for the peer grader

### CODE REVIEW

**Review by wuj18 — CHANGES_REQUESTED** [review]
a01e19b64edd9f080a9889c8f379066

TA grading component is visible by peer graders after the component is graded

**Comment by Xiayucheng1212** [comment]
### Before changes
截圖 2024-01-29 下午8 39 25

### After changes
截圖 2024-01-29 下午8 38 38

**Review by Xiayucheng1212 — COMMENTED** [review]
@wuj18  I fixed the problem you mentioned, thank you so much! Could you help to review this again? Thanks

**Review by wuj18 — APPROVED** [review]

**Review by iamdanielyun — APPROVED** [review]

**Comment by Xiayucheng1212** [comment]
@wuj18 Would you help me to merge this branch?

**Review by williamjallen — APPROVED** [review]

**Pull request merged**
