### PR TITLE
[Bugfix:InstructorUI] student photo attachment upload fixed

### PR DESCRIPTION
**Pull request by JWei17**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Uploading attachment under student photo is buggy. The document page will pop up twice. 
This issue is similar to PR [#10243](https://github.com/Submitty/Submitty/pull/10243) but is happening in student photo.
### What is the new behavior?
Upload attachment bug get fixed.

Procedure: 
Go to student photo
click upload student photo
upload attachment.

### CODE REVIEW

**Review by Kush-Raval — APPROVED** [review]
The desired change is shown after this change --> The glitch where you double-click on the file you want to upload is gone.

The code change makes sense because the eventListener is probably incorrectly handling user input.

**Comment by DarthNyan** [comment]
Can you edit the PR title to be specific that this a change to student photo upload?

**Review by ryvaru — APPROVED** [review]
Works as intended, the document page will no longer pop up twice when uploading in all instances in the Instructor view. The code is also very understandable and logical. Approved.

**Review by JoJo-ESC — APPROVED** [review]
Change fixes issue. Nothing is broken. It all looks good!

**Pull request merged**
