### PR TITLE
[Bugfix:HelpQueue] Fix Contact Information in current queue

### LINKED ISSUE #7000: Student Contact Information is not shown to the instructor in the Office Hours Queue
**Describe the bug**
When student joins the office hours queue and specifies their contact information, this contact information is not shown in the TA/instructor view of the queue.

**Expected behavior**
Student's contact information, if provided, should be shown in the TA/instructor view of the queue.

**To Reproduce**
1. On the student's side, navigate to the Office Hours Queue page. In my specific example, this is course CSCI-2500. The corresponding URL is https://submitty.cs.rpi.edu/courses/f21/csci2500/office_hours_queue 
2. Select an open queue from the dropdown list, enter the access code and specify contact information. See screenshot 1.
3. Click "Join" and observe that the student was successfully added to the queue. See screenshot 2.
4. On the instructor side, navigate to the Office Hours Queue page. URL is the same as in step 1. Refresh the Web page and observe that the student's name is shown in the queue but no contact information is visible. See screenshot 3.

**Configuration**
 - OS: Windows 10 Enterprise x64 20H2, 10.0.19042, Build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
 - Browser: Mozilla Firefox 91.0.2 (64-bit)

**Screenshots**
image
image (1)
image (2)

**Additional context**
It was discovered by @bmcutler and confirmed by me that using `.*` as the regex pattern for a particular office hours queue mitigates the problem.

### PR DESCRIPTION
**Pull request by loadedskiffer**
### What is the current behavior?
closes #7000

### What is the new behavior?
If contact information is enabled for the course, the table always shows the student's contact information
pr14_1
if contact information isn't enabled the column doesn't appear
pr14_2

### Other information?
To test:
join different queues as different students and see the table

### CODE REVIEW

**Comment by MasterOdin** [comment]
To confirm, the actual fix for the linked issue is just the change in `site/app/controllers/OfficeHoursQueueController.php`, while the change in `site/app/templates/officeHoursQueue/CurrentQueue.twig` is purely cosmetic?

**Comment by loadedskiffer** [comment]
> To confirm, the actual fix for the linked issue is just the change in `site/app/controllers/OfficeHoursQueueController.php`, while the change in `site/app/templates/officeHoursQueue/CurrentQueue.twig` is purely cosmetic?

correct

**Comment by MasterOdin** [comment]
Why the change of the contact info location? Just want to confirm where this might have been discussed (weekly meeting?) since the change is unrelated to the linked bug.

**Comment by bmcutler** [comment]
I'm not in favor of changing the position of the contact info.  Let's please leave it where it was.

Note, in some courses we will have a mix of queues, some requiring contact info (remote/webex office hours) and some not requiring contact info (in person office hours).

**Comment by loadedskiffer** [comment]
> I'm not in favor of changing the position of the contact info. Let's please leave it where it was.
> 
> Note, in some courses we will have a mix of queues, some requiring contact info (remote/webex office hours) and some not requiring contact info (in person office hours).

so you don't want a column for contact information ?

**Review by MasterOdin — APPROVED** [review]

**Pull request merged**
