### PR TITLE
[Bugfix:InstructorUI] Using cookie for show grader/date option

### PR DESCRIPTION
**Pull request by ZheyuDeng**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)

### What is the current behavior?

image
When refreshing, show graders/date option becomes uncheck when it is orginally checked before refreshing.

### What is the new behavior?
Both checkbox(Show graders/dates) can be remembered now when refreshing using cookies.
image

### Other information?

Tested only one checkbox being checked and both to see if the cookie remembers correctly.

### CODE REVIEW

**Comment by williamjallen** [comment]
Please expand your PR description a bit.  At a minimum, it should contain a brief description of the current problem/feature request.  As it currently stands, I am unable to tell what the purpose of your PR is by looking at the title and description alone.

Please also capitalize the first letter of your PR title.

**Comment by williamjallen** [comment]
Please make sure future commit messages describe why the change was made.  A commit message like "Update foo.txt" doesn't tell reviewers anything they can't already get by looking at the diff.  Please refer to my presentation from a couple weeks ago for examples of good and bad commit messages.

**Comment by yanliw123** [comment]
works as expected, the button remembers the show grader/date option after refreshing the page. The code looks clean. Approved!

**Review by yanliw123 — APPROVED** [review]
works as expected, the button remembers the show grader/date option after refreshing the page. The code looks clean. Approved!

**Review by Nicc041 — APPROVED** [review]
I'm not sure how to read the edited code, but I tested it and everything works!

**Pull request merged**
