### PR TITLE
[Bugfix:TAGrading] Show Peer Grading Status on TA interface

### LINKED ISSUE #10166: TA Interface Does Not Reflect Student Peer Grading Status
**Describe the bug**
In the current system, instructors can visually identify if a student has completed their assigned peer grading tasks, as these components are highlighted in purple. However, this functionality appears to be missing on the TA interface, where the status indicators for peer grading completion do not change regardless of a student's grading activity.

**Expected behavior**
The TA interface should reflect the peer grading status accurately, similar to the instructor's interface. Once a student has graded a peer component, the corresponding components should be highlighted to indicate completion. 

**To Reproduce**
1. Log in to a student account and grade a peer homework assignment.
2. Log in to the instructor account to observe that the graded components are highlighted in purple.
3. Log in to the TA interface and notice that all peer grading components remain unhighlighted.

**Configuration**
Windows Chrome

**Screenshots**

instructor's interface:
f9d6b35a905fa68d74c8791b06e2ad3

ta's interface:
6704dd640adcd18b5367725c10200fc

**Additional context**

### PR DESCRIPTION
**Pull request by wuj18**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Fixes #10166 Currently, the peer grading completion status is only visible to the instructor. The status indicator does not change on the TA interface, regardless of whether a student has finished grading the component or not.

### What is the new behavior?
The status indicator is highlighted in purple on the TA interface if the student has graded their assigned peer component.

### Other information?
before change:
d7b9f91408db1bf31d72d400db0a2c8

after change:
637709d334dcd03541c006c4a2a1d48

### CODE REVIEW

**Review by DarthNyan — APPROVED** [review]
I'm not that knowledgeable about peer grading, but I tested it and it seemed to work. The code change also makes perfect sense.

**Review by ArnavPawar — APPROVED** [review]
Tested the changes and the code makes sense and seems quite simple. Should not cause any issues looks good to merge.

**Review by arougey — COMMENTED** [review]
Code seems to work, however is it the intended use for any grader, whether limited/full access/instructor to be able to access it and not just the grader with the right id? Otherwise it looks good.

**Comment by wuj18** [comment]
> Code seems to work, however is it the intended use for any grader, whether limited/full access/instructor to be able to access it and not just the grader with the right id? Otherwise it looks good.

Yes, limited/full access/instructor should be able to view the progress of peer graders.

**Review by ryvaru — APPROVED** [review]
Tested this code and everything works as intended. The purple colors work well for peer grading and the code is logical. Approved, seems ready to merge.

**Review by Kush-Raval — APPROVED** [review]
The code change makes sense, gives the TA access to see Peer Grading Status based on:
$grader->accessGrading().
Also, I tested for functionality and correctly saw the new change.

**Pull request merged**
