### PR TITLE
[Refactor:Calendar] Improve Database Handling of Unspecified Date Styles

### PR DESCRIPTION
**Pull request by sachinrastogi12**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to GitHub PR if visual/UI changes were made

### CODE REVIEW

**Comment by williamjallen** [comment]
@sachinrastogi12 Thanks for this contribution!  Please fill in your PR description, and change the PR title so it meets out PR title [guidelines](https://submitty.org/developer/getting_started/make_a_pull_request).

**Comment by sachinrastogi12** [comment]
"Hi there, I have updated the PR name accordingly. Please take a look once and let me know."

**Comment by williamjallen** [comment]
You still need to fill out the PR body with a description of your changes.

**Review by ziesski — CHANGES_REQUESTED** [review]
Please reduce the length of PR title as well as including description of the changes in body.

**Comment by bmcutler** [comment]
Thanks for your suggestion & contribution
However we cannot merge this PR without more information in the PR description
It should include sample screenshots or data examples
I am unclear what impact this change will make on the system as a whole
and whether other changes will be required.

I am therefore closing this PR, please reopen or make a new PR if you can provide the requested information.

**Pull request closed without merging**
