### PR TITLE
[Feature:System] Add Term to Rejoin Email

### PR DESCRIPTION
**Pull request by NiaHeermance**
### What is the current behavior?
When a student self readds themselves, the email does not say what term the course they rejoin is a part of.

### What is the new behavior?
The term is now specified.

# Images
Email subject:
image

### CODE REVIEW

**Review by liny18 — APPROVED** [review]
Looks good to me. The desired outcome is achieved and the change doesn't seem to have side effects.

**Comment by NiaHeermance** [comment]
Add real comment, remove capitalization.

**Comment by RitaLei123** [comment]
How do you recreate this? I tried kicking a student out but it says that they have recorded data so I can't kick them out. Can I get some steps that will lead me to the changes please?

**Review by RitaLei123 — COMMENTED** [review]
1. Is the proposed change a good idea?
Yes, instructors can now easily see what term the student rejoined.

2. Did the author take the right approach?
Yes, the author went to the relevant file and added the term variable for the rejoin.

3. Are all the implementation details correct?
Yes, the implementation details are correct but not specific enough.

Additional Notes:
How to recreate the changes: (Steps provided by Nia)
1. In a student account, complete some form of activity (click a course material, view a gradable, view a forum post, etc…)
2. Using the instructor account, remove the student on the student list and make sure that the student is set to non-manually registered. Manually registered students will not be allowed to rejoin a course.
3. Return to the student account, and try to access the course. This can be done by going to another course and changing the URL to the course that the student was removed from (Example: http://localhost:1511/courses/f23/tutorial → http://localhost:1511/courses/f23/sample)
4. Now you should be on the No Access page and there should be a blue Rejoin Course button. Click on the button, and you should be on the course’s main page.
5. Go to the instructor account and go to the course’s email status page. A new email should appear there and the new feature is visible.

**Pull request merged**
