### PR TITLE
[Feature:Calendar] Button to Set Calendar Date to Today

### PR DESCRIPTION
**Pull request by arougey**
Screenshot from 2024-04-06 13-09-31

The current behavior is that, to change the date to the current day, the user must press the arrow keys repeatedly.

The new behavior is that, there is now a blue button on the upper left-hand side of the calendar page that
sets the calendar date to the current day/month/year and also updates all cookies.

This should not be a breaking change and was tested on both student and instructor accounts. 

However, this pr could interfere with my other calendar pr #10249 which creates month/year dropdowns which may or may not update when the button is pressed.

### CODE REVIEW

**Comment by arougey** [comment]
Forgot to mention that is closes #10265

**Comment by sadam-04** [comment]
Looks good, i tested on student and instructor logins

**Review by sadam-04 — APPROVED** [review]
Looks good, i tested on student and instructor logins.

**Review by AavanVadiwala — COMMENTED** [review]
Works. Went couple months ahead, and successfully leads user back to current date. Went couple months back, and successfully leads user back to current date. Checked on Student, Instructor, and ta. The comments that Github Action seems to make on the code in the file site/public/js/calendar.js seem small and don't affect the action, but need to be addressed to be merged.

**Review by ryvaru — APPROVED** [review]
Code looks good. Tested it on every login and it successfully brought me back to the current month going backwards or forwards a couple of days or years. I suggest having a bit of empty space between "Today" and "New Item" (Instructor) or "Today" and "Options" (Student, TA) for it to look better visually, but the current one tackles the issue well.

**Review by ArnavPawar — CHANGES_REQUESTED** [review]
Looks good. As far as the UI though I think it should be aligned with the other blue buttons.

**Review by Kush-Raval — APPROVED** [review]
The button does what is intended.
Code change makes sense, code is ready to merge after JS lint is fixed.

**Comment by arougey** [comment]
Button has been moved to the right

**Comment by williamjallen** [comment]
> Button has been moved to the right

Can you update the screenshot in the PR description to reflect this?

**Review by williamjallen — APPROVED** [review]
Code seems reasonable.

**Pull request merged**
