### PR TITLE
[Bugfix:InstructorUI] Disable Inputs in Instructor Grading

### PR DESCRIPTION
**Pull request by sahilsuman933**
### Please check if the PR fulfills these requirements:

* [] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently, in the Instructor Grading View, input controls such as checkboxes, radio buttons, and other selectable elements are active, allowing unintended changes to be made.

### What is the new behavior?
In the updated Instructor Grading View:
- Checkboxes are disabled.
- Radio buttons are disabled.
- Other relevant input controls are disabled.

This prevents unintended changes and ensures data integrity while providing a more streamlined grading experience for instructors.

https://github.com/Submitty/Submitty/assets/34382211/2b44976b-866f-4f80-8463-85dc5bad6102

### Other information?

This is not a breaking change as it only affects the input controls within the Instructor Grading View and ensures they are non-interactive.

Changes were tested by:
- Verifying that all checkboxes, radio buttons, and other inputs are disabled in the Instructor Grading View.
- Ensuring there is no impact on other views or functionalities.

### CODE REVIEW

**Comment by williamjallen** [comment]
@sahilsuman933 It looks like you have some extra changes to the composer lock file.  Reverting the changes should resolve the current install issue in the CI.

**Comment by sahilsuman933** [comment]
@williamjallen Yeah, by mistake, I pushed some extra changes when I opened this PR for review. I will fix all those errors.﻿

**Comment by sahilsuman933** [comment]
@williamjallen I will remove those extra changes once I will open it for review.

**Comment by sahilsuman933** [comment]
I will create another fresh pull request with all the changes and requested modifications, as well as attach it to the pull request issue﻿

**Pull request closed without merging**
