### PR TITLE
[Feature:InstructorUI] Add "display" on customization page

### PR DESCRIPTION
**Pull request by ziesski**
### What is the current behavior?
Instructor cannot select display options on web-base-customization page. (There is no box for it)

### What is the new behavior?

With new behavior - instructor can check display options from web-based customization page, it will successfully save the file in the customization.json file. 
Screen Shot 2023-08-04 at 11 50 45 AM

Screen Shot 2023-08-04 at 11 56 46 AM

### CODE REVIEW

**Comment by bmcutler** [comment]
As discussed... please add a second array with strings of on page documentation for each option.  And please set the order for the options as follows: 

"grade_summary" - "Display a column(row) for each gradeable bucket on the syllabus"
"grade_details" - "Display a column(row) for each gradeable within each gradeable bucket on the syllabus"
"display_benchmark" - "Display a row(column) for each benchmark/comparison selected below."
"benchmark_percent" - "not used" (didn't double check this)

"exam_seating" - "Used for assigned seating for exams, see also: https://submitty.org/instructor/course_settings/rainbow_grades/exam_seating"
"section" - "Display the students registration section"
"messages" - Display the optional text message at the top of the page"
"warning" - "not used" (didn't double check this)

"final_grade" - "Display the student's final term letter grade."
"manual_grade" - "not used" (didn't double check this)
"final_cutoff" - "Display the histogram of average overall grade and count of students with each final term letter grade."

"instructor_notes" - "Optional message for specific students that are only visible on the instructor gradebook, these messages are never displayed to students."

remove "iclicker"

... the above list is imperfect, we can revise it in future PRs

**Comment by bmcutler** [comment]
line wrap looks kinda bad on narrow window:

Screenshot 2023-08-17 at 2 15 45 PM

**Review by bmcutler — APPROVED** [review]
please tweak the formatting, and then I'll merge it.

**Comment by ziesski** [comment]
Ok, I did notice it but thought it was fine, since you pointed out, I will come up with better solution

**Pull request merged**
