### PR TITLE
Replaces usages of glob.glob with pathlib.glob

### LINKED ISSUE #3277: Replace usages of glob.glob with Pathlib.glob
Somewhat similar to #2392, we should remove all uses of glob.glob for Pathlib.glob due it to having better compatibility with 3.4 (which we should theoretically support). The following files use glob.glob:
- [ ] grade_item.py
- [ ] reset_system.py
- [ ] setup_sample_courses.py
- [ ] integrationTests (throughout)

Any of these that use `recursive=True` flag or the `**` notation should be a priority to replace.

### PR DESCRIPTION
**Pull request by drumilpatel2000**
fix #3277 
Minor mistake in branch name  
Found uses of `glob.glob` in these files
Sample changes : 
1. Replaced `glob` with `pathlib`
2.
```
glob.iglob() => Path(*).glob()
```

<details><summary>Files Changed</summary>
<p>

```
.setup/bin/
              reset_system.py
              setup_sample_courses.py
sbin/autograder/grade_item.py

tests/integrationTests/tests/
        c_failure_messages/__init__.py
        choice_of_language/__init__.py
        cpp_buggy_custom/__init__.py
        cpp_cats/__init__.py
        cpp_custom/__init__.py
        cpp_hidden_tests/__init__.py
        cpp_provided_code/__init__.py
        cpp_simple_lab/__init__.py
        input_output_subdirectories/__init__.py
        minimal_code_editing/__init__.py
        pdf_word_count/__init__.py
        python_linehighlight/__init__.py
        python_multipart_static_analysis/__init__.py
        python_simple_homework/__init__.py
        tutorial_01_simple_python/__init__.py
        tutorial_02_simple_cpp/__init__.py
        tutorial_03_multipart/__init__.py
        tutorial_04_python_static_analysis/__init__.py
        tutorial_05_cpp_static_analysis/__init__.py
        tutorial_06_loop_types/__init__.py
        tutorial_07_loop_depth/__init__.py
        tutorial_08_memory_debugging/__init__.py
        tutorial_09_java_testing/__init__.py
        tutorial_11_resources/__init__.py
        tutorial_12_system_calls/__init__.py
        tutorial_16_docker_network_python/__init__.py
```
</p>
</details>

### CODE REVIEW

**Comment by drumilpatel2000** [comment]
@MasterOdin Please review  this one

**Comment by MasterOdin** [comment]
Thank you for your patch, but unfortunately there's some problems with it.

`glob.glob` and `glob.iglob` are not identical in what they return to `Path.glob` (see my description of what all of these return and how I manged it in #3276), which is causing our entire autograding integration suite to fail.

**Comment by drumilpatel2000** [comment]
Thank you for reviewing @MasterOdin I will try to solve this issue by tomorrow

**Comment by bmcutler** [comment]
Closing for now.  Can be re-opened if problems are addressed.

**Pull request closed without merging**
