### PR TITLE
[Feature:API] Add testcases to student api

### PR DESCRIPTION
**Pull request by IDzyre**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Currently, the student api only returns the total grade points, and doesn't include which of the tests the points came from. 

### What is the new behavior?
This adds the testcases the user can view to the return values, giving more information on what failed, and why. 
API tests will be converted to Jest in a future PR.

### CODE REVIEW

**Comment by justin-sadakhom** [comment]
How did you test the API?

**Review by justin-sadakhom — COMMENTED** [review]
Please also fix the PHP linting.

**Comment by IDzyre** [comment]
Since this addition to the API is regarding the graded component of gradeables, I don't think it is currently able to be tested VIA the CI, unless we do some hacky thing like create a gradeable, submit to it, wait for it to be graded, then request it VIA the API, however I can create a test that runs only locally for now. I use Postman to call the API locally.

**Comment by justin-sadakhom** [comment]
> Since this addition to the API is regarding the graded component of gradeables, I don't think it is currently able to be tested VIA the CI, unless we do some hacky thing like create a gradeable, submit to it, wait for it to be graded, then request it VIA the API, however I can create a test that runs only locally for now. I use Postman to call the API locally.

If it's possible to add a test case that can be run locally but is ignored by GitHub Actions please do that. Thank you!

**Pull request merged**
