### PR TITLE
[Feature:Autograding] Add command `submitty_count_ts`

### PR DESCRIPTION
**Pull request by poorna2152**
### Other information?

This command doesnt work as of yet (gives a ABORT signal). 
I tried commenting out the function call [enable_all_setrlimit()](https://github.com/Submitty/Submitty/blob/main/grading/execute.cpp#L919) and setting limits to `RLIM_INFINITY` in the config.json file. But didnt manage to solve the issue.
The changes are made in execute.cpp. Other files are relevant to PR[#7957](https://github.com/Submitty/Submitty/pull/7957).

### CODE REVIEW

**Comment by poorna2152** [comment]
I was expecting this to be an issue with the memory limit. 
However I observed the following behavior.
- When I do not set any rlimits in config.json following are the default ulimit values.
```
data seg size           (kbytes, -d) 488281
stack size              (kbytes, -s) 488281
```
This cause the program to immediately suspend giving an error.

- When I set the,
`RLIMIT_DATA":  "RLIM_INFINITY"` in the config.json. 
It sets
```
data seg size           (kbytes, -d) unlimited
stack size              (kbytes, -s) 488281  
```
Program executes without stopping and doesnt generate an output.

- When following resource limit is set in config.json,
`"RLIMIT_STACK":      "RLIM_INFINITY"`
It sets
```
data seg size           (kbytes, -d) 488281
stack size              (kbytes, -s) 8192
```
As similar to above case program executes without stopping.

However when I replicating those ulimits and running the program locally only the first instance generates an error other two instances work

**Comment by bmcutler** [comment]
@poorna2152 

I'm guessing node is trying to create a new thread (or similar action) and the system call filtering is blocking that thread and node is apparently waiting for the thread.

I commented out the system call filtering temporarily, and now it works.
We'll need to figure out what system calls node needs and put those on the allow list for running node.

**Comment by MasterOdin** [comment]
Running `/usr/bin/node dist/index.js -l python count token while test/data/python/loops.py`, I got this list of unique syscalls:
```
{
  'execve',
  'brk',
  'arch_prctl',
  'access',
  'openat',
  'fstat',
  'mmap',
  'close',
  'read',
  'mprotect',
  'pread64',
  'munmap',
  'set_tid_address',
  'set_robust_list',
  'rt_sigaction',
  'rt_sigprocmask',
  'prlimit64',
  'futex',
  'getuid',
  'geteuid',
  'getgid',
  'getegid',
  'fcntl',
  'ioctl',
  'clock_getres',
  'epoll_create1',
  'pipe2',
  'write',
  'eventfd2',
  'clone',
  'getpid',
  'getrandom',
  'madvise',
  'readlink',
  'getcwd',
  'statx',
  'epoll_ctl',
  'epoll_wait',
  'exit_group'
}
```

For reference, the system calls to execute a simple node program that just prints to console is:
```
{
  'execve',
  'brk',
  'arch_prctl',
  'access',
  'openat',
  'fstat',
  'mmap',
  'close',
  'read',
  'mprotect',
  'pread64',
  'munmap',
  'set_tid_address',
  'set_robust_list',
  'rt_sigaction',
  'rt_sigprocmask',
  'prlimit64',
  'futex',
  'getuid',
  'geteuid',
  'getgid',
  'getegid',
  'fcntl',
  'ioctl',
  'clock_getres',
  'epoll_create1',
  'pipe2',
  'write',
  'eventfd2',
  'clone',
  'getpid',
  'getrandom',
  'madvise',
  'readlink',
  'getcwd',
  'statx',
  'stat',
  'dup3',
  'epoll_ctl',
  'epoll_wait',
  'exit_group'
}
```

**Comment by poorna2152** [comment]
@MasterOdin 
It was not possible to run even a simple Node program in Submitty. Barb suggested to use the `system_call_check.cpp` utility to test which system calls needs to be whitelisted. Even the after whitelisting the system calls suggested by that program this didnt get resolved. 
We decided to test implementing using tree-sitter-c api. I did an [initial implementation](https://github.com/Submitty/AnalysisToolsTS/pull/2) and it seems to work fine when run on Submitty.

**Pull request closed without merging**
