### PR TITLE
[UI/UX:TAGrading] Remove incorrect message

### LINKED ISSUE #10130: Not Assigned Message When Peer Grading
**Describe the bug**
The message ``Notice: You are not assigned to grade any students for this gradeable.`` appears for undergraduate peer graders even when you are assigned to peer grade someone else.

**Expected behavior**
The message should not appear.

**To Reproduce**
1. As the instructor, create a gradeable with peer grading components.
2. Login as at least three students and submit to this gradeable.
3. As the instructor, in the gradeable's configuration, generate peer grading assignments in the peer grading tab.
4. As one of the students who submitted, navigate to the grade page and see the message.

**Configuration**
 - OS: Windows
 - Browser: Firefox, Edge

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Xiayucheng1212**
Fixes #10130 

### What is the current behavior?

1. It shows incorrect message: "Notice: You are not assigned to grade any students for this gradeable" when the user is a peer grader. 
截圖 2024-02-03 下午12 47 40

### What is the new behavior?
1. Remove incorrect message for peer grader.
截圖 2024-02-03 下午12 46 54

I use the `graded_gradeables` to replace with the `grader_registration_sections` when the user is a peer grader, since a student might not have access to grade all other students. Therefore, the `grader_registration_sections` is null for these normal students. However, they still have students assigned to them for some specific gradeable. 

To make less change on the current design, I choose to reuse the `graded_gradeables` instead of adding extra infos in `grader_registration_sections` for a peer student.

### CODE REVIEW

**Comment by Xiayucheng1212** [comment]
@hansongu123  Yes, but it was abandoned accidentally, so i reproduce it.

**Comment by hansongu123** [comment]
> @hansongu123 Yes, but it was abandoned accidentally, so i reproduce it.

I see. In the future, please do not close a PR that's already been approved or requested changes unless there is a reason that you must do so in order to avoid confusion. Do not be afraid if the PR is listed as "abandoned" since it is only an indication of inactivity, and it can be removed. Our admin would eventually go through all the approved PRs and decide whether to merge them.

**Comment by Xiayucheng1212** [comment]
> > @hansongu123 Yes, but it was abandoned accidentally, so i reproduce it.
> 
> I see. In the future, please do not close a PR that's already been approved or requested changes unless there is a reason that you must do so in order to avoid confusion. Do not be afraid if the PR is listed as "abandoned" since it is only an indication of inactivity, and it can be removed. Our admin would eventually go through all the approved PRs and decide whether to merge them.

Got it! Sorry I didn't know that before, will be noticed. May I know how to remove the abandoned label, or it can only be handled by the admin?

**Comment by bmcutler** [comment]
We do not intentionally limit who can edit labels on issues and PRs -- but Github may restrict it to users that are in the Submitty organization.

**Review by NiaHeermance — APPROVED** [review]
Code is quick change. Maybe excessive commenting (one comment would have sufficed), but I like the detail. Tested and works!

**Pull request merged**
