### PR TITLE
[Feature:Forum] Full page forum

### LINKED ISSUE #4795: Bigger, easier to use "browse threads" display
Initially I think we designed the forum landing page to show just the threads.  (full width)

But then we decided to stick with one layout for the forum where the threads were the left 1/3 of the screen and the posts in a selected thread were the right 2/3.

This compromise is not great.

Suggestion:
Let's have 2 layouts, the "only thread", and the current "threads + posts".
We start/land in the only thread layout, it's easier for students and instructors to browse the threads (we see more of the text of the title & post body.  Maybe we can also display # of posts and # of unread posts and  # of participants??

ADDED:
also, some indication if teaching staff (graders or instructor) have participated in the conversation
maybe an indication that something has been merged with this thread??
does it contain an image attachment?
has the title or top post of this thread been edited

### PR DESCRIPTION
**Pull request by jenaybarela**
### Please check if the PR fulfills these requirements:

* [X] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Currently the forum opens with the threads on one third of the screen. With the selected thread open on the other two thirds of the screen.
Fixes #4795 
### What is the new behavior?
Forum starts out full paged. When a thread is clicked it goes back to the original layout

### CODE REVIEW

**Comment by jenaybarela** [comment]
image

**Comment by jenaybarela** [comment]
Im working on getting the selected thread to load first rather than the first thread in the list.

**Comment by mukul-kmr-jha** [comment]
> We could possibly use cookies to only show this display after a certain time. Alternatively could also modify request parameters made to this url so that this page is shown in certain conditions (ie clicking the discussion forum icon on the sidebar).

So for the page refresh condition, I think it should maintain the prev-state like if you are on the complete threadlist view it should keep showing that and same goes for the particular thread post list view...As a solution for this, modifying the routes and view seems a good idea to me.

**Comment by bmcutler** [comment]
@mukul-kmr-jha 
Can I assign you to please take over and complete the work for this draft PR?
We can talk next week.
Thanks!

**Comment by mukul-kmr-jha** [comment]
Sure, I would like to work on this one, thanks!

**Comment by bmcutler** [comment]
Closing this PR.
Will be addressed in PR #5726

**Pull request closed without merging**
