### PR TITLE
Improve autograder test suite

### PR DESCRIPTION
**Pull request by MasterOdin**
This (a) simplifies the path for the test suite (moving run.py and lib.py up a directory which means we don't have to do any path manipulation in run.py to run the suite) and (b) improves the output of the test suite so that it's easier to see the status of the suite at a glance.

screenshot 2016-06-20 22 47 37

(if the test fails, it'll show a red "FAILED" instead and then print out the error message)

### CODE REVIEW

**Comment by bmcutler** [comment]
Let's get issue #372 finished in this branch too.

even though it's now checked off as completed, this command:
/usr/local/hss/INSTALL_SUBMITTY.sh clean test linehighlight_test cpp_cats 
only runs the first test (linehighlight_test)

also, we'd like to have this output also written to a log.  when that's done, add it to the wiki documentation.

Also @MasterOdin, can you add some overview documentation to the travis page (editing the title too to remove php... )

**Comment by bmcutler** [comment]
Ignore my comment about running 2 tests.  I was on the wrong branch.  That does work :)

**Comment by MasterOdin** [comment]
Where would the log live and what would its usefulness be? It's not like the tests are being run hiding output (unless the user explicitly chooses to do so, but we can ignore that) so that the end user will see the appropriate details about a test failure (and would be what's logged anyway). 

And would we want to implement this in the python runner itself or just use something like (tee)[http://linux.101hacks.com/unix/tee-command-examples/] in the INSTALL script?

**Comment by bmcutler** [comment]
When the test suite output is buried in the output of other steps installation, it would be nice to have it in a known place (and easily searchable) and not have to scroll back to find it.  It would be good to have the logging done within the test suite, and not at it to the installation script (I feel iffy about it running the test suite in the first place).
The log might contain more info than what's printed to the screen (up to the test suite module creator).  The log could be cumulative.  Each time the test suite is run it puts the timestamp at the top.  Then as you're developing and running one or all tests you have a history of what was failing or working.
Put it in /usr/local/hss/test_suite/log (or similar)

**Comment by MasterOdin** [comment]
Added logging to the test suite so I believe the feature is done and that the issue can be closed.

**Comment by bmcutler** [comment]
@MasterOdin Can you fix this Travis failure?

**Pull request merged**
