### PR TITLE
[Feature:Submission] Display Jupyter notebooks in browser

### PR DESCRIPTION
**Pull request by williamjallen**
### What is the current behavior?
TAs are currently required to download `.ipynb` files for grading.  This is inconvenient and slow, especially since many TAs only want to view the file.

### What is the new behavior?
This PR introduces the ability to view Jupyter notebooks anywhere files can be viewed.  Currently, code, markdown, and text output cells are rendered.  A future PR will add support for viewing image output.

Notebooks can be viewed in the TA grading interface:
Untitled

The same file can be viewed by students in a popout on the submission page:
image

### CODE REVIEW

**Review by sahilsuman933 — CHANGES_REQUESTED** [review]
https://github.com/Submitty/Submitty/assets/34382211/05adb263-c091-4c8a-99ea-6fe5a5d99322

**Comment by sahilsuman933** [comment]
@williamjallen It is still failing the `php-lint CI`, can you please fix it?

**Review by powe97 — CHANGES_REQUESTED** [review]
After submitting files in a normal gradeable, they appear to get duplicated:
image
image

Attempting to view the jupyter notebook gives me this error:
image

The jupyter notebook file I am using to test is below; it is from a quantum physics homework:
[PHYS2210Spring2024_HomeworkProblem21_1DWavefunctionCoefficients.tar.gz](https://github.com/user-attachments/files/16180826/PHYS2210Spring2024_HomeworkProblem21_1DWavefunctionCoefficients.tar.gz)

**Comment by williamjallen** [comment]
@powe97 Please don't merge main into random branches without first discussing doing so with the author.  Doing so creates unnecessary conflicts.

**Comment by williamjallen** [comment]
> After submitting files in a normal gradeable, they appear to get duplicated.

I am unable to reproduce this, and I don't see anything obvious in the diff which looks like it could lead to this error.

> Attempting to view the jupyter notebook gives me this error:

Fixed.

**Review by powe97 — APPROVED** [review]
Looks good. In the future it is probably a good idea to implement rendering for $\LaTeX$ as well. Here is how it looks for my example file:

image

**Review by ziesski — CHANGES_REQUESTED** [review]
I was testing and some of the markdown was not properly rendered. For example `<hr>` did not render as expected. Please take a look at my screenshot. (Submitty, terminal, vscode)
스크린샷 2024-07-13 오전 11 59 01

**Comment by williamjallen** [comment]
@ziesski `<hr>` is a HTML tag, and is not supported by our current Markdown setup.  We have HTML rendering [turned off](https://github.com/Submitty/Submitty/blob/8a9cd0c2a55fb3afee88246fd37d7719dc964aab/site/app/libraries/Output.php#L173) in our Markdown config for [security reasons](https://commonmark.thephpleague.com/2.4/security/#html-input).  The Jupyter spec specifies that Markdown cells follow the Markdown spec, and the Markdown spec specifies that Markdown is a superset of HTML.  We don't currently have the ability to fully support HTML in Markdown cells, and I don't see a clear path towards doing so safely.

**Comment by williamjallen** [comment]
Since this has been blocking follow-up work for a while, I boiled down the most basic output cell rendering functionality and committed it to this PR.

**Review by powe97 — APPROVED** [review]
Tested locally, looks good. Below is my example file rendered. The only note I have is that there are no margins; this causes text to be cut off a tiny bit at the very bottom of the render. Approving anyway because this PR has been blocking other work and the functionality is fine. 
image

**Pull request merged**
