### PR TITLE
Stop Autograding Workers JSON from being Overwritten

### PR DESCRIPTION
**Pull request by emaicus**
A quick fix which prevents the autograding workers json from being deleted when configure submitty is called.

### CODE REVIEW

**Comment by MasterOdin** [comment]
Would a better solution here be just not removing the config directory on each run?

**Comment by emaicus** [comment]
@MasterOdin Probably. What was our reason for removing it in the first place?

**Comment by MasterOdin** [comment]
So we do this with the `.setup` folder as well, and I believe the reasoning for this was that you'd be able to generate all files from the running of CONFIGURE_SUBMITTY.py (and getting all the answers t to the questions) so we don't leave behind any files that might have been retired and are nice and "clean". 

Perhaps a better solution would be to just load the worker file into memory around [here](https://github.com/Submitty/Submitty/blob/master/.setup/CONFIGURE_SUBMITTY.py#L145-L151) and then just write it out later. We can move up where we define the constants for reference the files [here](https://github.com/Submitty/Submitty/blob/master/.setup/CONFIGURE_SUBMITTY.py#L145-L151) upwards and just go from there, that way it sort of follows the existing design (even if at this time we're not asking any questions about configuring the workers).

**Comment by MasterOdin** [comment]
Well, I guess we'll hold off any potential refactors of CONFIGURE till some later date given this was merged.

**Pull request merged**
