### PR TITLE
[Refactor:Autograding] Enable flake in more_autogrding_examples

### PR DESCRIPTION
**Pull request by powe97**
### What is the current behavior?
Currently, `flake8` static analysis/linting is disabled on `more_autograding_examples`, as discovered in #10727. So, there is a lot of unlinted code.

### What is the new behavior?
This PR enables `flake8` on this directory and fixes the lint issues.

### CODE REVIEW

**Comment by powe97** [comment]
If this should be split into smaller PRs that is fine but it will complicate the flake exceptions file until all of them are merged.

**Review by dorian451 — APPROVED** [review]
Seems to work

**Comment by powe97** [comment]
After revisiting this initially planning to split it into smaller PRs, I would like to point out that as of today there is only one active PRs that edits `.py` files in `more_autograding_examples` (yes, I went through and checked): #10577, and that PR adds `.py` files and does not edit of the existing ones. _In other words, it is quite literally impossible for this PR to cause merge conflicts with existing PRs._ I checked this before opening this PR to ensure that potential merge conflicts would be minimal, but alas.

While I understand why the recommendation is to lint one file at a time, I feel that opening 45 PRs for linting a directory that is rarely edited (4 commits in 2024, one of which was minor lint) is excessive and pointless given the circumstances.

Additionally, there is currently an open PR (#10562) that lints 22 files at once in a significantly more active directory (site/cypress/e2e, which has had 51 commits in 2024). I do not understand what the problem with this PR is if that one is OK.

**Comment by ziesski** [comment]
I also ran black on this directory last Thursday, but then noticed we have intentional buggy code as well, which I think should be left as it is. Moreover, I do see some value in fixing config related lints, but not in submission related lints, because Sample Submissions should closely mimic actual student submissions, which is rarely linted.

**Pull request closed without merging**
