### PR TITLE
[Bugfix:Autograding] URGENT fix for Autograding error 

### PR DESCRIPTION
**Pull request by williamschen23**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### CODE REVIEW

**Comment by williamschen23** [comment]
related to #9969

**Comment by williamschen23** [comment]
@IDzyre We surprisingly dont have tests that checks the autograding stack trace for errors. Would that be a possible test in the future?

**Review by bmcutler — APPROVED** [review]

**Comment by powe97** [comment]
I double-checked and this appears to be the only remnant of the old `tzlocal` syntax. So the saga should be over now.

**Comment by IDzyre** [comment]
> @IDzyre We surprisingly dont have tests that checks the autograding stack trace for errors. Would that be a possible test in the future?

We didn't have submissions enabled so it was hard to test the autograding

**Pull request merged**
