### PR TITLE
[Feature:RainbowGrades] Add performance warnings to display

### PR DESCRIPTION
**Pull request by zacharymnp**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.

### What is the current behavior?

Display has a checkbox for `warning` that has no functionality.
image

### What is the new behavior?
Can add academic perfromance warnings for students using the Rainbow Grades customization GUI. The visibility of this customization item is linked to the `warning` checkbox under Display.
image

### Other information?

Related to #9685

### CODE REVIEW

**Review by oliiso — CHANGES_REQUESTED** [review]
Image 8-13-24 at 11 33 AM
I was able to have the same gradeables have multiple instances and different target scores. Maybe removing the gradeable name from the list of options once it has been used in a previous warning would be a good approach.

**Review by oliiso — APPROVED** [review]
Duplication is fixed, looks good!

**Comment by williamjallen** [comment]
@zacharymnp It looks like this PR is failing the accessibility test.

**Review by williamjallen — APPROVED** [review]
Code seems reasonable to me.

**Review by ziesski — APPROVED** [review]
Reviewed, Tested, good to go.

**Pull request merged**
