### PR TITLE
[Bugfix:Forum] Remove white shadow in wide threads

### LINKED ISSUE #10345: Wide view forum posts have white shadow in dark mode
**Describe the bug**
When viewing discussion forum posts in the wide view in dark mode, a white gradient appears underneath each post.  

image

**Expected behavior**
The white shadow should be eliminated in favor of a cleaner design.

### PR DESCRIPTION
**Pull request by CCWizma99**
Updating forum.css to remove unnecessary box-shadow in wide threads and add a gray like color to the border to improve the UI for both Light and Dark color themes.

### What is the current behavior?
There is a white shadow underneath each thread and it is not looking good in dark mode.

Dark mode
image
Light mode
image

### What is the new behavior?
When you check forum threads in wide mode, it doesn't show a white shadow in dark mode.
(Optional) 
Instead there will be a gray color border to improve the cleaner look for both Dark and Light modes.

Dark mode
image
Light mode
image

closes #10345 

#### Other information?
Changed forum.css -> .thread-box-full

### CODE REVIEW

**Comment by JWei17** [comment]
Is this the white shadow you mean?
image

**Comment by CCWizma99** [comment]
> Is this the white shadow you mean? image

Yes...White shadow underneath threads list in wide view.

**Review by JWei17 — APPROVED** [review]
Approve, the unnecessary with shadow no longer appears in light, dark, and dark(black) mode.

**Review by RayReyRam — APPROVED** [review]
I also approve this PR, the white shadow is gone, and the forum looks cleaner in my opinion. Files changed looks good aswell

**Review by ArnavPawar — APPROVED** [review]
Fixes it and just changes css so looks good

**Comment by williamjallen** [comment]
Can you please add before and after screenshots to the PR description?

**Comment by CCWizma99** [comment]
@williamjallen 

### Before the update
#### Dark mode
image
#### Light mode
Screenshot from 2024-04-17 09-30-34
### After the update
#### Dark mode
image
#### Light mode
Screenshot from 2024-04-17 09-29-54

**Comment by Kush-Raval** [comment]
> @williamjallen
> 
> ### Before the update
> #### Dark mode
> image
> 
> #### Light mode
> Screenshot from 2024-04-17 09-30-34
> 
> ### After the update
> #### Dark mode
> image
> 
> #### Light mode
> Screenshot from 2024-04-17 09-29-54

Put these pictures in the PR description under "current behavior" and "new behavior". For UI changes we want the before and after in the description

**Review by williamjallen — APPROVED** [review]

**Pull request merged**
