### PR TITLE
Unique ID for autograding_logs

### PR DESCRIPTION
**Pull request by scopeInfinity**
Issue : #1760 
Generates unique ID for logs while auto grading.
Image

### CODE REVIEW

**Comment by MasterOdin** [comment]
Thanks for this! Looks good to me. Assigning @bmcutler to review this.

**Comment by bmcutler** [comment]
I don't want to commit a change that affects the # of items in the logfile mid semester.
Instead, let's replace the process id (2nd column) with an id.

The width of this ID seems like overkill.  (I use these logs regularly and this column is just noise for me).  Instead of just hex, can we use an id with numbers and all upper & lowercase letters and keep this column width small.

**Comment by scopeInfinity** [comment]
@MasterOdin  @bmcutler Thanks for the feedback.
Modified the PR,  Using random string of length 6 for the unique id in place of process id field. 
autograding_logs

**Comment by scopeInfinity** [comment]
Fixed merge conflicts,
Now `autograding_logs` looks like
autograding_logs

**Comment by bmcutler** [comment]
Hi Gagan,
Sorry, this PR conflicts significantly with the recent large change we finally finished to the scheduler/shipper/worker.  I cannot easily resolve conflicts via the command line.  Can you please resolve the conflicts?  Unfortunately it will require re-doing a bit of the work, apologies for the conflicts.
Thanks
Barb

**Comment by scopeInfinity** [comment]
Hi @bmcutler 
Conflicts have been resolved.
But due to some reason, Travis build has not started for this PR.
However, travis build for the same commit[`0f41572`] can also be checked [here](https://travis-ci.org/scopeInfinity/Submitty/builds/359398472)

Thanks
Gagan

**Comment by MasterOdin** [comment]
I made a commit to make the shipper and worker have unique IDs instead of it being blank (`~SHIP~` and `~WORK~` respectively), and it seems that Travis is building properly on this. I'm good with this being merged though.

**Comment by scopeInfinity** [comment]
Thanks @MasterOdin

**Pull request merged**
