### PR TITLE
[Bugfix:InstructorUI] student search function overlap

### PR DESCRIPTION
**Pull request by yanliw123**
i think the original purpose of the function for student search is to have it follow when scroll. So the user may use the search function whenever instead of scrolls to top every time. But I removed all related codes since the purpose of issue #9177 is to have the student search function fixed at its position.

### What is the current behavior?

Search for student, undo, redo button overlaps with Color info of check points, when scrolling down.

### What is the new behavior?
Search for student function now fixed at its position. 
### Other information?

To Reproduce

Go to Lab grading of gradable.
Scroll down

### CODE REVIEW

**Review by ANS1514 — APPROVED** [review]
The change works as intended when I tested locally. Could be worth asking some TA's if they'd like the sticky search bar but that's a conversation for the future. Overall the fix works for the issue it looks to solve.

**Comment by yanliw123** [comment]
> The change works as intended when I tested locally. Could be worth asking some TA's if they'd like the sticky search bar but that's a conversation for the future. Overall the fix works for the issue it looks to solve.

I discussed this with Jaeseok, and we believe that ctrl + f can do the same thing. However, I can try to make it sticky if overall more people believe that's a better way of solving this.

**Review by ziesski — APPROVED** [review]
Works as intended, I checked to see if there is any code dangling, and it seems good to me.

**Comment by bmcutler** [comment]
@yanliw123 please resolve merge conflicts on this PR

**Pull request merged**
