### PR TITLE
[Bugfix:Forum] Fix Forum Post Spacing

### LINKED ISSUE #10070: Markdown posts have padding that non-markdown posts do not
**Describe the bug**

When making a post with Markdown enabled, even if no markdown is used, the resulting post has extra padding because by default the Markdown renderer will add in `<p>` tags for every paragraph. In contrast, when not using Markdown, the text is inserted as is, without `<p>` tags. This leads to an inconsistency in post padding.

Additionally, normal posts have spaces prepended to them at the beginning, but Markdown posts do not.

**Expected behavior**
 Both modes would make the post look the same

**To Reproduce**
1. Make a post with normal text
2. Edit post to use Markdown

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

**Additional context**

Regular post:

```html
<span class="post_content">    Post text here 
</span>
```

Markdown:

```html
<span class="post_content">    <div class="markdown " style=""><p>Post text here</p>
</div>
</span>
```

### PR DESCRIPTION
**Pull request by hansongu123**
closes #10070 

### Please check if the PR fulfills these requirements:

* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

#10118 fixes the first part of #10070 by containing the post text in a block, but this way it adds extra spacing on top and bottom of a post to match that of a markdown enabled post, causing there to be more wasted space.

### What is the new behavior?

This PR adds whitespace control to the non-markdown enabled text and removes the extra spacing for the posts w/ markdown.
A 5px top-margin is added to improve the look and feel.

Before:
image

Now:
image

### CODE REVIEW

**Review by Kush-Raval — APPROVED** [review]
I did a functionality test and there didn't seem to be any glitches. I tested with different size screens and nothing broke the general function of the page. 
The code changes make sense as to how you get the desired result.
Looks good to merge

**Review by jeffreyC4 — CHANGES_REQUESTED** [review]
The fix looks good on my end. Works as intended for single lines and multiple paragraphs. I would change the selector to "post-content" to fix the CSS Lint issues. I would also look into removing ".post_content p:first-child/last-child" because there is no paragraph tag within any of the "post_content" containers.

**Comment by hansongu123** [comment]
@jeffreyC4 there's <p> block created for every paragraph if the post is markdown enabled, and each paragraph get's the same top and bottom margining hence we want to remove them for the first and last paragraphs.  With disabling css lint for these two lines there should be no more failing check.

@Kush-Raval @jeffreyC4 guys can you re-review and make sure the white space control (- -) doesn't affect other things?

**Review by Kush-Raval — APPROVED** [review]
Ran this on my local machine and saw the desired effects. Messed with different screen sizes and formats and the change still worked. Drastic improvement on space inside posts.
Tested as instructor and student.
The code makes sense and I can see why it will result in the desired effect.
Ready to merge.

**Pull request merged**
