### PR TITLE
Fix reply box not disabled when text area is empty

### LINKED ISSUE #10126: Forum reply button should be disabled when text area is empty
**Describe the bug**
The "submit reply to all" button is enabled and clickable when no content has been entered in the forum text box.

**Expected behavior**
The submit button should be disabled when no content has been entered.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by zhanghong27**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Fixes #10126.

### What is the new behavior?
When text area is empty, submit button is disabled and gray out. When text area has input, submit button is enabled and clickable. 
image
image

### CODE REVIEW

**Comment by jeffrey-asm** [comment]
[https://github.com/Submitty/Submitty/pull/10129](#10129) addresses this and accounts for attachments and Cypress conflicts.

**Review by ArnavPawar — CHANGES_REQUESTED** [review]
Looks good think this is a good feature. Just change format of the title and ensure it passes checks and it should be good.

**Comment by IDzyre** [comment]
Should this be closed in favor of https://github.com/Submitty/Submitty/pull/10129 or do they address different issues?

**Comment by IDzyre** [comment]
Closing as a duplicate of #10129

**Pull request closed without merging**
