### PR TITLE
Read More button for long forum posts

### LINKED ISSUE #3575: Too long threads displayed without clipping
**Describe the bug**
Long threads in the Discussion Forum are displayed as is, without any clipping of initial content and then an option to see remaining content.

https://www.loom.com/share/15602cea7fc64a91bd21cae031d45211

**Expected behavior**
A Read More button/link should be displayed after clipping the content upto a certain height.

**To Reproduce**
1. Go to Discussion Forum
2. Create New Thread and enter a very long text
3. See error

**Configuration**
 - OS: Linux
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by xprilion**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
Closes #3575 

### What is the new behavior?
A "Read More" link is displayed for all posts exceeding 200px height. On clicking, the post expands.

https://www.loom.com/share/edec9ce991a84608bc36197e2aa97686

### Other information?
Is this a breaking change? - No
How did you test - On Chrome and Firefox, Elementary OS 5

### CODE REVIEW

**Comment by xprilion** [comment]
@drumilpatel2000 I'll have to check for the code part, it looks tricky but I'll make sure its handled as well 😊

Read Less is obviously a matter worth polling. Facebook does not have a Read Less, while some forums do. In my personal preference I'd skip that!

**Comment by xprilion** [comment]
@drumilpatel2000 the plugin used to provide code colouring is probably setting its own maximum height on any code content. 

Please see this video - https://www.loom.com/share/8798fb57fb164dbd970a35458fb7d105

Any code block on my laptop gets broken at Line 33 and I guess that's okay amount of code to show at once. For content containing both text and code, the "Read More" break does occur when the height of the text part exceeds 200px.

**Comment by drumilpatel2000** [comment]
It seems okay for me but purpose of this PR is not served as one of major purpose of this is maintaining uniformity between posts. When we have `[code][\code]` this breaks PR   and uniformity of posts is destroyed

**Comment by bmcutler** [comment]
Hi, thanks for the suggested contribution, but this isn't a requested feature in any of our courses that use the forum.  Lengthy forum posts have important content and having to click to expand just burdens the user.

**Pull request closed without merging**
