### PR TITLE
[Bugfix:Submission] Disable drag drop if not on last version

### LINKED ISSUE #7097: Confusing functionality of drag & drop from not-last submission
**Describe the bug**
PR #6686 changed how the submit box appears/functions when we are viewing not the last submission.  It does not let you click the drop zone box to get a file browser to select files to upload.  However... you can still drag files into the box.  But now that the files are in the box, you cannot submit them (the buttons are disabled). I was confused why the click to file browser was missing, and thought things were buggy, until I realized I was on not the most recent version and our new design.
Once I switched to the current version, the files that I had dragged were replaced with the files for the final version -- which I only noticed because it wouldn't let me upload, since the files were not different from the most recent submission.

**Expected behavior**
I think drag & drop of files -- or removal of files in the drop zone should be blocked.  The appearance of the drop zone should be more clearly/visuallly disabled.  The text "drop & drop or click to select files" should probably also be modified.  The disabled submit button was not sufficient for me to recognize what was wrong.

### LINKED ISSUE #7108: Switch to most recent version button not disabled for notebook gradeables
**Describe the bug**
When viewing a notebook gradable submission version that is not the most recent version, the green "switch to most recent" is not disabled when it should be disabled.

If a student tries to click it a submission is attempted to be made but then are shown an error message on trying to submit on an older version.

**Expected behavior**
Button should always be disabled

**To Reproduce**
1. Go to notebook gradeable with multiple versions (or submit multiple times)
2. Select a version from the dropdown that is not the most recent
3. See error

**Configuration**
 MacOS firefox

**Screenshots**
Example state where the button should be disabled:
image

### PR DESCRIPTION
**Pull request by loadedskiffer**
### What is the current behavior?
closes #7097 
closes #7108

### What is the new behavior?
Drag and drop functionality is now disabled when not viewing most recent submission. The box is more clearly disabled and the text was modified slightly to avoid confusion.
pr17_1

### CODE REVIEW

**Review by shailpatels — CHANGES_REQUESTED** [review]
Looks good for most gradeables, however the old style of submission box is shown for notebook gradeables with file uploads

The new submission box looks like this:
image

As a result files are no longer shown (not sure if that's important/desired design @bmcutler )

**Comment by loadedskiffer** [comment]
> Looks good for most gradeables, however the old style of submission box is shown for notebook gradeables with file uploads
> 
> The new submission box looks like this:
> image
> 
> As a result files are no longer shown (not sure if that's important/desired design @bmcutler )

I fixed the submission box for notebooks and fixed some twig errors that popped up, for notebook gradeables students can still see their submitted files below the box.
pr16_1

**Comment by shailpatels** [comment]
@loadedskiffer  There are also some existing notebook errors on the grading view, I fixed those and the ones you mentioned in this PR yesterday https://github.com/Submitty/Submitty/pull/7107, I think the easiest way would be to pull that branch into this one

(or locally remove the notebook changes on your branch but keep them in your VM) - whatever is easier for you

**Comment by loadedskiffer** [comment]
> @loadedskiffer There are also some existing notebook errors on the grading view, I fixed those and the ones you mentioned in this PR yesterday #7107, I think the easiest way would be to pull that branch into this one
> 
> (or locally remove the notebook changes on your branch but keep them in your VM) - whatever is easier for you

I merged your branch into mine, should be good now.

**Review by shailpatels — APPROVED** [review]
Looks good,

If you're happy with submitted files no longer being shown in older versions (for non notebook gradeables) @bmcutler  this should be good to merge

**Pull request merged**
