### PR TITLE
[Refactor:PHP] Move queries being executed in views into controllers.

### PR DESCRIPTION
**Pull request by dakriy**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Makes progress on #4537. The current behavior is undesired because the MVC principal is broken, and queries are made inside of views instead of controllers.

### What is the new behavior?
Some (not all) queries were moved out of the views into controllers to be more coherent with MVC principals. 

### Other information?
Some of the controllers are being tested for calling the queries in the controller instead of the view, but not all.

### CODE REVIEW

**Comment by MasterOdin** [comment]
Thanks for this work! I appreciate the effort on getting this done, and will try and get a review done in the next day or two, as I also go through #4576 which has some amount of overlap.

For future PRs, please do not make "omnibus" PRs that covers changes in a bunch of different files where there's not explicit link between the files. For example, it would be nicer to have a PR that just has the changes to `NavigationController` and `NavigationView`, changes to `LateController and `LateDayView`, etc. This allows for a bit nicer of a feedback loop for reviewers and then getting things merged, and a bit easier having it follow along with on-going work.

For this PR how it stands, do not worry about doing that and I'll as I go through be doing a bit of a disjointed review structure, and cherry-pick bits out into master.

**Comment by prestoncarman** [comment]
Our class has been working on this issue and the change grew to be much bigger than first thought. Sorry for the large PR.

**Comment by MasterOdin** [comment]
Gotcha. Like I said, the merge process here is going to be somewhat messy as I cherry-pick pieces of this and #4576, so I apologize in advance.

For my reference, here is the list of file tuple groups:
- [ ] NavigationController, NavigationView
- [ ] GradeOverrideController, GradeOverrideView, GradeOverrideControllerTester
- [ ] LateController, LateControllerTester, LateDayView
- [ ] PlagiarismController, PlagiarismView
- [ ] ElectronicGraderController, ElectronicGraderView
- [ ] SubmissionController, HomeworkView
- [ ] TeamController, TeamView

**Comment by MasterOdin** [comment]
Sorry it took so long for these to land into master. I've cherry-picked most of the changes to files. For the changes to submission and electronic grader, I will use them to help inform future work.

**Pull request closed without merging**
