### PR TITLE
[Feature:TAGrading] Add pronoun student photos page

### LINKED ISSUE #9182: Add Pronouns to Student Photos page
**What problem are you trying to solve with Submitty**
Currently only the instructor can see the user-specified pronouns on the "Manage Students" page.

**Describe the way you'd like to solve this problem**
Let's add the user-specified pronouns (if specified) to the "Student Photos" page.  
Currently, underneath the student's photo we have their preferred name, and their user id.
Let's put the pronouns underneath the user id.

NOTE:  We will also have to change the My Profile page to indicate that ALL members of the teaching staff will have access to the pronoun data entered by students.

### PR DESCRIPTION
**Pull request by sahil-ansari01**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?
Fixes #9182 

### What is the new behavior?
User-specified pronouns added to the "Student Photos" page.

### CODE REVIEW

**Review by ch3nnyj — CHANGES_REQUESTED** [review]
The code seems to be working/running just fine. I do have a suggestion. I think the warning should be below the pronouns in the basic information. Having it on the top can cause some to miss it but having it directly below once you've specified your pronouns would be much better.

**Comment by mahi-pas** [comment]
the note shouldn't be here, it should be in EditPronounsForm.twig.
image

**Review by mahi-pas — CHANGES_REQUESTED** [review]
The note shouldn't be here, it should be in EditPronounsForm.twig.
image

**Comment by mahi-pas** [comment]
The pronouns on the student photos page works
image
It's up to Barb if placing them there is the preferred design choice, but functionality works properly

**Comment by sahil-ansari01** [comment]
Thanks @mahi-pas  I'll make the requested change soon and make a PR!

**Comment by ch3nnyj** [comment]
After talking with our professor, the changes that need to be made was for the pronouns panel when choosing pronouns. See below. We want to changed it to say all members of the teaching staff not just instructors. 
Screenshot 2023-04-16 at 3 10 40 AM

**Review by mahi-pas — APPROVED** [review]
Everything is correct

**Review by ch3nnyj — APPROVED** [review]
Looks all set now, thank you for your contributuion  to Submitty.

**Comment by mahi-pas** [comment]
@bmcutler This is ready for a merge, although I realized that perhaps changing the visibility of pronouns without allowing students to opt into it or warning may be unethical

**Comment by mahi-pas** [comment]
@sahil-ansari01 Could you also put screenshots of the new form message and the pronouns in photos in the original PR message? Please do this for all future PRs as well.

**Comment by sahil-ansari01** [comment]
> @sahil-ansari01 Could you also put screenshots of the new form message and the pronouns in photos in the original PR message? Please do this for all future PRs as well.

@mahi-pas I'm sorry, I am unable to do this currently. Could you not mind. Checking it on my behalf 🙂.
Thanks

**Pull request merged**
