### PR TITLE
[Testing:Linter] Fix PHP linter for #4726

### PR DESCRIPTION
**Pull request by shailpatels**
### Please check if the PR fulfills these requirements:

* tried to fix it as best i could , should be merged after #4726

### CODE REVIEW

**Comment by shailpatels** [comment]
i dont know whats happening anymore

**Comment by MasterOdin** [comment]
Use `vendor/bin/phpcbf` to fix lint problems, easier than trying to fix it by hand.

**Comment by shailpatels** [comment]
Does that script put brackets on new lines, for some reason it would change function 
from ```foo(...){``` to
 ```
foo(...)
{
```
which would then be an error

**Comment by MasterOdin** [comment]
You need to use it in the same way you use `phpcs`:
```
vendor/bin/phpcbf --standard=tests/ruleset.xml
```

If you do not pass in the standard, it will default to something that mandates that above style (which then classes with our standard).

**Comment by shailpatels** [comment]
ohh ok thats what i was doing wrong

**Pull request closed without merging**
