### PR TITLE
Suvendu-UI/markdown_text_area_resizing error resolved

### PR DESCRIPTION
**Pull request by Suvendu-UI**
### What is the current behavior?
Fixes#10008

### What is the new behavior?
Now you can resize it automatically by vertical motion
### Other information?
I tested it in my local server and it worked well

### CODE REVIEW

**Comment by justin-sadakhom** [comment]
@Suvendu-UI What issue does this PR address?

**Comment by Suvendu-UI** [comment]
Markdown text area can be changed at will  by the user but I have changed to automatically vertically

**Comment by justin-sadakhom** [comment]
Make sure to properly link the issue. Also, please read [this page](https://submitty.org/developer/getting_started/make_a_pull_request) to better format your PR.

**Review by DarthNyan — CHANGES_REQUESTED** [review]
Please refer to this [documentation](https://submitty.org/developer/getting_started/make_a_pull_request) on writing PR titles and bodies.

**Comment by williamjallen** [comment]
Duplicate of https://github.com/Submitty/Submitty/pull/10295.

**Pull request closed without merging**
