### PR TITLE
[Feature:Submission] Timezones added to due dates

### LINKED ISSUE #5170: Display timezones with due dates
**What problem are you trying to solve with Submitty**
Currently, submitty only shows the due date and time without a timezone

**Describe the way you'd like to solve this problem**
A quick patch would display timezone, the ideal solution would show adjusted due date based on local timezone

**Describe any potential alternatives you'd tried to solve the problem**
Timezones have mostly been an afterthought since everyone was in the same place and submitty was an aid to in-person teaching.

### PR DESCRIPTION
**Pull request by matgar1997**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?
Closes #5170

### What is the new behavior?
Displays system timezone on due dates

### CODE REVIEW

**Comment by shailpatels** [comment]
If you're making a UI change please include a screenshot so people can quickly see the change :)

This is what the Timezone is displayed at on the gradeable navigation page 
image

**Comment by matgar1997** [comment]
@shailpatels Good catch not sure how I missed that one
@MasterOdin Agreed, didn't know that was possible

**Comment by shailpatels** [comment]
@matgar1997 @bmcutler @MasterOdin Maybe we should include the UTC offset - when Submitty takes over the world how will we know if its Eastern Daylight Time or Australia Eastern Daylight Time!

**Comment by MasterOdin** [comment]
Well, one is EDT and one is AEDT...

Assuming an increased usage of purely online classes, it would be better to allow people to set their desired timezone than go to in depth of what we show on the UI assumes a single timezone globally.

**Pull request merged**
