### PR TITLE
[Feature:InstructorUI] Course Materials Access on Dashboard

### PR DESCRIPTION
**Pull request by NiaHeermance**
### What is the current behavior?
The Student Activity Dashboard does not include course materials access information.

### What is the new behavior?
Course materials access information appears both on the page and in the downloaded csv file feature. You can also highlight students who accessed course materials on a specific day.

### Images
image
image

### CODE REVIEW

**Review by DarthNyan — CHANGES_REQUESTED** [review]
Feature mostly works. Table displays and updates properly and CSV download works.

Small thing: when pressing the clear filters button that the course material access date doesn't clear, but all the other fields do.

**Review by VVVITH — CHANGES_REQUESTED** [review]
The clear button cannot clear the new feature selection.

**Comment by NiaHeermance** [comment]
Fixed the clear button!

**Review by VVVITH — COMMENTED** [review]
The clear button now works will.

**Review by cjreed121 — APPROVED** [review]
Code looks good. Tested it and works as expected.

**Pull request merged**
