### PR TITLE
[Bugfix:Forum] Always display 'Show history' button

### LINKED ISSUE #10174: "Show History" button only appears when posts ordered hierarchically
**Describe the bug**

The button to show the edit history of a post in the forum disappears when the posts are not sorted hierarchically.

**To Reproduce**
1. Create a forum post and then edit it.
2. Click the "show history" button in the bottom left corner of the post to view the history of edits.
3. Exit the post history, then click on the "more" drop down menu in the top right of the page. Click "alpha by registration post order"
4. Observe that the "show history" button disappears.

**Expected behavior**

The "show history" button should remain visible and usable regardless of how the posts are ordered. The "reply" and "split post" should remain only visible when the posts are ordered hierarchically.

Hierarchical ordering:
image

Alpha by registration post order:
image

### PR DESCRIPTION
**Pull request by Xiayucheng1212**
Fixes #10174

### What is the current behavior?

Currently the "Show Display" button only displayed in "Hierarchical Post Order", but it should be shown in all kind of order.
### What is the new behavior?
The "Show History" button will be properly displayed no matter under which order.
截圖 2024-02-10 下午11 20 03
截圖 2024-02-10 下午11 20 38

### Other information?
Originally the "Show History" button was defined only when "display_option === tree", which is exactly the  Hierarchical order. Therefore, I extract the button from the "display_option === tree" condition, and make it rendered in any condition.

### CODE REVIEW

**Comment by DarthNyan** [comment]
Code looks good to me and fix works. If you can fix the title check I'll approve. 

The title subject is fine as-is, but if you were to edit it to something like, "Always display 'Show history' button" that might be clearer.

**Review by ZheyuDeng — APPROVED** [review]
Tested the code and reproduced the issue. Issue is solved but still need to fix the pr title check and cypress UI check.

**Comment by DarthNyan** [comment]
I think the failing title check is due to the 'F' in BugFix being capitalized. Try "[Bugfix:Forum]..."

**Comment by Xiayucheng1212** [comment]
@DarthNyan Hi, thank you for the review, could please merge this PR?

**Review by williamjallen — APPROVED** [review]
Thanks for this contribution!  A great thing to do in a follow-up PR would be a Cypress test to prevent this from occurring again in the future.

**Pull request merged**
