### PR TITLE
[Feature] Download Zips in Course Material Page

### LINKED ISSUE #3746: Download zip of a subfolder within course_materials
**What problem are you trying to solve with Submitty**
Currently if a student wants to download all of the files in a folder of the course materials, they have to click and download on each individual file.  Let's add a download link on each folder for the course materials that will allow zip & download of all files/folders under that folder with a single click.

### PR DESCRIPTION
**Pull request by zjxiaohan**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Documentation has been updated/added if relevant (**Will do if the changes are approved**)

### What is the current behavior?
Closes #3746 .

### What is the new behavior?
In the course material page, instructors and students are able to download zips made of files in a directory.

### Other information?

Instructor downloading the `bin` folder:
Screenshot from 2019-06-03 20-44-10

Student downloading the `bin` folder:
Screenshot from 2019-06-03 20-51-12

### CODE REVIEW

**Comment by zjxiaohan** [comment]
@shailpatels 

Hi. Thank you for your review! Sorry, I forgot to test folder names with space. Thank you very much for doing that.

> I think there is a missing check for individual files for students to download.

Sorry I cannot reproduce this bug. Did you download the files as a student?

> Theres also an issue where if I download a nested file with a space it does not download correctly on firefox.

Fixed by replacing the space with underlines in the recent commits.

**Comment by shailpatels** [comment]
@zjxiaohan 
Yes I think the issue is nested directories. Here's an  example I set up as an instructor:
instructor

So the file "even better.txt" should not be shared with the student and it is not shown to the students view which is good, but if I download the entire folder "nested", "even better.txt" gets downloaded as well.

Student view on submitty:
studeview

However after downloading "nested"
stude

"even better.txt" should gets downloaded anyways

**Comment by zjxiaohan** [comment]
I'll check again. Thank you very much.

**Comment by zjxiaohan** [comment]
@shailpatels 

Hi. I finally realized why this happens.

I only checked if the file exists in the .json, which looks like this:

```
  '/var/local/submitty/courses/s19/sample/uploads/course_materials/nested/blah.txt' => 
    array (size=2)
      'checked' => string '1' (length=1)
      'release_datetime' => string '2019-06-08 03:53:18-0400' (length=24)
  '/var/local/submitty/courses/s19/sample/uploads/course_materials/nested/New folder/even better.txt' => 
    array (size=2)
      'checked' => string '0' (length=1)
      'release_datetime' => string '2019-06-08 03:57:27-0400' (length=24)
```

However, if the prof checked one file and then uncheck that, there will be an entry in the json.

This problem has been fixed.

Thank you so much for testing and coming up with this critical bug!

**Comment by shailpatels** [comment]
@zjxiaohan Happy to review :)

**Pull request merged**
