### PR TITLE
Iris updates (plus automatic Linting)

### PR DESCRIPTION
**Pull request by bluemellophone**
Updates to Iris to use SCP instead of RSYNC (version 2)

### CODE REVIEW

**Comment by bmcutler** [comment]
Your linting is conflicting.  Please don't lint unrelated files :(

**Comment by MasterOdin** [comment]
Resolved the conflict in both iris_fixes and iris_updates as I'm not sure who is using which branch for what

**Comment by bmcutler** [comment]
@bluemellophone added commits onto this branch that had already been squashed, merged, & deleted.   Most of this branch is already on master.

**Comment by MasterOdin** [comment]
What commits are new and should be separated into their own branch to be merged into master?

**Pull request closed without merging**
