### PR TITLE
[Testing:CourseMaterials] Changed attachFile to selectFile

### PR DESCRIPTION
**Pull request by jason490**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
The previous cypress test used functions that are no longer supported in cypress

### What is the new behavior?
Updated the cypress test to use functions that are supported

### Other information?
Changed attachFile to selecFile and added the path to the file.
Link to where `attachFile` was deprecated:
https://docs.cypress.io/guides/references/migration-guide#Migrating-from-cypress-file-upload-to-selectFile

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
Do we still need the `cypress-file-upload` plugin?  If not, it should be removed from our `package.json`.

**Comment by jason490** [comment]
> Do we still need the `cypress-file-upload` plugin? If not, it should be removed from our `package.json`.

It seems like it is still required

**Comment by hansongu123** [comment]
The newest Cypress dependabot PR from two days ago seems hasn't been failing tests.

**Comment by williamjallen** [comment]
> The newest Cypress dependabot PR from two days ago seems hasn't been failing tests.

`attachFile` (and the `cypress-file-upload` plugin as a whole) has been deprecated, but has not been removed.  That means that using `attachFile` is no longer recommended, but existing usages won't break anything (yet).

**Review by williamjallen — APPROVED** [review]

**Pull request merged**
