### PR TITLE
[Refactor:SubminiPolls] Refactor Poll JS code from Twig to JS

### LINKED ISSUE #10614: Move Javascript for Polls from Twig to JS
**What problem are you trying to solve with Submitty**

#10337 introduced a significant amount of Javascript to ViewPoll.twig that would fit better in poll.js so that it can be properly linted and maintained.

### PR DESCRIPTION
**Pull request by Kush-Raval**
Fixes #10614 
### Please check if the PR fulfills these requirements:
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
There is a lot of JS code in the twig file that isn't a good coding practice since we can reformat this code and place it into the JS file where that code will be linted.

### What is the new behavior?
Placed the code in the JS file by making a function with a sub-function and running only the function in the twig, so the majority of the JS code gets linted.
### Other information?

To test, verify that no functionality was broken.

### CODE REVIEW

**Review by ryvaru — CHANGES_REQUESTED** [review]
When verifying that no functionality was lost, I found a potential error in the student View Poll page. As an instructor, when I clicked 'Accepting Answers' and then 'View Poll', the UI correctly displayed the remaining time left on that poll. Then, when I logged in as a student and clicked 'View Poll' on that same poll (which still had time remaining), it did not display the remaining time left at all.

**Comment by Kush-Raval** [comment]
> When verifying that no functionality was lost, I found a potential error in the student View Poll page. As an instructor, when I clicked 'Accepting Answers' and then 'View Poll', the UI correctly displayed the remaining time left on that poll. Then, when I logged in as a student and clicked 'View Poll' on that same poll (which still had time remaining), it did not display the remaining time left at all.

Oh, I see where the problem lies, this is interesting because the cypress test should have caught this accessibility error. Thank you for the review.

**Review by ryvaru — APPROVED** [review]
Tested thoroughly and no functionality seemed to be broken or different from main. Code changes also make sense as it's transferring the same function from twig to JS as intended. Approved.

**Review by ziesski — APPROVED** [review]
Haven't tested the functionality, but the script portion of code is moved from twig to js, which is reasonable + good practice.

**Pull request merged**
