### PR TITLE
[Refactor:Developer] Remove all redundant cyvisit('/') 

### LINKED ISSUE #9910: Remove unnecessary visit statements in Cypress CI
**What problem are you trying to solve with Submitty**
When #9522 was merged, this made all of the cy.visit('/'); statements before logging in obsolete, as the login function no longer required the UI to be visible, since it is using a post request. 

**Describe the way you'd like to solve this problem**
Remove all of the cy.visit('/'); statements that are directly before a cy.login() statement (or in a beforeEach that happens before logging in during the test), as they are no longer needed, and it just adds unnecessary time/complexity to the tests. 

**Additional context**
NOTE: The cy.visit('/') statement in the logout function is still needed, just none of the ones before the cy.login() statements.

### PR DESCRIPTION
**Pull request by Akshun-01**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Fixes #9910

### What is the new behavior?
All the redundant cyvisit('/'); statements have been removed from the code, thus reducing the unnecessary time/complexity from the tests.

### CODE REVIEW

**Review by jason490 — COMMENTED** [review]
It seems like theirs multiple redundant `cy.visit([course])` calls in sidebar.spec.js. We should fix it in another PR.

image

**Review by jason490 — COMMENTED** [review]
Besides what I said above, everything looks good. I will approve this PR after the cypress tests gets fixed as its currently failing on main

**Comment by Akshun-01** [comment]
> It seems like theirs multiple redundant `cy.visit([course])` calls in sidebar.spec.js. We should fix it in another PR.
> 
> image

should I revert this change or are you suggesting to open a different pr to remove other redundant cy.visit([course]) statements ?

**Comment by Akshun-01** [comment]
> Besides what I said above, everything looks good. I will approve this PR after the cypress tests gets fixed as its currently failing on main

Do I need to make some other changes on my side for this ? Could you please explain what needs to be done, I don't have much experience with cypress.

**Comment by jason490** [comment]
What I can see so far, this is PR is good to go and you don't need to make any changes.

**Comment by jason490** [comment]
> > It seems like theirs multiple redundant `cy.visit([course])` calls in sidebar.spec.js. We should fix it in another PR.
> > image
> 
> should I revert this change or are you suggesting to open a different pr to remove other redundant cy.visit([course]) statements ?

If you want to make a new PR for what I mentioned, sure. I was just pointing it out, for a future PR.

**Comment by 04vmatsibekker** [comment]
It looks like the cypress is failing for some of the spec.js files. But I didn't see that you made changes to those specific files.

**Review by taorif25 — COMMENTED** [review]
Looks good, only removes redundant code and successfully closes the issue. Since cypress tests are a little flaky right now, I'll come back and approve once they're fixed.

**Review by taorif25 — APPROVED** [review]

**Comment by Akshun-01** [comment]
> cy.visit([course])

Hey, I checked the code there is only one such occurrence of the line `cy.visit([course])` 
are you referring to some other cy statements as well which might be redundant?

**Comment by IDzyre** [comment]
The visit(course) statement is due to the sidebar being different for inside the course vs outside of the course, so I believe that statement should stay.

**Pull request merged**
