### PR TITLE
[Feature:TAGrading] student view of peer grades

### PR DESCRIPTION
**Pull request by jchulton**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Students who have been peer graded cannot view grades assigned by a certain peer if there are more than five peers, and cannot view a pdf with annotations from only a certain peer.

### What is the new behavior?
Can switch to a peer feedback mode, in which a student can view the grades, comments, and annotations made by individual peers. This is in preparation for grader feedback, coming in a future PR.

### CODE REVIEW

**Comment by emaicus** [comment]
Pushed a UI update which made component rendering a re-usable function. 
Two bugs I encountered: 
1. No peer is selected by default when switching to feedback mode (you should automatically select peer 1)
2. Confetti is triggered when clicking on the feedback mode button if you have full credit.

Also, please pull all new javascript out of twig and put it in a `.js` file. I believe there is one for the page already. This is especially important as we move towards linting our javascript.

**Comment by jchulton** [comment]
The above problems have been fixed in the latest commit

**Comment by jchulton** [comment]
Pushed a fix to confetti

**Comment by jchulton** [comment]
Confetti is now gone from TAResults.

**Pull request merged**
