### PR TITLE
[Feature:Submission] keep previous files uploaded

### LINKED ISSUE #4837: Get rid of "Keep Previous Files Uploaded" course setting
This setting does not work well with notebook gradeables, and it's also not well-understood on what it does by users (or even if it exists).

Let's delete the setting, and just always keep previously uploaded files in the buckets/inputs.

### PR DESCRIPTION
**Pull request by mukul-kmr-jha**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
Closes #4837 
### What is the new behavior?
*Keep Previous Files uploaded* option is now removed and the previous files are now kept in bucket by default.

### CODE REVIEW

**Comment by mukul-kmr-jha** [comment]
@MasterOdin Hey PTAL!

**Comment by bmcutler** [comment]
The submission box of files *should* be empty if you roll back to an earlier submission.
We do not support modification of earlier submissions.   (this is not a git/version control system.)
We think that would be more confusing than helpful to intro programming students.

**Comment by shailpatels** [comment]
Whoops my bad, my understanding was that each version was supposed to show you your uploaded files for that version (since we keep every version's upload around). I'll continue testing with that in mind

**Comment by shailpatels** [comment]
This looks good but you need to fix some of the end to end tests that are failing

**Comment by mukul-kmr-jha** [comment]
I'm on it .

**Comment by mukul-kmr-jha** [comment]
@shailpatels please take an other look . Thanks!

**Comment by bmcutler** [comment]
@mukul-kmr-jha please resolve conflicts

**Comment by bmcutler** [comment]
@mukul-kmr-jha this PR is failing multiple end-to-end tests
please let us know if you need help debugging the errors.

**Pull request merged**
