### PR TITLE
[Feature:Forum] Blockquote Visual Indicator

### LINKED ISSUE #10073: Blockquotes have no visual indicator
**Describe the bug**

Markdown blockquotes have no padding/margin or borders to indicate that there is a blockquote

**Expected behavior**

Blockquotes should have some padding

> like this

**To Reproduce**
1. Insert a blockquote into Markdown text
2. Look at the preview

**Configuration**
 - OS: [e.g. Windows, Linux, ...] MacOS
 - Browser [e.g. Chrome, Safari] Chrome

**Screenshots**

Screenshot 2023-12-14 at 10 31 10 AM

**Additional context**

Input text: 

```md
> of all time
```

### PR DESCRIPTION
**Pull request by ryvaru**
Closes #10073 

### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently, blockquotes are not an actual feature that users can use when selecting the Markdown option as they could with bold, italics, code, or links.

### What is the new behavior?
The code implements the blockquote feature when a user types ">" in front of text in a single line, or if they click the "Blockquote" button in Markdown and replace the default text.

image

Black Mode:
image

Light Mode:
image

### Other information?
To test, select the Markdown button and type ">" in front of text or click on the button and replace the default text.

### CODE REVIEW

**Comment by williamjallen** [comment]
Can you add a screenshot of the new feature in light mode to the PR description for documentation purposes?

**Comment by ryvaru** [comment]
> Can you add a screenshot of the new feature in light mode to the PR description for documentation purposes?

Yes, light mode screenshots are now posted in the PR description.

**Review by williamjallen — COMMENTED** [review]
Looks great!  One comment though: should the quoted text be somewhat grayed out to signify that it's a block of quoted text?  For example GitHub does this:

> Here's some quoted text

**Comment by powe97** [comment]
Changed colors to use `colors.css` and respect WAVE compatibility with light and dark themes.

image
image

**Review by powe97 — APPROVED** [review]
Tested: nested blockquotes, blockquotes in the message preview, WAVE compatibility in both light and dark mode.

**Pull request merged**
