### PR TITLE
Add Confetti to Submitty

### PR DESCRIPTION
**Pull request by shailpatels**
## Confetti 2.0 Features
- on click or mouse enter will now end the confetti animation
- added support for seasonal confetti (<i> Note: student grade database deleted to make room for extra confetti </i> )
- "Submitty" typo replaced with "Shailmitty" across website

### If Autograding or Total score is greater than or equal to the max score then confetti! 

ezgif-3-6e75e4450ece

Fixes & Closes all issues everywhere
(May accidentally delete all jQuery and add Bars to forum)

### CODE REVIEW

**Comment by bmcutler** [comment]
👍

**Comment by shailpatels** [comment]
@emaicus 
This is because I'm using an HTML canvas to draw the confetti, once the animation is complete the rest of 
the page can receive mouse clicks again - a refresh will kill the animation completely

**Comment by emaicus** [comment]
Ah, I see! This appears to work as intended then :)

**Comment by andrewaikens87** [comment]
Ready to be merged

**Pull request merged**
