### PR TITLE
[Bugfix:Submission] Instructor access blocked if not on team

### LINKED ISSUE #9489: A Notebook gradeable as a team assignment causes a "Server Error"
**Describe the bug**
I created a Notebook configuration as a Team Gradeable. After configuring myself as a team of 1, I tried submitting to the Gradeable, but it failed with the frog robot and a Server Error. 

**Expected behavior**
Team members should be able to select to the Submit button for the gradeable and then be able to fill out and submit the form. The Form should apply to all of the students for purposes of grading.

**To Reproduce**
1. Create a team gradable with a student upload component
2. Use the attached config.json file 
3. Go to the Submitty main page and select to Submit to the Gradeable you created. (This will give you a "bad" submission page without the fields defined in the configuration file. I am not sure if this step is necessary, but I am including it because I did this every time by mistake and it may be salient.)
4. Go back to the Gradeable page and create a single person team
5. Go back to the Graeable page and hit "SUBMIT" to make a submission to the Gradeable.
6. See the error.

[config.json.txt](https://github.com/Submitty/Submitty/files/11887402/config.json.txt)

**Configuration**
 - OS: Windows
 - Browser Microsoft Edge
Version 114.0.1823.58 (Official build) (64-bit)

**Screenshots**
None

**Additional context**
The configuration file is attached. It is for the RCOS Submitty. https://submitty.cs.rpi.edu/courses/u23/csci2960 The non-working team assignment is named "Garbage, do not use". The working individual assignment is "EdgeX Equipment Checkout"

### PR DESCRIPTION
**Pull request by 04vmatsibekker**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

closes #9489.
Currently when instructors  create a Notebook configuration as a Team Gradeable and configure themselves as a team of 1, a failure occurs. 

### What is the new behavior?

No more frog error in the console log

### CODE REVIEW

**Review by bmcutler — DISMISSED** [review]
After making these edits, I'm seeing an additional error:

Screenshot 2023-06-29 at 10 39 34 AM

**Comment by 04vmatsibekker** [comment]
> After making these edits, I'm seeing an additional error:
> 
> Screenshot 2023-06-29 at 10 39 34 AM

I didn't cross that issue when I was testing out my fixes, so I am going to work on reproducing that issue. But I have applied a fix that will probably fix that issue.

**Comment by williamjallen** [comment]
Can you please update the title to be a bit more descriptive?  Many of the bugs we fix are "server error"s, so it provides almost no information when you say that you've fixed a server error.

**Comment by NiaHeermance** [comment]
Currently have this on the main page.
image

**Comment by 04vmatsibekker** [comment]
> Currently have this on the main page. image

I think I might have an echo in my code that I forgot to take out

**Review by NiaHeermance — APPROVED** [review]
I was indeed able to submit with no error. Awesome!

**Comment by bmcutler** [comment]
@04vmatsibekker please resolve merge conflicts

**Review by mahi-pas — APPROVED** [review]
I was able to submit without any issues

**Review by mahi-pas — CHANGES_REQUESTED** [review]
You are still able to access submission without a team as instructor if the gradeable is past due or when grades are available.

image
image

It works properly for instructor for open, alpha and, beta

**Review by mahi-pas — CHANGES_REQUESTED** [review]
image
For TA the button is still active for past due/grades release, but it won't let you access the submissions page without making a team

**Review by mahi-pas — CHANGES_REQUESTED** [review]
image
It says "overdue submission" during past due when it should say "must be on a team to submit"

**Comment by mahi-pas** [comment]
> image For instructors, It says "overdue submission" during past due when it should say "must be on a team to submit"

Same issue for grades available
image

**Review by mahi-pas — APPROVED** [review]
Tested for Instructor, Grader, TA, and Student for alpha, beta, open, past due, and grades available. Looks good to me.

**Pull request merged**
