### PR TITLE
[Feature:InstructorUI] Reorganized grading stats page

### LINKED ISSUE #4233: Re-organization of Grading Stats Page
**What problem are you trying to solve with Submitty**
First timers to this page are not sure what to do on this page.  

**Describe the way you'd like to solve this problem**
Here's a proposal:

grading_stats_page

Most people should click on the grading index page (top left), and we explicitly list what is available.

Some TAs like the shortcut to jump into grading (top right).  This button may currently be broken.  @Kevin-MM will tackle this related to...  #3951

The tabs have been reordered and re-labeled.

The less frequently used buttons are at the bottom.  (and some are white)

### PR DESCRIPTION
**Pull request by thef1stofhername**
### Please check if the PR fulfills these requirements:

* [X] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
Closes #4233 
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(4)
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(5)
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(6)
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(7)

### What is the new behavior?
The page layout more closely represents Barb's idea (some stuff may not be visible because of grading assignments/teams) but I have them arranged
62163768-1327a480-b2e9-11e9-9fa7-43750c72fc0e
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(1)
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(2)
Screenshot_2019-07-31 Submitty Sample Autograde and TA Homework (C System Calls) Grading(3)

click on some assignments that have been/are being graded and see what's up

### CODE REVIEW

**Comment by bmcutler** [comment]
Please change the button text to match the new sketch.
Please add the bulleted list of information next to the "grading index" button.  (On page documentation)

**Comment by thef1stofhername** [comment]
Screenshot_2019-08-01 Submitty Sample Grading Team Homework Grading
Screenshot_2019-08-01 Submitty Sample Autograde Only Homework (Simple Python) Grading
Screenshot_2019-08-01 Submitty Sample Grading Homework Grading

**Comment by thef1stofhername** [comment]
text changed, list added

**Comment by bmcutler** [comment]
We shouldn't have the manual grading tab or overall histogram if there is no manual grading
for this assignment.

Also if there is no autograding, we don't need that tab -- but all submissions go through the
autograder stage, so by this I mean no points are awarded for autograding.

**Pull request merged**
