### PR TITLE
Add Fix for StopLights for Peer View (#5577)

### PR DESCRIPTION
**Pull request by josharsh**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### CODE REVIEW

**Comment by jchulton** [comment]
The bugs @emaicus pointed out are due to edge cases in the $info["graded_groups"]. Take a look at ElectronicGraderView.php lines 522-547 (where $info["graded_groups"] is aassigned) and make sure these edge cases are considered.

**Comment by jchulton** [comment]
This fixes the if a student has been graded but not submitted, no stoplights appear bug, but it doesn't fix teh if a student has not submitted, both TA and Peer stoplights appear bug
image

**Comment by jchulton** [comment]
The "Peer stoplights only show up for instructors/TAs if they have completely finished their non-peer grading." bug is still present.

Also, here is an odd bug: I have a gradeable with one peer grading component and mark and no non-peer grading components/marks. If I grade this component as a peer, it will show as graded for all other peers in the grade details page (both score and spotlight). If I add a non-peer component, it suddenly only shows as graded for the peer who actually graded it. This is a master bug and seems out of scope of this PR, so I don't think it should hold up this PR.

**Comment by josharsh** [comment]
@jchulton This is because of dependency of both of the features of the status of Manual Grading which somehow contains both manual TA and manual Peer grading. Like we discussed in the meeting, individually Peer Stoplights and Non Peer Stoplights seem to work well. For the bug ,"The instructors only see peer marks when non-peer grading is complete bug is still present" we discussed to include in later PRs.(Because of the need for separate functional paradigm)

P.S I have slacked you more on this with screenshots and about the bug you mentioned when having only "1 Peer Component" and no non peer component.

**Comment by jchulton** [comment]
@josharsh Thank you for messaging me and for the reminder above. This PR is good to merge and we will address the function rework in later PRs

**Pull request merged**
