### PR TITLE
[Feature:System] Can Email Anyone

### PR DESCRIPTION
**Pull request by NiaHeermance**
### What is the current behavior?
Currently, Submitty's email API only allows emails to be sent to people with a Submitty user id.

### What is the new behavior?
Now, developers can send emails to anyone. This PR also adds emailing the sysadmin when a student readds themselves to a course, see PR #9768.

### How to Test?
As an instructor, move a student to the Null section and make sure you untick "Manual." Then, as that student, go to the course's page. On the No Access page you get, click the join button. Make sure that before you dropped the student, the student had done some sort of activity in the course within the past three days. Now, as an instructor, go to the email status page and see that one of the emails is to "Sysadmin."

### Images
image

This PR should only be merged after PR #9768 is merged.

### CODE REVIEW

**Comment by williamjallen** [comment]
Should this branch be deleted?  Is this PR superseded by another one?

**Comment by NiaHeermance** [comment]
> Should this branch be deleted? Is this PR superseded by another one?

I was trying to recreate the PR but rebase it so that the changes were based off of my unmerged branch rather than main, but it didn't end up working. I'll try that strategy again someday if I have PRs based off unmerged branches. In any case, I was stupid and deleted this branch before I was done, and I deleted it via my local machine with git commands, so I had to recreate this branch.

In any case, here's the recreated PR https://github.com/Submitty/Submitty/actions/runs/6274888619/job/17041163863?pr=9799.

**Comment by williamjallen** [comment]
In this case, you could have just set the remote branch to `origin/email-sysadmin` on your new local branch and force-pushed the new changes rather than creating an entirely new PR.

There's nothing wrong with what you did of course, but this is something to keep in mind for the future because it might save you work later.

**Comment by NiaHeermance** [comment]
Gotcha!

**Pull request closed without merging**
