### PR TITLE
[UI/UX:Forum] top-duck button for forum

### PR DESCRIPTION
**Pull request by ziesski**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

Screen Shot 2023-10-30 at 5 11 46 PM

Here is the draft of duck button in dark mode 

Screen Shot 2023-10-31 at 2 10 21 PM

============ 11/05/2023 
Here is the updated duck icons @williamjallen @bmcutler 
DUCKS-outline

### What is the current behavior?
I couldn't find @ArnavPawar  PR for duck button, so I am putting it in the site/public/img directory for now.
Removed the feather, and made two versions one with gray, one with original color, as discussed with Barb.

### CODE REVIEW

**Comment by ArnavPawar** [comment]
yea, it's not a pr it's just a branch right now called UpvoteDiscussionForm. But I can add the files to that myself. Thanks for making them they look good

**Comment by williamjallen** [comment]
What do the ducks look like in dark mode?

**Comment by ziesski** [comment]
> ey look good

good point, Barb and I did talk about it last meeting, and decided to make two off buttons for each mode, and I forgot about it. will update with image.

**Comment by ziesski** [comment]
@williamjallen I have updated the image on the original post, please review them :)

**Review by ArnavPawar — APPROVED** [review]

**Pull request merged**
