### PR TITLE
[Bugfix:Notifications] Add keepalive messages/heartbeats to websockets

### PR DESCRIPTION
**Pull request by emaicus**
By default, `nginx` drops inactive connections after sixty seconds. As a result, our websocket connections are frequently dropped and subsequently reconnected after an interval. To combat this issue, this PR adds a "ping" heartbeat message to each websocket, which is sent once every fifty seconds.

### CODE REVIEW

**Comment by shailpatels** [comment]
I think this should work,
one note is that JavaScript intervals on tabs that are inactive will be considered 'low priority' and the timer may either be delayed to stopped altogether but if that's not a problem this should be fine then.

Alternative would be to set [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) to some big number (10m, 1h, 1d etc) I searched a little bit and it appears you can't just disable this however.

**Comment by shailpatels** [comment]
I would say maybe extend the timeout to 5m or something else long and we can have an interval on each page that uses sockets that checks the websocket `readyState` every x interval and trys to reconnect if closed

this would give extra protection against people who may tab out to do something else which might be a usecase with something like office hours q ?

**Comment by MasterOdin** [comment]
It's almost certainly better to be dealing with keep alive frames from the server to the client, as it also allows the server to kill off dead connections from its memory for connections that may have been improperly closed client side. Ratchet provides this functionality, it just needs to be enabled through a function call. The benefit of this method is that this would then follow the spec for websockets and ping/pong frames: https://tools.ietf.org/html/rfc6455#section-5.5.2.

**Comment by shailpatels** [comment]
Make sure the websockets service is restarted after installing this code
`systemctl restart submitty_websocket_server.service`

**Review by shailpatels — APPROVED** [review]
Approved, best code i've ever seen

**Pull request merged**
