### PR TITLE
'Allow late submission' saves to database and in edit gradeable page

### LINKED ISSUE #2146: Add Option to Create/Edit Gradeable to disable late submissions
It can be desirable to prevent students from submitting late.  This option should prevent students from making overly late submissions.  Details on exactly how late days and extensions should interact with this are to come later, but it should be an option on the create/edit gradeable page at least.

### PR DESCRIPTION
**Pull request by KevinMackenzie**
Closes #2146
Previously, this option was never saved to the database and the was not configurable in the edit gradeable page.  This does not add support for preventing overly late submissions when this flag is enabled, but that is now possible with this PR.

### CODE REVIEW

**Comment by bmcutler** [comment]
Also add this text somewhere nearby: 

"Submissions received after the deadline will be automatically recorded as a zero if late days are not allowed for this assignment (or the student does not have sufficient late days to cover the submission) and no excused absence extension is entered for this student for this gradeable."

and add the link:  "Late Days & Extension"  http://submitty.org/student/late_days

**Comment by bmcutler** [comment]
It does not appear to autoset to zero for me (mac/chrome).  Also, please read my requests again.

**Comment by KevinMackenzie** [comment]
There are some changes I'm waiting on making until #2613 is finalized.

**Comment by bmcutler** [comment]
Opened new issue #2745 to use this boolean.

**Pull request merged**
