### PR TITLE
Explicitly set the path where Dr. Memory was being extracted

### PR DESCRIPTION
**Pull request by inlinefan**
Explicitly set the path where Dr. Memory was being extracted and changed the link to reflect it

### CODE REVIEW

**Comment by MasterOdin** [comment]
This is still downloading that tar.gz to ${INSTALL_DIR}/JUnit. We should either remove the ```cd``` on line 132 (and instead cd to a common directory to hold these tars) or have a ```cd ${INSTALL_DIR}/DrMemory``` after line 153 (which I'd prefer)

**Comment by inlinefan** [comment]
Is there a reason to keep the tarballs around once it is extracted?  We could put them in /tmp so that they are cleared on reboot, or have the script delete them explicitly.  If there is benefit to keeping them, I'm ok with adding an extra cd in there.

**Comment by MasterOdin** [comment]
No, I don't think there's any particular reason to hold onto the tars after we extract the contents

**Comment by inlinefan** [comment]
Cleaned it up

**Comment by MasterOdin** [comment]
I'm good with this now

**Pull request merged**
