### PR TITLE
[UI/UX:Submission] Changed default radio button

### LINKED ISSUE #8821: default radio button to 'submit by bulk pdf upload'
**What problem are you trying to solve with Submitty**
If a gradeable is a submit by bulk upload gradeable

Screen Shot 2023-02-02 at 10 25 55 PM

currently the submission page for the instructor/graders defaults to Normal Submission, which often leads to user errors when we 
grader mistakenly uploads the exams as a submission for themselves.

Instead, let's default the radio button in this case to "Bulk PDF Upload"
(don't remove the other options, since sometimes we do use the other options to upload special cases)

Screen Shot 2023-02-02 at 10 26 27 PM

### PR DESCRIPTION
**Pull request by hasthik**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Current default choice is Normal Submission

### What is the new behavior?
Fixes #8821 and makes submit by bulk pdf upload as default choice

### CODE REVIEW

**Comment by williamjallen** [comment]
As a general rule, we don't include the issue number a PR fixes in the PR description to save space.  I see you're failing the title check because SubmitBox is not a valid module.  Reading through this document might be helpful: https://submitty.org/developer/getting_started/how_to_contribute

**Review by shailpatels — APPROVED** [review]
Looks good and works as described, the bulk upload option is auto-checked and the warning banner shows for it.

Thanks for the contribution! 

The only thing is to fix up the title as @williamjallen mentioned and then it should be good to go

**Comment by bmcutler** [comment]
thanks for your contribution

please follow the instructions here on how to title your PR so that it passes the test and can be merged.
https://submitty.org/developer/getting_started/how_to_contribute

**Comment by hasthik** [comment]
Thanks for the help !! **🤝**

**Comment by hasthik** [comment]
shall I close this pr and send a new pr?

**Comment by williamjallen** [comment]
> shall I close this pr and send a new pr?

Shail approved this PR, so there's definitely no need to close it.  The PR title looks fine to me, and seemingly complies with our PR title rules, so I will look into the issue further.

Thanks for this contribution!

**Review by williamjallen — APPROVED** [review]

**Comment by hasthik** [comment]
Thanks for the update. I appreciate your prompt response and approval of the PR. I will keep an eye on it and let you know if there's anything else that needs to be addressed. Thanks again for your support!

**Comment by hasthik** [comment]
How do I get more details on what tests the pr is failing?

**Comment by shailpatels** [comment]
> How do I get more details on what tests the pr is failing?

You can view the result by scrolling down to the bottom of the PR and the list of checks
image

and click on details to see the full output of what the job tried doing and where it failed
sometimes some of our tests are flaky, meaning they may fail when none of your changes caused it and simply rerunning or pulling in main would fix them

**Comment by williamjallen** [comment]
> > How do I get more details on what tests the pr is failing?
> 
> You can view the result by scrolling down to the bottom of the PR and the list of checks 
> and click on details to see the full output of what the job tried doing and where it failed sometimes some of our tests are flaky, meaning they may fail when none of your changes caused it and simply rerunning or pulling in main would fix them

First-time contributors can't run the checks themselves, so they don't necessarily show up.  Each run has to be approved by a member of the Submitty organization.  For example, I've been approving most of the runs for this PR.

As for the original question @hasthik, you can always run the tests locally if you want to verify the results before someone clicks approve on the CI run.  It looks like you are failing one of our e2e tests, which is sometimes rather flaky, so I have re-run the tests.  If the issue persists, you can try running the tests locally as per our docs [here](https://submitty.org/developer/testing/cypress).

**Comment by bmcutler** [comment]
@hasthik 
This is repeatedly failing the e2e tests.  Please debug this locally and update the code and/or tests as necessary.

**Pull request merged**
