### PR TITLE
Installation revision

### PR DESCRIPTION
**Pull request by bmcutler**
This commit is mostly the addition of comments pasted from some of the lengthy manual installation documents (deprecated now with the automated install scripts).  Please help proofread to make sure the comments are well-placed & relevant.

Also in this branch...  I've started moving the "create a bunch of courses" to a separate script.  This will streamline testing of course creation stuff without destroy & re-up of the entire VM.  I'm going to continue working on the add course script...

### CODE REVIEW

**Comment by MasterOdin** [comment]
I think if anything we can to create a generic script that can be passed a course name and semester and it'll create the associated course so that we can just call ```./create_course f15 csci1100```, ```./create_course f15 csci1200```, etc.

**Comment by bmcutler** [comment]
@MasterOdin 
Don't we already have that with the 
https://github.com/Submitty/Submitty/blob/master/bin/create_course.sh ?

See docs here:
https://github.com/Submitty/Submitty/wiki/Course-Creation

or do you mean we should add more to / automate more with that script?
We could add database creation to that script too.

**Comment by bmcutler** [comment]
In this PR I've started work on this script:
https://github.com/Submitty/Submitty/blob/installation_revision/.setup/add_sample_courses.sh
which creates a bunch of sample courses. 

This was ripped out of the install_system.sh script.  It is only run for vagrant installs.

I'm going to fancy it up a bit, make the 3 courses different.  change csci1100 to sample_python_course (or something shorted) and have it only have the python sample assignments.  etc for a c++_course and a java_course.  RIght now all 3 courses each have all of the sample assignments.

I'm also going to break out the chunk of BUILD_csciXXXX.sh that will be autogenerated by the new create/edit new gradeable form.

**Comment by MasterOdin** [comment]
I meant more like a generic script that you would pass in semester and class and it would handle creating all the stuff for the class which I think is:
1. Create group (cscixxxx_tas_www)
2. Create database and fill it
3. Create the course
4. Build the course
etc

as there are numerous repeated things in that file.

Also, you cannot change the name of the courses too significantly at the moment with [these checks in place](https://github.com/Submitty/Submitty/blob/aa72fc2e056ada954d38f93fb9c8fccda652e91c/public/controller/data_functions.php#L782-L786)

**Comment by bmcutler** [comment]
I agree with 2 and 3.  For 1, the group often already exists (and on our department machines, making a group isn't a simple operation, since we want the group to exist on all machines in our dept network).  And for 4, building the course doesn't make sense because there aren't any gradeables yet.  So really we're just talking about adding the database.... Which actually maybe isn't a good idea either since on our system the database is on another machine and needs a different login and different root password.  

But if we're just talking about a script to make the vagrant box....  sure, you could do it all.  Limited utility.

Yes, I'm aware I'll need need to change the validity checks.

**Comment by MasterOdin** [comment]
Well we could accomplish 4 by also allowing to pass in a list of gradeables to be included in the course (coming from the samples directory?)

This current script would only be run on vagrant anyway so the utility of such a script isn't going to be anymore limited than it already. I'd just like to have something extendable so if we decide that we want a fourth class, we can add one line instead of just copying pasting the same half dozen lines (and then having to update any duplicate line multiple times if something changes).

**Comment by bmcutler** [comment]
How about I write a function in the script, ok?

**Comment by bmcutler** [comment]
In addition to the vagrant script, I'm going to use this script as part of the course teardown-rebuild development (2nd section of this page) 
https://github.com/Submitty/Submitty/wiki/Development-Instructions
And developers might modify it while testing.

**Comment by bmcutler** [comment]
@ZishanHuang the latest commit on this branch puts the num_parts and part_names into the config/XX_assignment_config.json file.  (Only if there is >1 part).

**Comment by inlinefan** [comment]
I tweaked a couple of comments in the install_system.sh script, but it looks ok to me.

**Pull request merged**
