### PR TITLE
[Feature:TAGrading] Added Grade Inquiry Title

### LINKED ISSUE #9178: TA Grading 'Grade inquiry' panel does not have a title/label
**Describe the bug**
All the 'panels' available for TA grading have a label/title at the top:

Screen Shot 2023-04-13 at 7 07 48 PM

Screen Shot 2023-04-13 at 7 07 22 PM

Screen Shot 2023-04-13 at 7 07 29 PM

Except the Grade Inquiry panel.  

Screen Shot 2023-04-13 at 7 07 41 PM

**Expected behavior**
Let's give the Grade Inquiry panel a title/label to look like the others.

### PR DESCRIPTION
**Pull request by Suryansh5545**
### What is the current behavior?
Fix #9178   No title on the grade inquiry page

### What is the new behavior?
Added title on grade inquiry page

image

### CODE REVIEW

**Review by yanliw123 — APPROVED** [review]
grade inquiry title added as expected

**Review by mahi-pas — APPROVED** [review]
Works as it should

**Review by yanliw123 — CHANGES_REQUESTED** [review]
Actually, if we have an ongoing grade inquiry, we would have a duplicate "grade inquiry title", As shown in the picture.
image
Can you remove the second one, so we can have only one title with/ without an ongoing grade inquiry.

**Comment by sahil-ansari01** [comment]
Hey can anyone from the chat suggest me resources on how to running submitty locally!

**Comment by Suryansh5545** [comment]
@yanliw123 I have made the changes.

**Review by yanliw123 — APPROVED** [review]
looks good. Thanks for your contribution

**Pull request merged**
