### PR TITLE
[Bugfix:Forum] Fix forum edit history markdown

### LINKED ISSUE #3928: Forum edit history doesn't render markdown
**Describe the bug**
When viewing edit history for a post on the discussion forum, markdown is not rendered. Most likely missing a `| markdown` somewhere.

**Expected behavior**
Markdown should be rendered here. 

**To Reproduce**
1. Go to forum
2. view edit history for a post that has markdown
3. See error

**Screenshots**
exbad

**Additional context**
We recently changed to using markdown for forum posts. Should be a relatively easy fix.

### PR DESCRIPTION
**Pull request by xprilion**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)

### What is the current behavior?
Fixes #3928

### Other information?
Is this a breaking change? - No
How did you test  - e2e

### CODE REVIEW

**Comment by xprilion** [comment]
@andrewaikens87 if you had seen this PR previously, there were changes to 4 files :p but it was getting to complex and eventually I decided to take the safe shortcut, and hence got it done with 3-4 lines of change. Please take a look and probably it will be good to merge quick!

**Comment by andrewaikens87** [comment]
I agree this should be fine, but I am gonna hold off on approval until one small request:

- For the other places that are using the `post_content | markdown` can we have them reference this twig file instead??

**Comment by xprilion** [comment]
@andrewaikens87 that is something I agree should happen. Otherwise it is just redundant cod, which is another reason why I went for the complex route first :smile:

**Comment by andrewaikens87** [comment]
Thanks for updating this. I was planning on approving this, but noticed that there exists some spacing issues for posts now. Are you experiencing this, @xprilion? It doesn't seem to be impacting master.

**Comment by xprilion** [comment]
@andrewaikens87 I do notice the spacing issues. I thought they were solved earlier! (Also some of the refactoring I did in the inline css and js PR has been lost, I've noticed)

**Comment by xprilion** [comment]
@andrewaikens87 got around that spacing. Apparently `span` inside a `pre` was put on a newline (and suffixed by one) which were being rendered as raw due to `pre`!

**Pull request merged**
