### PR TITLE
[Refactor:Developer] PeerFeedback query reformat

### PR DESCRIPTION
**Pull request by ziesski**
Was reviewing some stuff and came across this query. No change, just indentation.

### CODE REVIEW

**Review by NiaHeermance — APPROVED** [review]
Looks better!

**Review by williamjallen — COMMENTED** [review]
Changes look good.  Can you please update the PR title though?  The title currently lacks any sort of information about what query is being updated.

**Comment by ziesski** [comment]
> Changes look good. Can you please update the PR title though? The title currently lacks any sort of information about what query is being updated.

I agree, changed the title.

**Review by ziesski — COMMENTED** [review]
I agree, changed title accordingly

**Pull request merged**
