### PR TITLE
[Bugfix:InstructorUI] Fixed Textbox not displaying

### LINKED ISSUE #7985: Rainbow Grade Customization UI
**Describe the bug**
From instructor UI for a course,
click "Grade Reports"
then "Web-Based Rainbow Grades Generation"
In the "Messages" section, there should be a form text box allowing you to enter messages, but it is not displayed in the message is currently empty.  THIS IS THE BUG

Screen Shot 2022-06-01 at 12 43 56 PM

To hack to make the form box appear...
Press "Save Changes"
(wait for it to generate rainbow grades...  it creates some files in the course folder)
then in your VM, go to the file
/var/local/submitty/courses/s22/sample/rainbow_grades/customization.json
(replace 's22/sample' with whatever course you are using to test)

And edit the messages field to have
    "messages": [ "put something here" ],

Now reload the page and the form box is visible:  

Screen Shot 2022-06-01 at 12 44 43 PM

### PR DESCRIPTION
**Pull request by immortalcodes**
### What is the current behavior?
Closes #7985 
In instructor UI for a course,
Go to`  "Grade Reports"> "Web-Based Rainbow Grades Generation" > "Messages"'`

In the  section, there should be a form text box allowing you to enter messages, but it is not displayed in the message is currently empty. 

### What is the new behavior?
Empty TextBox is displayed allowing you to add and save the message.
### Other information?
Here is the screenshot for same.

image

### CODE REVIEW

**Review by shailpatels — CHANGES_REQUESTED** [review]
Maybe instead of duplicating the textarea the if statement can only wrap the inner part of the tag.

Something like:

```
<textarea id="cust_messages_textarea">
   {% if 0 in messages|keys %}
       {{ messages[0] }}
   {% endif %}
</textarea>
```

**Comment by immortalcodes** [comment]
Yeah! That will be more optimal.

**Comment by bmcutler** [comment]
@shailpatels Please re-review

**Review by shailpatels — APPROVED** [review]
Changes look good and fixes the issue described

**Pull request merged**
