### PR TITLE
[Bugfix] Update URL for sample courses

### PR DESCRIPTION
**Pull request by zjxiaohan**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
The links to courses in the error page are using old-style URLs.
Screenshot from 2019-06-22 19-03-23

### What is the new behavior?
Change to new-style URL.

### Other information?
Run `sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh` to make it update. The error page can be accessed by going to `http://192.168.56.111/index.php?semester=s19&course=development&component=admin` as a student.

### CODE REVIEW

**Comment by sak6lab** [comment]
Also @zjxiaohan out of curiosity, why was it necessary to recreate _sample_course?

**Comment by MasterOdin** [comment]
Because the links on this page (stored in `/usr/local/submitty/site/app/views/current_courses.php`) are only generated as part of setup_sample_courses.py. However, that file should probably be gotten rid of and if anything, the list can be generated on the fly.

**Comment by prestoncarman** [comment]
@MasterOdin Can we make an issue for generating the current courses on the fly?

**Comment by prestoncarman** [comment]
How is this generated page different than issue #1183.

**Comment by zjxiaohan** [comment]
@prestoncarman Thank you for your suggestion. Made an issue #3914 .

**Pull request merged**
