### PR TITLE
[Feature:InstructorUI] New Toggle Column Options

### PR DESCRIPTION
**Pull request by hayeonohh**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
The columns in the Manage Students page is missing columns for additional data we have on students. The only way to view this information is to press the "Edit Student" button for each individual student.

image

### What is the new behavior?
There are five new column options in the Manage Students page when the Toggle Columns button is pressed. When checked off there will be a new column for the additional data showing the information for all students instead of one. The new options are turned off by default.

image
(Image is cut off, you can scroll left/right to see all the columns on the site.)
image

### Other information?
First task in #9848

### CODE REVIEW

**Review by VVVITH — CHANGES_REQUESTED** [review]
I test the columns and the buttons, I works as expected. But as I tested, I find the new added columns are not defaultly checked off(turn on). Which is confilct to your decription. Is the decription wrong or your implement wrong? Please fix it.

**Review by VVVITH — CHANGES_REQUESTED** [review]
The description is now same as you implement. But I find a new problem that the new columns are not center alignment to the title as the columns we have before. I don't think it's very aesthetically pleasing. Could you fix it?
截屏2023-10-31 09 45 50

**Review by VVVITH — APPROVED** [review]
Looks good now!

**Comment by IDzyre** [comment]
The accessibility test is failing because the size of the table is smaller (13) than the amount of columns associated with it (17/18)(according to the test)

**Review by taorif25 — APPROVED** [review]
Code works as expected and successfully closes the first part of the issue. Columns are toggled off by default and correctly display the information with proper formatting. Approved.

**Review by DarthNyan — COMMENTED** [review]
Feature works for me but I have one question. Would it be possible to move the new columns so that the legal names are near the preferred names, the numeric id near the user id, and keeping the edit/delete columns on the far right? The current layout of columns feels a little disorganized to me.

**Comment by bmcutler** [comment]
Updated the original issue to add the feature request suggested by @DarthNyan  to allow the columns to be reordered.

**Pull request merged**
