### PR TITLE
[UI/UX:HelpQueue] Swap Alert Noise to Duck Quack

### PR DESCRIPTION
**Pull request by zacharymnp**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

The current audible alert noise for the discussion forum is two beeps.
As well, the alert noise is stored in base64 in a JavaScript file.

### What is the new behavior?
The audible alert noise has been replaced with Mallard quacks from the following site:
https://orangefreesounds.com/duck-quacking-sound/
License: The sound effect is permitted for non-commercial use under license “Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
The .mp3 has been clipped and background noise has been reduced.

The alert noise is now stored in an mp3 file in a new audio folder.

### CODE REVIEW

**Review by dorian451 — CHANGES_REQUESTED** [review]
Looks pretty good so far. Could you please fix these two things:
1. Stop the notifications from disabling themselves every time the page is reloaded.
2.  The noise gets cut off frequently, which makes it hard to hear.

**Comment by williamjallen** [comment]
Did Barb approve the audio change?  In my opinion, it will quickly become annoying for users who use this feature extensively.  I feel that this change will reduce the professionalism presented by the platform as a whole.

**Review by dorian451 — CHANGES_REQUESTED** [review]
For me, the sound doesn't play at all. I get this error message in the console:
```
notification-sound.js?v=1718895502:18 Failed to play the notification sound:  DOMException: The element has no supported sources.
```
It also still doesn't remember my sound preference if I refresh the page.

**Comment by sahilsuman933** [comment]
`php-lint` CI checks are falling @zacharymnp

**Review by dorian451 — APPROVED** [review]
Seems to work

**Pull request merged**
