### PR TITLE
[UI/UX:Forum] Websockets post ordering

### LINKED ISSUE #5683: Order new posts fetched with websockets
**What problem are you trying to solve with Submitty**
The current behavior of adding new posts fetched with websockets is working only for _"Hierarchical"_ ("tree") option while there exists other options a user can sort viewed posts with including, but not limited to, _Chronological_, _Alphabetical_ and _Alpha by Registration_.

**Describe the way you'd like to solve this problem**
- Check for the cookie **"forum_display_option"** 
- Switch cases for the value of the cookie and add the new fetched post in its correct position, see https://github.com/Submitty/Submitty/blob/master/site/public/js/forum.js#L238

**Additional context**
To enable websockets please check https://submitty.org/sysadmin/version_notes/v20.06.00

### PR DESCRIPTION
**Pull request by ANS1514**
### What is the current behavior?

Posts on the forum would come in with websockets out of order in most ordering selections except for hierarchical. 

### What is the new behavior?
closes #5683
Looks to have posts come in with websockets in the correct ordering based off the forum display option

### Other information?

Tested by adding in posts to a thread with every forum display option and seeing where the websocket would load in the post.

### CODE REVIEW

**Review by AdamTuhacek — COMMENTED** [review]
Works fine in all cases other than chronological descending. It looks like the first post goes to the top and the successive posts go below.

**Review by 04vmatsibekker — COMMENTED** [review]
Sátvik is correct. When a new post in made for someone in hierarchical mode, the change appears in hierarchical mode for all other users in real-time even if their forum post order are not in hierarchical mode.

image

**Comment by 04vmatsibekker** [comment]
Also if create a reply for the first post, it works fine, but if you try to reply to a later post, the problem occurs

**Comment by 04vmatsibekker** [comment]
Now this PR should work again without having to revert prior work

**Review by Youssef-Chip — APPROVED** [review]

**Pull request merged**
