### PR TITLE
[Bugfix:Submission] LATE DAY ERROR

### PR DESCRIPTION
**Pull request by aappppllee**
ISSUE ID : #10963
<h1>What is the current behavior?</h1>
In "Late Day Message" the text message says:
"You have 1 remaining late day for this assignment"

<h1>What is the new behavior</h1>
Now text message says:
"You have 1 remaining late day for future assignments"

### CODE REVIEW

**Review by DarthNyan — APPROVED** [review]
Looks good to me

**Comment by DarthNyan** [comment]
Code looks good, but see the [docs](https://submitty.org/developer/getting_started/make_a_pull_request) on how to title it.

**Review by DarthNyan — CHANGES_REQUESTED** [review]
.

**Comment by aappppllee** [comment]
@DarthNyan I have updated the PR Title according to the documentation. Thank you.

**Comment by ziesski** [comment]
Hi @aappppllee Thanks for contributing. 
The issue is asking to add link as well.  Your current PR is just changing text. 
There is existing PR #10981 that was created earlier than this PR and also adds the link.
So unfortunately, if this PR does not have any technical advantage over #10981, it will be closed.

We encourage you to continue contributing, but next time please check if there is existing PR that already tackles the same issue, and make sure PR addresses all mentioned issues.

**Pull request closed without merging**
