### PR TITLE
[Bugfix:System] Fixes CSV Upload Error

### LINKED ISSUE #9871: Error message when uploading CSV files to the Excused Absence Extension page
**Describe the bug**
When uploading a CSV file on the Excused Absence Extension page, an error message is given. However, the CSV input still modifies the extensions in the expected way.

**Expected behavior**
The CSV should work properly without producing an error message.

**To Reproduce**
1. Go to the Excused Absence Extension Page as an instructor.
2. Upload a CSV file. (see specific csv used below)

**Configuration**
 - OS: windows
 - Browser: edge

**Screenshots**
image

**Additional context**
CSV file used: [CSVnoReason.csv](https://github.com/Submitty/Submitty/files/12861909/CSVnoReason.csv)
Error seems to be produced in line 31 of extensions.js

### PR DESCRIPTION
**Pull request by taorif25**
Closes #9871
### What is the current behavior?
Currently, when uploading a CSV file on the excused absence extension page, an error is given due to invalid json being parsed.
This is due to a deprecated code warning in lateController.php for ini_set("auto_detect_line_endings", true);.
image

### What is the new behavior?
Deprecated code is replaced by manual newline parsing, removing the error.

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
Would PHP's [`fgetcsv`](https://www.php.net/manual/en/function.fgetcsv.php) function be cleaner here?

**Comment by taorif25** [comment]
> Would PHP's [`fgetcsv`](https://www.php.net/manual/en/function.fgetcsv.php) function be cleaner here?



> Would PHP's [`fgetcsv`](https://www.php.net/manual/en/function.fgetcsv.php) function be cleaner here?

I looked into it and it seems that fgetcsv would still have the problem of needing auto_detect_line_endings enabled in order to detect \r line endings. This manual parsing solution allows the detection of all line endings without using deprecated auto_detect_line_endings.

**Comment by taorif25** [comment]
> Could you improve the documentation of Submitty by adding a sample format of the csv file (in https://submitty.org/student/submission/late_days), because I made a file and I am still getting an error

Yeah sure. The csv formatted should also be listed on the excused absence extensions page. It should be in the format of student_id, gradeable_id, days_of_extension. Could you link the file that you used?

**Comment by williamjallen** [comment]
> I looked into it and it seems that fgetcsv would still have the problem of needing auto_detect_line_endings enabled in order to detect \r line endings. This manual parsing solution allows the detection of all line endings without using deprecated auto_detect_line_endings. https://www.php.net/manual/en/function.fgetcsv.php

Seems like reasonable logic to me.  I think the current approach is a good alternative.

**Comment by taorif25** [comment]
> > I looked into it and it seems that fgetcsv would still have the problem of needing auto_detect_line_endings enabled in order to detect \r line endings. This manual parsing solution allows the detection of all line endings without using deprecated auto_detect_line_endings. https://www.php.net/manual/en/function.fgetcsv.php
> 
> Seems like reasonable logic to me. I think the current approach is a good alternative.

Is there anything else I should change or do things look good?

**Review by Youssef-Chip — APPROVED** [review]
I can't manually test this on my machine because the csv upload feature doesn't work on macbook M1 ( I have made #9942 specific to macbook arm chips). However, I think this PR should get merged.

**Review by NiaHeermance — COMMENTED** [review]
Since no one tested functionality, I just went ahead and did so. Error is gone and uploading of csv works!

**Pull request merged**
