### PR TITLE
[Feature:Developer] Label new issues as Awaiting Triage

### PR DESCRIPTION
**Pull request by IDzyre**
### What is the current behavior?

Implements #9934
Submitty has over 400 issues currently, and some of them are from external contributors, so we are unsure if they are still issues, or even reproducible. 

### What is the new behavior?
A Github workflow has been added, so on opening a new issue, the label 'Awaiting Triage' will be added automatically, and a Submitty Org developer will go through and make sure enough information is in the issue, and review the problems.

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
Is there a reason why having an action as opposed to just adding the tag to the default tags in our issue templates is beneficial?

**Comment by IDzyre** [comment]
> Is there a reason why having an action as opposed to just adding the tag to the default tags in our issue templates is beneficial?

I did not realize that there was default tags, so that would be the easier and more efficient option probably...

**Comment by bmcutler** [comment]
If there are default tags, the tag can be removed

**Comment by williamjallen** [comment]
@bmcutler External contributors cannot edit tags.  The ability to modify tags is granted by the "Triage" access level and above.  External contributors also cannot make issues which do not use one of the existing issue templates.  To see what it looks like for people without the Triage access level, take a look at the [PHPStan repository](https://github.com/phpstan/phpstan/issues/new/choose).

**Comment by bmcutler** [comment]
External contributors cannot even choose which of existing set of labels should be applied?  Well that's an unfortunate decision by Github.  Even more reason we need to have someone with access review & correctly label new issues from junior devs and devs outside the organization.

**Comment by williamjallen** [comment]
Contributors who do not have at least the Triage access level cannot add individual tags to their issues, but they can choose from the set of issue templates, which can have default sets of tags.  It doesn't really make sense for Submitty due to our module tagging system, but for something like PHPStan it makes a lot of sense.  PHPStan only has a few categories of issues, and I can't think of many situations where a new contributor would need a set of tags that isn't provided by default.

In addition to being a good motivation for a manual triage step, this is exactly why we should carefully choose our issue templates to appropriately cover the maximum number of cases new contributors might run into.  That's also why I created [this](https://github.com/Submitty/Submitty/pull/9898) PR a few weeks ago.

Should this PR be closed again?

**Pull request closed without merging**
