### PR TITLE
[Feature:System] Variable number of Vagrant Workers

### PR DESCRIPTION
**Pull request by skara9**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Developers can only create one vagrant worker VM at a time, by specifying the `WORKER_PAIR` environment variable on initial vagrant up.

### What is the new behavior?
A variable number of worker VMs can be created by specifying the forwarded SSH ports and private IP addresses of each in the `.vagrant/workers.json` configuration file.

### CODE REVIEW

**Review by 04vmatsibekker — CHANGES_REQUESTED** [review]
image

I get this error on windows 11, after I merge main into the PR.

**Comment by NiaHeermance** [comment]
This is a silly question, but I don't see the workers.json file in the .vagrant directory. Do I need to create the file myself?

**Comment by NiaHeermance** [comment]
Where's that script?

**Review by NiaHeermance — APPROVED** [review]
We had a discussion in person. After the documentation is updated and the typo is fixed, merge time!

**Comment by mahi-pas** [comment]
I set the number of workers to 3 and was able to vagrant up on Ubuntu 22.04. I don't know that much about workers, so if you would like you can fiddle around on my machine and see if it's all good.

**Pull request merged**
