### PR TITLE
[Bugfix:Autograding] Remove CGI for Docker UI

### LINKED ISSUE #6955: Docker UI page doesn't display images that do not exist on the primary machine.
**Describe the bug**
Docker UI page doesn't display images that do not exist on the primary machine.

**Expected behavior**
The page should display any and all images on all worker machines.

**To Reproduce**
1. On a Submitty setup with multiple worker machines, create a new capability only existing to one of the worker.
2. Add a new image that doesn't yet exist in the system to the new capability
3. See that the page does not show the new image

**Configuration**
 - OS: Windows
 - Browser: chrome

### PR DESCRIPTION
**Pull request by HenrikLam**
Closes #6955

### What is the current behavior?
Currently, the page tries to cross reference the cgi results and the json files to make sure the results matches up before displaying the images. However, since only the primary machines run the cgi script, the images that do not exist on the primary machine is not displayed on the page.

### What is the new behavior?
Removed all usage and dependency on the cgi script. This means the table for images to capabilities will lose some columns, however, this can be fixed in the future by logging the docker information onto the log from the worker machine. This will be the first step toward a more scalable solution as the number of worker machines increases.

### Additional Information
#6961 Should be merged before this PR

### CODE REVIEW

**Comment by shailpatels** [comment]
One of the tables appears to be rendered in dark mode, when the rest of the page is in light mode, is this an issue on this branch or would it be resolved merging the other docker UI PR?

image

**Comment by HenrikLam** [comment]
The issue with the table will be resolved once #6961 is merged, I can merge #6961 into this branch if that will help.

**Comment by shailpatels** [comment]
> The issue with the table will be resolved once #6961 is merged, I can merge #6961 into this branch if that will help.

Ok good to know, just wanted to make sure it wasn't a bug introduced

**Comment by bmcutler** [comment]
@HenrikLam 
Just merged your other PR.  Can you please resolve conflicts (looks straightforward, but I'll let you do it)

**Comment by HenrikLam** [comment]
The merge conflict should be resolved now.

**Review by shailpatels — APPROVED** [review]
Looks good

**Pull request merged**
