### PR TITLE
[Refactor: Mobile] Changes across different mobile pages

### PR DESCRIPTION
**Pull request by mukul-kmr-jha**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the new behavior?
- Consistent header across different screen width 
- Student Index page `View-all` fixes
- Same UI for collapsible panels on gradeables and Student Index page
- Separate out the collpasible panel method in different file to keep it clean

### Screenshots
image
image

image

### Other info
This PR is based on [submission mobile page PR](https://github.com/Submitty/Submitty/pull/5432)

### CODE REVIEW

**Comment by bmcutler** [comment]
@mukul-kmr-jha 

Since this PR changes appearance, please add images to document the changes (both before & after).  (please do this for all open and future PRs that change appearance.  Thanks!)

**Comment by mukul-kmr-jha** [comment]
Sure, Thanks!

**Comment by shailpatels** [comment]
@mukul-kmr-jha could you please resolve the merge conflicts - I'm not familiar enough with the changes to fix them myself.

**Comment by bmcutler** [comment]
@mukul-kmr-jha 
Please fix merge conflicts.... thanks!

**Comment by mukul-kmr-jha** [comment]
Need your review on this [comment](https://github.com/Submitty/Submitty/pull/5432#issuecomment-653454472) as I'm little confused about what should be taken in... thanks!

**Pull request merged**
