### PR TITLE
Removed unnecessary files from included libraries in TA Grading Server

### PR DESCRIPTION
**Pull request by TheoBr**
The libraries included in the TA Grading Server were forked into a toolbox folder. In the future, it is best to just include the "min.js" file, and comment the necessary credit where the file is included. This minimizes the amount of traffic moved and cleans up the repo a lot

I didn't deploy this locally, so I'm not sure if this breaks anything. If it does, the issue is likely an include of an uncompressed library (i.e. pickadate.js instead of pickadate.min.js)

### CODE REVIEW

**Comment by MasterOdin** [comment]
We at least want to keep the MIT license file for both pickdate and codemirror libraries in the root of the folder.

**Comment by TheoBr** [comment]
@MasterOdin Usually it's best to list all of the open source attributions in a single license file, or even just link the repo in a comment above where the libraries are included. Including the separate license files for each project is not typical

**Comment by MasterOdin** [comment]
So in looking this over, I'm not even sure we actually even need pickadate at all anymore (as we moved to jquery-ui-timepicker-addon.js instead as pickadate had only date or time pickers, and not a combined one. So that whole library should be removed.

> Including the separate license files for each project is not typical
I wouldn't call it "not typical" consider that's how all node and composer based projects work, not to mention Chromium. I also plan to move to a different setup for these JS requirements anyway (#773) I'd prefer just leaving the current setup (license in the folder) for now.

**Comment by MasterOdin** [comment]
But I would say I don't particularly care how we include third party licenses, just that we need to so please choose a strategy (either all licenses in one file or per directory) and I'll merge this.

**Comment by TheoBr** [comment]
I'm not a core contributor to this project, and I don't think it's my place to determine the way you guys handle attributions. All I know is that I trimmed 17,000 lines of code and everything seems to work still.

When I was hunting through the code base, I was unable to find any instance where PickADate was used. I left the min.js due to lack of confidence in my knowledge of this project.

I can tidy up this PR if a method for open source attributions/credits is determined, and I'll happily discuss this with current maintainers of the project. I'm equally willing to drop this PR entirely and let someone closer to the code base handle it.

Let me know how you wish to proceed!

**Comment by MasterOdin** [comment]
So just killing off the one remaining min.js file for pickadate is fine and you should do that and I'll accept this pull request. I've also opened #774 which should resolve this debate (as it turns out several libraries in cdnjs.com don't have their license terms in their headers so better be safe and just explicitly do have them than be sorry later).

**Comment by TheoBr** [comment]
Just removed the rest of pickadate

**Pull request merged**
