### PR TITLE
Fixed multi part and other improvements

### PR DESCRIPTION
**Pull request by ZishanHuang**
1. Code now gets num_parts and part_names from assignment config.
2. Changed error messages for assignment being late, within/exceed max late days allowed.

#394 #61

### CODE REVIEW

**Comment by ZishanHuang** [comment]
BTW, where is the max # of late days allowed being stored? @bmcutler

**Comment by bmcutler** [comment]
It's stored only in the database currently.  
Why don't you hard code it to 2 late days for right now.  Put a big comment next to that setting in the code, and make a new issue -- when it's saved/stored to a json file we'll replace it.

**Comment by ZishanHuang** [comment]
Yes it is already hard coded as 2 in the commit.

**Comment by ZishanHuang** [comment]
Added alerts for changing active version after max late days allowed and other improvements.
#61

**Comment by bmcutler** [comment]
looks good!

**Pull request merged**
