### PR TITLE
[Feature:TAGrading] Prev/next student by (active) inquiry

### LINKED ISSUE #4765: "Go to next grade inquiry"
**What problem are you trying to solve with Submitty**
A ta/instructor has a half dozen grade inquiries to resolve...
they click to open the first one, resolve it...  would be nice to have a "next" that will skip through the students until the next unresolved inquiry.

### PR DESCRIPTION
**Pull request by DefinitiveAbove**
### What is the current behavior?
No prev/next inquiry option for switching between students in TA grading.

### What is the new behavior?
Closes #4765 
Prev/next inquiry and active inquiry options added for switching between students in TA grading.
If a component is open, the prev/next student for inquiries is found based on the component id (searches for unlinked regrade requests and regrade requests with the specified component id). Otherwise, it will just find the prev/next student with a grade inquiry.
Refactored filtering to make it easier to add more filters in the future.

### CODE REVIEW

**Comment by HenrikLam** [comment]
I am not sure on where do I access this filter.

**Comment by DefinitiveAbove** [comment]
> I am not sure on where do I access this filter.

You can find it in the TA grading settings (Wrench icon when grading a student) and it is at the top of the settings next to the "Prev/Next student arrow functionality" label.

**Review by HenrikLam — APPROVED** [review]
Both active inquiries and any inquiries fiters work.

**Review by loadedskiffer — APPROVED** [review]
Could not break prev/next student for inquiries, code looks good.

**Pull request merged**
