### PR TITLE
[Bugfix:TAGrading] Fix error when loading pdfs from non-root submissions folders

### LINKED ISSUE #2622: PDF Annotation supports subfolders within submission folder
Currently, the annotator only supports PDF submissions with no subfolder. If, however, a gradeable has multiple sections, the pdf annotation cannot save and read annotations.

### LINKED ISSUE #5023: Clicking the +/- zoom buttons when grading a pdf does not work
**Describe the bug**
When you click +/- buttons to zoom in on a pdf it gives an error
image
It does work if you refresh the page after though

**Expected behavior**

No error it should just zoom in with no page refresh

**To Reproduce**
1. Open an exam with a pdf
2. click the +/- button

**Configuration**
 - OS: [e.g. Windows, Linux, ...]
Arch Linux Firefox

**Screenshots**
image

### PR DESCRIPTION
**Pull request by MasterOdin**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?

Closes #2622
Closes #5023

Fixes error when attempting to load PDFs for annotation when the PDFs were submitted via VCS or when within a sub-folder for regular submission. This was due to the code hard-coding the directory to top-level `submissions` folder when attempting to load the PDFs.

### What is the new behavior?

PDFs load as expected and can be annotated. As a side-effect of wiring the new changes up to the function signature, it looks like I fixed the zoom/rotation bug that existed before this PR.

### Other information?

Tested opening PDFs and annotating them when PDFs were submitted by both VCS as well as regular file upload.

### CODE REVIEW

**Comment by bmcutler** [comment]
This doesn't seem to have fixed it. 
I tested on both MacChrome & MacFirefox.
If it matters the pdf is in a subdirectory of the checkout folder:  checkout/answers/foo.pdf

Screen Shot 2020-02-06 at 12 49 11 AM

**Comment by MasterOdin** [comment]
Yeah, subfolders would break loading PDFs whether they were uploaded via file upload or VCS. Back to the proverbial drawing board once more to do even more rewriting of how this works.

**Comment by jchulton** [comment]
Whelp I did some testing: not too much to add except this doesn't seem browser specific (breaks on chrome and firefox). The error seems to happen somewhere in either encodePDF in MiscController.php or in PDFAnnotateEmbeded.js, but that's just the pdf rendering chain so that's unsurprising

**Comment by MasterOdin** [comment]
So fixed the errors above with subfolders. There remains a bug where if you have a PDF in a subfolder with the same name as a PDF elsewhere in that submission, the annotations will collide. Fixing that (and #4779) will be done in a different PR as it requires overhauling some other parts of it, as well as writing a migration, which I'd rather have this in sooner so at least Konstantin can grade.

**Pull request merged**
