### PR TITLE
[MobileUI: TaGrading] Adds Mobile UI for the TA Grading page

### PR DESCRIPTION
**Pull request by mukul-kmr-jha**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the new behavior?
- Made Ta grading page mobile compatible.
- Removed scrolling from Nav-toolbar like grading panel header
- Removed combined student nav buttons
- Hides some of the buttons on smaller screen width

### Screenshots
image

### Other information?
Some of the features like two-panel-mode, full-left-column, and exchange panels are not given on the mobile and are reserved for bigger screen devices only.
This PR is based on the [Ta-grading-redesign PR](https://github.com/Submitty/Submitty/pull/5543)

### CODE REVIEW

**Comment by bmcutler** [comment]
@mukul-kmr-jha 
Please include screenshots from default/light mode as well.

**Comment by Kevin-MM** [comment]
Hi @mukul-kmr-jha , can you get the tests and merge conflicts addressed and then I will review.

**Comment by mukul-kmr-jha** [comment]
Hii @Kevin-MM , please take a look, thanks!

**Comment by mukul-kmr-jha** [comment]
Hii Kevin, added the autograding result fix, please take another round, thanks!

**Comment by bmcutler** [comment]
@mukul-kmr-jha 
Not surprising...  we have merge conflicts.
Please resolve so we can do a quick test & merge
Thanks :)

**Comment by mukul-kmr-jha** [comment]
haha... it was relatively easier to fix than previous ones, please take another look, thanks!

**Pull request merged**
