### PR TITLE
[Refactor:System] Refactor beginning_of_time of time

### PR DESCRIPTION
**Pull request by williamlin6803**
Fix that

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

Fixes https://github.com/Submitty/Submitty/issues/10334 issue

Just changes the variable names for this from one to the other

### CODE REVIEW

**Comment by Kush-Raval** [comment]
This will have to hold off until https://github.com/Submitty/Submitty/pull/10184 gets merged because the PR also uses Dateutils.

**Review by Kush-Raval — APPROVED** [review]
Fixes spelling errors and replaces errors in relevant files.
Refer to previous comment before it gets merged

**Review by ArnavPawar — APPROVED** [review]
looks good just refactored code

**Review by arougey — APPROVED** [review]
simple change small spelling error looks good

**Review by sadam-04 — APPROVED** [review]
Just renaming a variable, looks good to me

**Comment by williamjallen** [comment]
I just switched this to the "Work in Progress" status since it is blocked by https://github.com/Submitty/Submitty/pull/10184.  Please add it back to the "Awaiting Maintainer Review" column once https://github.com/Submitty/Submitty/pull/10184 is merged.

Additionally, the PR description is somewhat lacking.  Can you please fill it out a bit?  The PR description is very important because it summarizes the changes being made, without leaving the reader to have to dive into the code to figure out what actually changed.

**Review by williamjallen — APPROVED** [review]
Good to merge if tests pass.

**Pull request merged**
