### PR TITLE
add seeking team/partner feature for team assignments

### LINKED ISSUE #1790: Forming Teams
Right now, students need to know the username of another student to create and form a team.
(We intentionally do not allow list all/search/name completion because of FERPA concerns).

We'd like to let students advertise themselves as "seeking partner/team" for this gradeable.  This option should be added to the create team page.  The names & emails would appear on other students pages when they go to form teams. 

This will probably involve an addition to the database, design discussion needed.

### PR DESCRIPTION
**Pull request by tushargr**
Closes #1790 
following is video link for my deployment have seek team/partner feature
https://drive.google.com/file/d/15vV4xBwZFe2qE3bzCqWDR22pq0uqeUvc/view?usp=sharing

### CODE REVIEW

**Comment by bmcutler** [comment]
Hi Tushar

Nice work.  I'd like to request some changes in the UI.  We'll probably also have some changes to request in the code.  (And we'll need to add code to update existing courses since there are database changes).

UI change requests first:  

Let's not have the popup window or the "users seeking team/partner" button, it's unnecessary clutter, we've got alot of empty space on the manage team space.  If there are users who are seeking a team, let's add a third grey div/box beneath the invitation box.  In the new box, let's list more information about each user: preferred first name, last name, username, and email address.  

If the current user has put their own name on the list to seek a team/partner, they should have a button to remove their name from the list.  (Making a team and leaving the team is awkward workaround to do that -- and it clutters the team namespace with a dead team name).

I'll probably have more comments on the wording of the UI later.

Barb

**Comment by tushargr** [comment]
Hi @emaicus i will be soon making a commit for UI changes as suggested by bmcutler.

**Comment by tushargr** [comment]
Sorry by mistake I closed the PR

**Comment by bmcutler** [comment]
Small UI nitpick...  Can you switch "Username" in the list of those seeking to be "User ID" to be consistent with the terms used elsewhere on the page.
Thanks

More significantly, before we merge this we need to modifying .setup/update_database.py to migrate existing databases to add the new table/constraints.  (And yes @MasterOdin wants us to switch to a different method for migrating databases...  #1655 but we're not there yet)

Also, I would like @MasterOdin to review the DB changes.

**Pull request merged**
