### PR TITLE
[Feature:RainbowGrades] automatic grade summary generation

### PR DESCRIPTION
**Pull request by Kevin-MM**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant

### What is the current behavior?
Before the web-based rainbow grades ui could generate rainbow grades you had to manually generate grade summaries

### What is the new behavior?
Pressing the save button on the rainbow grades web-based ui form will now automatically generate grade summaries and rainbow grades as long as instructor level credentials have been provided.

### To Test
- First ensure the [jobs daemon is running](https://submitty.org/developer/jobs_daemon) by calling ```sudo systemctl start submitty_daemon_jobs_handler``` prior to running the submitty install script
- Ensure the RainbowGrades repo is cloned in your GIT_CHECKOUT directory
- Modify ```/usr/local/submitty/config/submitty_admin.json``` to provide instructor level credentials, for example instructor/instructor on a regular vagrant development installation
- Log into the 'sample'
- Press the grade reports button
- Press the 'Web-Based Rainbow Grades Generation' button
- Play with the new customization user interface, saving the form when satisfied
- Check out the results in the 'Rainbow Grades' tab (must be enabled inside the course configuration page)

### Other info
- In the event that no credentials or bad credentials are provided the web-ui will still work as normal provided grade summaries have been manually generated.

### Other information?
Tested manually

### Other Other Information?
Credit to @zjxiaohan for his contribution of generate_grade_summaries.py

### CODE REVIEW

**Comment by zjxiaohan** [comment]
Do we need to create `customization.json` manually? It's my first time running it and it's saying 

Warning: file_put_contents(/var/local/submitty/courses/f19/sample/rainbow_grades/customization.json): failed to open stream: No such file or directory in /usr/local/submitty/site/app/models/RainbowCustomizationJSON.php on line 279

**Comment by Kevin-MM** [comment]
@zjxiaohan No you shouldn't have to that is the job of the ui.  I'll have to investigate why this is happening.

**Comment by Kevin-MM** [comment]
Did you run the submitty install script after checking out the branch?

**Comment by zjxiaohan** [comment]
Yes, I ran `sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh` after checking out.

There doesn't even seem to be `rainbow_grades` directory. I re-ran the migration manually (`rollback` and `migrate`) and they turn out to be fine. I don't know why it wasn't handled in the installation script though.

**Comment by zjxiaohan** [comment]
I tried to generate it, but there are some errors in the log.
Maybe some access control thing?
Screenshot from 2019-07-20 11-01-40

**Comment by zjxiaohan** [comment]
I ran `sudo bash /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/recreate_sample_courses.sh` again and there is no `customization.json` generated.

**Comment by Kevin-MM** [comment]
Thank you for these messages @zjxiaohan .  Did you check out [rainbow grades](https://github.com/Submitty/RainbowGrades)?  If it is checked out then there must be a permission error.  How did you check it out?  I think you need to vagrant halt, checkout on host machine, then vagrant up.

**Comment by zjxiaohan** [comment]
oops. I didn't check that out. Now I do, and re-installed submitty but there still seems to be permission problems. May be a problem on my side. I'll try again after doing a sample course recreation.

**Comment by Kevin-MM** [comment]
Thanks @zjxiaohan .  You were correct in not understanding why it wasn't run by the installation script.  I never added that part, so the only way to create the directory was with the migration.  I am going back to fix that now.

**Comment by zjxiaohan** [comment]
Wait, I thought the installation script runs migrations?! So `sudo /usr/local/submitty/.setup/INSTALL_SUBMITTY.sh` never runs migration?! :sweat_smile:

**Comment by Kevin-MM** [comment]
I think it only runs new migrations, not exactly sure what happened here.

**Comment by thef1stofhername** [comment]
So everything works fine for me until the end, where  I enable rainbow grades to view. I create them and save the form and then it says there's no grades to show. I fun the daemon, I have the rainbow grades, changed the json, logged in, went to sample, went to grade reports, went to web-based, made the grades how I wanted, saved, turned on rainbow grades, checked them, and there are no grades available. Did I miss anything?

**Comment by Kevin-MM** [comment]
@thef1stofhername Does the web-form say that they were generated successfully?  What is the output of ```/var/local/submitty/courses/f19/sample/rainbow_grades/auto_debug_output.txt```

**Comment by Kevin-MM** [comment]
I've added a button that displays the contents of the debug log to the browser window.  This should hopefully make it easier to debug while testing

**Comment by Kevin-MM** [comment]
I've corrected the (second) linting error.  Apologies about that.  I think this PR is ready to go.  It should be noted that if the user doesn't have the rainbow grades repo checked out then the install_submitty script will provision it automatically, but the permissions will be off.  The RainbowGrades directory needs 775, while the files inside need 664.  I'll look into this more.

**Pull request merged**
