### PR TITLE
[Bugfix:Submission] Fixing Buggy Late Day Message Text

### LINKED ISSUE #10963: buggy late day message text
**Describe the bug**
Screenshot 2024-09-19 at 6 53 26 PM
that message is ok.

but this other message is not ok:
Screenshot 2024-09-19 at 7 06 12 PM

The assignment allows students to use 1 late day.
My user has 2 late days available.

I believe that last sentence should  not say "You have 1 remaining late day for this assignment"
And it should instead say 
"You have 1 remaining late day for future assignments"

EDIT TO ADD:

While we are in here editing this message.  Let's add a link...
For more information, see your complete "My Late Days / Extensions" page, which points to the link also available from the  left sidebar on the bottom.

### PR DESCRIPTION
**Pull request by ryvaru**
### What is the current behavior?
Closes #10963 

The late day messages currently do not display a link to the "My Late Days / Extensions" page and says "You have 1 remaining late day for this assignment" instead of for future assignments.

### What is the new behavior?

The code fixes the above behavior:
image

In the image above, the instructor makes a gradeable that has a limit of 3 late days allowed. The student uses one late day, and the code now displays that the student has two more late days remaining for that same assignment. Also, it displays a link at the bottom to the 'My Late Days / Extensions' page.

### Other information?
To test, make or go to a late gradeable, and check if the above changes have been made correctly.

### CODE REVIEW

**Review by Kush-Raval — APPROVED** [review]
The code change makes sense, I functionality-tested this and the correct response came up. Also, the link correctly links to the desired URL path.

**Review by ZheyuDeng — APPROVED** [review]
Looks good to merge to me have put this into maintainer review.

**Review by Kush-Raval — APPROVED** [review]
Code change makes sense, now the new message shows how many late days can be used for the current gradeable.

**Review by lavalleeale — APPROVED** [review]
Looks good to me, the new language is more understandable for students.

**Review by williamjallen — APPROVED** [review]
Moving this to "ready to merge"...

**Pull request merged**
