### PR TITLE
[Feature:System] superuser view all gradeables

### LINKED ISSUE #5203: Assignment status page for superusers
**What problem are you trying to solve with Submitty**
If the system administrator wants to do maintenance on the machine (e.g., reboot, install an update to the Submitty software etc) that is going to involve a short outage, they would like to pick a good time to do that.  Different courses have different assignment deadlines, or TA grading deadlines, and it can be impractical to keep track of everything, or poll instructors & tas for a good time.

**Describe the way you'd like to solve this problem**
Let's add a new webpage for superusers, "assignment status", that lists
all assignments that are open for student submission, and all assignments that are open for TA grading.  Assignments with submission deadlines or TA grading deadlines today or within the next hour or two should be specially highlighted.  

As a future extension, we could also have some information here about the average length of time to autograde each submission, how many student have or need to submit, fraction of the ta grading completed for each assignment in the open for grading category, etc.

Some if the information about recent autograding submissions / wait time / time to completion, etc. would be nice for students to view.    Related to issue #5202

**Additional context**
Much of this information can be quickly grabbed from each course database, but there is a concern opening connections too many separate databases.  Currently we have ~22 unarchived courses (the current term plus a few holdover courses from past terms).  Will producing this page be too expensive?  Should we somehow cache this data, or generate this data via an infrequent cron job, etc?

Let's design a prototype of the page first, then we can decide if we want to optimize the gathering of the data for the page.

### PR DESCRIPTION
**Pull request by MasterOdin**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Closes #5203. There is currently no good way to view all gradeables in the system for a Sysadmin who might be looking to do system maintenance without affecting any courses.

### What is the new behavior?

Adds a new superuser page that shows all gradeables for all non-archived courses.

Screenshot 2020-05-04 19 18 35

Screenshot 2020-05-04 19 28 55

Currently the displayed information is minimal, and per the issue, can be expanded later. None of the buttons are links as I'm not sure there's any value to that, and the button design is just to add a bit of contrast there.

### CODE REVIEW

**Comment by MasterOdin** [comment]
Design notes from @bmcutler:

* Condense the view to display more information more readily (no buttons for dates, use normal data table)
* Display the semester / course in each row
* Only show open gradeables and gradeables currently being graded

**Comment by MasterOdin** [comment]
Updated view of the page:
Screen Shot 2020-07-31 at 1 02 46 PM

Screen Shot 2020-07-31 at 1 02 51 PM

Per the feedback, it now only shows gradeables that are open for submission and open for grading, in reverse order of the regular gradeables page (sooner deadlines are at the top).

**Comment by bmcutler** [comment]
@jhulton please review and run all access tests (e2e & otherwise) and make sure the functionality & code changes don't conflict with recently merged PRs.

**Review by jchulton — DISMISSED** [review]
As above

**Comment by bmcutler** [comment]
looks great!

**Pull request merged**
