### PR TITLE
Allow mentors to edit posts

### PR DESCRIPTION
**Pull request by shwehtom89**
Mentors are now allowed to edit posts and mark threads as unresolved. Should mentors be allowed to alter posts made by instructors?

### CODE REVIEW

**Comment by bmcutler** [comment]
yes, mentors can edit any post.  we have the full edit history should it be necessary.

**Comment by shwehtom89** [comment]
Changes added. Now mentors can edit posts, change the thread status, add/delete thread categories and alter announcements.
announcement
edit_posts
Logged in as Tim Grader up above.

**Comment by andrewaikens87** [comment]
@bmcutler I don't remember if this was discussed but should mentors have the ability to add/delete thread categories and alter announcements?

**Comment by shwehtom89** [comment]
## List of things mentors should now be able to do
- toggle thread status (resolve/unresolve)
- toggle thread categories
- create/delete/edit/reorder thread categories
- edit threads and post content (including TA/instructor)
- delete/undelete posts/threads
- show deleted threads
- show merged threads
- merge threads
- show stats page
- show post history
- toggle display options (chrono, alpha, hierarchical)

## List of things mentors should __NOT__ be able to do
- reveal anonymous user
- get student's email
- toggle announcement

**Pull request merged**
