### PR TITLE
[Feature:RainbowGrades] Add Gradeable Percents to GUI

### PR DESCRIPTION
**Pull request by zacharymnp**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.

### What is the new behavior?
Added a checkbox labeled _Per Gradeable Percents_ under the Gradeables configuration, that adds textboxes for percents for each gradeable. This allows final grade percent configuration per gradeable in the RainbowGrades GUI.

image

### CODE REVIEW

**Review by oliiso — CHANGES_REQUESTED** [review]
This is a good start, two ideas to improve it:
- Adding a reset button to put the percentages back to having an equally divided weight, maybe something like a redo arrow in front of the checkbox of per gradeable percents.
- I was able to add amounts that total over 100% for the category. Putting a check for that would be a nice addition. It can be set up similarly to the warning triangles that show up when editing the point amounts and text appears when hovering over them, or just as a notice/warning near the top that the total for percent per gradeable amounts are over/under 100%.
Image 7-30-24 at 3 50 PM

**Comment by zacharymnp** [comment]
I added a clamp solely for over 100, because values under 100 get scaled to 100 anyway. I am unsure about clamp vs warning icon, since the clamp as I implemented it seems like it might be irritating for users but the warning icon may be ignored.

**Comment by oliiso** [comment]
The even split button is great.
But adding the clamp made it so that you cant set a higher percent than the percent of the even split. It automatically gives the warning of it being over 100 and resets it back to the even split number. I think adding a warning icon or just setting it back to having no clamp or warning might be more useful.

**Review by oliiso — APPROVED** [review]
Looks good, requested changes were updated.

**Review by williamjallen — APPROVED** [review]
Code looks reasonable to me, but I'm going to put this in "In Review" until @ziesski reviews.

**Review by ziesski — APPROVED** [review]
Tested, reviewed looks good.

**Review by bmcutler — APPROVED** [review]
quick test of UI looks good :)

**Pull request merged**
