### PR TITLE
[Testing:TAGrading] Download Zip File

### LINKED ISSUE #10601: When downloading a student's code as a ZIP file, their RCSID is exposed
**Describe the bug**

When downloading a student's code as a ZIP file, I'm pretty sure their RCSID is exposed.

**Expected behavior**

Some sort of anonymous file name

**To Reproduce**
1. go to any grading portal
2. select "download zip file"
3. the file name will be `assignementName_RCSID_version`

**Configuration**
 - OS: Fedora Spin Sway
 - Browser Librewolf

**Screenshots**

I would rather not, as I don't want to expose any student's RCSID and I'm not part of the class (just a mentor)

**Additional context**

### PR DESCRIPTION
**Pull request by manzil-infinity180**
### Please check if the PR fulfills these requirements:
Closes #10601

* [x] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

When we download the zip file , 
the file name will be like this `assignementName_RCSID_version `and we do not want to exposed any kind of student details

### What is the new behavior?
new file name - `grading_homework_hG1b13ljpDjKu32_v1.zip` (**assignementName_anonId_version**)
And no test existed so added test for  download zip file button 

**Concerned about should we need to test the content of zip file ?? Difficult to do that**

### CODE REVIEW

**Review by IDzyre — COMMENTED** [review]
The test works, however I think the test could test more (either in this PR or a future PR). 

I will leave final approval to Barb, as I am not sure about the functionality and non-testing changes in this PR.

**Comment by IDzyre** [comment]
Could you add where the download zip file button is? There are many of them, so adding which of the buttons would be nice.

**Review by IDzyre — APPROVED** [review]
After discussion in the meeting, this is an okay change, just force everyone to view anonymous IDs. Will leave for Barb to merge and final approve.

**Review by williamjallen — APPROVED** [review]
Code seems reasonable to me.

**Review by ziesski — APPROVED** [review]
code looks good to me. One thought I had is reversing the if statement, instead of checking if the user is in student group, how about checking if user is in instructor group. 

So everyone other than instructor access would get anonymous file. I think it would carry the benefit of bulk download and sort, for instructor. But current implementation is what we decided during discussion.

**Pull request merged**
