### PR TITLE
[Refactor:Autograding] Logger refactor

### PR DESCRIPTION
**Pull request by hdrodz97**
### Please check if the PR fulfills these requirements:

* [X] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [X] Tests for the changes have been added/updated (if possible)
* [X] Documentation has been updated/added if relevant

### What is the current behavior?

Currently, the logging functions `log_message` and `log_stack_trace` are independent functions in the `autograding_utils` package that require specifying the log path every time.

### What is the new behavior?

A new `Logger` class is created and is attached to the `Config` object, which remembers the autograding log and stack traces directory, as well as a default `job_id` parameter (set to the `JOB_ID` constant set in `submitty_autograding_shipper.py` and `submitty_autograding_worker.py`, as this value is frequently used there). Furthermore, the signature for these functions was slightly tweaked so the message/stack trace can be used alone, and any other extra parameters must be provided as keyword arguments (in order to make it clear what's what in the function parameter list without having to open the function definition). Additionally, the function signature for `log_stack_trace` has had all unused/irrelevant parameters removed (it was originally a carbon copy of `log_message`).

Finally, the `log_stack_trace` function now accumulates the parameters sent to it if `capture_traces` is set to `True` when the `Logger` is created. This is primarily for the autograding worker to be able to send any stack traces encountered during grading back to the primary machine.

### CODE REVIEW

**Review by emaicus — CHANGES_REQUESTED** [review]
Very close to ready! Right now, it looks like local errors in the worker are being triple logged.

To reproduce, just raise an error in the worker on line 77.

Here is the resulting log output:
logs/autograding:
```
2021-01-18 12:19:45.278-0500 | ~WORK~ |       |             |                                                                             |                      | ERROR attempting to unzip graded item: localhost untrusted03. for more details, see traces entry.
2021-01-18 12:19:45.930-0500 | ~SHIP~ |       |             |                                                                             |                      | NOTE: Job s21/development/submissions/cpp_cats/instructor/2 has stack trace messages. Check the stack traces log for details.
2021-01-18 12:19:45.930-0500 | ~SHIP~ |       |             | s21/development/submissions/cpp_cats/instructor/2                           |                      | ERROR: failure returned by vagrant.vm_localhost_untrusted03. View stack traces for more info
2021-01-18 12:19:45.933-0500 | ~SHIP~ |       |             | s21/development/submissions/cpp_cats/instructor/2                           |                      | ERROR: Exception when unpacking results zip. For more details, see traces entry.
root@vagrant:/var/local/submitty/logs# cat autograding_stack_traces/20210118.txt 
2021-01-18 12:19:45.280-0500 | ~WORK~ |       |            
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_worker.py", line 77, in worker_process
    i = 10 / 0
ZeroDivisionError: division by zero


2021-01-18 12:19:45.930-0500 | ~WORK~ |       |            
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_worker.py", line 77, in worker_process
    i = 10 / 0
ZeroDivisionError: division by zero


2021-01-18 12:19:45.931-0500 | ~SHIP~ |       |            
ERROR: vagrant.vm_localhost_untrusted03 returned the following error:
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_worker.py", line 77, in worker_process
    i = 10 / 0
ZeroDivisionError: division by zero


2021-01-18 12:19:45.933-0500 | ~SHIP~ |       |            
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_shipper.py", line 587, in unpack_job
    config, which_machine, which_untrusted, local_results_zip
  File "/usr/local/submitty/autograder/autograder/packer_unpacker.py", line 331, in unpack_grading_results_zip
    queue_obj = unzip_queue_file(my_results_zip_file)
  File "/usr/local/submitty/autograder/autograder/packer_unpacker.py", line 89, in unzip_queue_file
    raise RuntimeError("ERROR: zip file does not contain queue file", zipfilename)
RuntimeError: ('ERROR: zip file does not contain queue file', '/tmp/tmp95ikabe0')
```

logs/autograding_stack_traces
```
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_worker.py", line 77, in worker_process
    i = 10 / 0
ZeroDivisionError: division by zero


2021-01-18 12:19:45.930-0500 | ~WORK~ |       |            
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_worker.py", line 77, in worker_process
    i = 10 / 0
ZeroDivisionError: division by zero


2021-01-18 12:19:45.931-0500 | ~SHIP~ |       |            
ERROR: vagrant.vm_localhost_untrusted03 returned the following error:
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_worker.py", line 77, in worker_process
    i = 10 / 0
ZeroDivisionError: division by zero


2021-01-18 12:19:45.933-0500 | ~SHIP~ |       |            
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_shipper.py", line 587, in unpack_job
    config, which_machine, which_untrusted, local_results_zip
  File "/usr/local/submitty/autograder/autograder/packer_unpacker.py", line 331, in unpack_grading_results_zip
    queue_obj = unzip_queue_file(my_results_zip_file)
  File "/usr/local/submitty/autograder/autograder/packer_unpacker.py", line 89, in unzip_queue_file
    raise RuntimeError("ERROR: zip file does not contain queue file", zipfilename)
RuntimeError: ('ERROR: zip file does not contain queue file', '/tmp/tmp95ikabe0')
```

**Comment by hdrodz97** [comment]
@emaicus (no clue why, but I can't seem to figure out how to respond to your earlier comment) So after poking around, I figured this one out: the first error print is the worker printing locally, the second error print is the shipper reproducing the error as-is from the worker, and the third error print is comes from including the stack trace in the worker response if an exception happens there: https://github.com/Submitty/Submitty/blob/bdd07985f4810b637b16ec939794bca7c55c8771/autograder/submitty_autograding_worker.py#L85-L108

The logger logs it to the worker's local stack trace error file (i.e. the first print) and places the same traceback in the response object, which the shipper echoes when it sees that the response object doesn't have a `success` status. I'm thinking it might make sense to drop the printing of the worker response status message from the shipper since it's gonna get printed by the worker log replay anyway. Thoughts?

**Review by emaicus — CHANGES_REQUESTED** [review]
One last question and then I think we're good to go. The `Job:` field in the stack trace log looks like it may always be the empty string, can you have a quick look into that? Also, I agree with your above comment, let's drop the extra logging.

**Comment by hdrodz97** [comment]
Regarding the blank `Job:` field, it shows up as empty if you force a crash within `submitty_autograding_worker.py` in `worker_process` because the `except:` block as-written does not have a `jobname` entry assigned. It does work as expected if you force a crash in the `archive()` function `grade_item.py`, as a `jobname` is available then.

One way to get around this is to open up the queue file in the `except` branch and pull the job name from the queue file, falling back to some `UNKNOWN`-type constant if we're unable to open or parse the queue file for whatever reason, though this feels a bit messy.

**Comment by bmcutler** [comment]
Evan approved during today's meeting.

**Pull request merged**
