### PR TITLE
[Bugfix:TAGrading] Fix view of user_assignment_settings

### PR DESCRIPTION
**Pull request by wuj18**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently, one cannot view the `user_assignment_settings.json` file from the grading interface, even with Instructor permissions. Attempting to do so shows a permissions error:
image

This functionality was broken in https://github.com/Submitty/Submitty/pull/10406.

### What is the new behavior?
With this change it is once again possible to view `user_assignment_settings.json`.
image

### CODE REVIEW

**Review by justin-sadakhom — COMMENTED** [review]
@wuj18 What is the purpose of this pull request? Can you fill in the PR template so we know why the change is being made?

**Comment by skara9** [comment]
Seems to be reverting an unintentional code change made in #10406, which breaks some functionality.
This should be mentioned in the PR body.

**Comment by powe97** [comment]
I've updated the body and title of this pull request to be more descriptive.

**Review by powe97 — APPROVED** [review]

**Review by williamjallen — APPROVED** [review]
Thanks for updating the description for this @powe97!  In the future, please also link any relevant work in the PR description so future developers can follow the entire trail of PRs.  I just edited the description to include the PR # which broke this.

**Pull request merged**
