### PR TITLE
Translate Profile Page

### PR DESCRIPTION
**Pull request by skara9**
PR to demonstrate localization feature.

Languages Supported:
- [x] English US

---

To add a translation:
- Create a copy of `site/lang/en_US.json` and name it based on the CLDR locale you want to write a translation for
- Update each of the JSON values to the translated text and save the file

To test the translation:
- Inside the VM, edit the file `/usr/local/submitty/config/submitty.json`, adding the key:
  
  ```json
  "default_locale": "en_US"
  ```
  (replace `en_US` with your locale)

### CODE REVIEW

**Review by shailpatels — COMMENTED** [review]
You may want to take a look at how other projects implement translation and localisation,

Here's a symphony library approach will also supports twig
https://symfony.com/doc/current/translation.html

**Comment by 04vmatsibekker** [comment]
can you show an example of how to translate the page

**Comment by 04vmatsibekker** [comment]
Maybe it is just me. But I went to this branch, and it worked. I switched back to main. Then I switched to this branch. I ran submitty_install, and then got this error. I ran submitty_install again and I still have this error.
image

**Comment by 04vmatsibekker** [comment]
Please make your slide for this

**Pull request closed without merging**
