### PR TITLE
[VPAT:InstructorUI] Made "delete gradeable" button accessible

### LINKED ISSUE #4076: [VPAT:InstructorUI] Device Dependent Event Handler in Gradeables List
The home view that lists available gradeables also has controls to edit (wrench) and delete (trashcan).  The delete control (trashcan) is not keyboard accessible.  WAVE is reporting this as a "Device Dependent Event Handler".  Meaning that this control is only accessible via mouse.
Screen Shot 2019-07-12 at 6 32 34 PM

Looking at the site inspector in Chrome, it appears that the delete function is solely handled by an `onclick()` event handler.  (see lower area, highlighted line).  This will prevent keyboard access to the delete control.
Screen Shot 2019-07-12 at 8 45 14 PM

### PR DESCRIPTION
**Pull request by mktung**
Closes #4076 

Put button inside <button> for semantics and accessibility (should be able to tab and trigger using keyboard)

### CODE REVIEW

**Comment by mktung** [comment]
I've made it more noticeable that we can click the button, but I'm not sure if we can use the render button system here. On-click, the delete button calls a JavaScript function to generate a confirmation form. Is there a way we could call that through href? If not, I think it'd be better to leave this as an exception.

**Comment by shailpatels** [comment]
> I've made it more noticeable that we can click the button, but I'm not sure if we can use the render button system here. On-click, the delete button calls a JavaScript function to generate a confirmation form. Is there a way we could call that through href? If not, I think it'd be better to leave this as an exception.

Yes you can execute a JS function through a hyperlink using
 ```html
<a href="javascript:foo('test');">Execute JavaScript</a>
```

You should be able to construct the link since PHP will know all the information at the time and pass it in.

**Comment by mktung** [comment]
The modal keyboard accessibility is another issue. I think everything else should be good in this latest commit

**Comment by mktung** [comment]
My latest commit should fix the delete button. Also my modals aren't that big? Does your CSS look like this image

**Comment by shailpatels** [comment]
image

This is what I'm seeing on firefox, can you try pulling master into your branch, I'm not sure if the issue is from this branch or somewhere else, I'll look more into that later

**Pull request merged**
