### PR TITLE
[Testing:Developer] Remove force click in test_forum

### PR DESCRIPTION
**Pull request by micpap25**
### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

The force-clicks and wait in this test don't serve a purpose and are bad practice. This removes them.

### CODE REVIEW

**Comment by micpap25** [comment]
So it turns out the force-clicks are used to account for what seems to be an issue with the merge-thread dropdown in that sometimes the thread you want to merge doesn't appear (potentially due to recency of creation?) Waiting wouldn't change this. Something underlying about this needs to be fixed.

**Comment by IDzyre** [comment]
in this specific case, one of the force clicks are because the popup and dropdown for the merge thread goes over the edge of the popup, and scrolling down made even more flakiness, so just forcing it to click the desired dropdown option was the best route.

**Comment by micpap25** [comment]
This should probably be on the backburner until underlying issues with merge threads are resolved

**Comment by IDzyre** [comment]
The force clicks were the way to get around scrolling, since in Cypress, { force: true } clicks on the element no matter if it's visible or not. I agree that the wait should be removed. This was one of the first tests I worked on when I was first starting with Cypress, and so I didn't use the best selectors, and no testids. This one should be refactored to use testids.

**Comment by williamschen23** [comment]
I think we should wait until #10382 is merged because it refactors some of the code to use better selectors, and I'm going to mark this as a draft.

**Comment by williamjallen** [comment]
@williamschen23 and @micpap25, what's the status of this PR?  As per https://github.com/Submitty/Submitty/pull/10480#issuecomment-2158585287, this was waiting for https://github.com/Submitty/Submitty/pull/10382 which has now been merged.

**Comment by williamschen23** [comment]
> @williamschen23 and @micpap25, what's the status of this PR? As per [#10480 (comment)](https://github.com/Submitty/Submitty/pull/10480#issuecomment-2158585287), this was waiting for #10382 which has now been merged.

I tried after #10382 got merged and did not get far. Since this was Michaels PR, I figured he would pick it back up. Since then, forums got another wait if I remember correctly.

**Comment by micpap25** [comment]
Picking this back up, though I might just close it because the issue with it does stem back at merge threads being slow (which i can't address).

**Review by IDzyre — APPROVED** [review]

**Pull request merged**
