### PR TITLE
[Bugfix:Forum] Scroll issue in sidebar of forum

### PR DESCRIPTION
**Pull request by SatendraDiwakar**
### What is the current behavior?
- When filter options are open then the last thread in sidebar gets hidden because of fixed height in child elements.
- **Fixes** #6014 

### What is the new behavior?
- **Reason**: The child elements **threads_list** and **posts_list** is having fix height of 81vh but the parent **thread_container** depends on its own parent due to which the child's scroll is not increasing.
- So I added fix height of **81vh** to **thread_container** and updated child height to **100%** so that they can increase there scroll based on content.

### To reproduce the issue
- Make sure your screen size is having height less than **800px**.
You can change your resolution from developer tools. My screen size is **1500x740**.
- Go to discussion forum and open any thread.
- Check the sidebar which has thread list, before filter options opened up.
- Check the sidebar which has thread list, after filter options opened up. You'll find that the last thread got hidden from the bottom.

### Screenshots

- **_Before fix_**

forumScrollIssue

- **_After fix_**

forumFixed

### CODE REVIEW

**Review by Eceptonsu — COMMENTED** [review]
It seems like on my computer, the PR does not make a difference as describled (Windows 10, Chrome)? Here are the two screenshots. The first one is from main.
image
image

In addition, this PR creates the following behavior. The forums are not in a "container" anymore.
image
image

**Comment by SatendraDiwakar** [comment]
Hi @Eceptonsu ,
Thankyou so much for the review,

> **In addition, this PR creates the following behavior. The forums are not in a "container" anymore.**

I have fixed this please review it again.

And I wanna specify that the issue was produce on screen height less than 800px as per my findings.
And as specified in description, for the issue to be reproduced the filter options has to be opened up.

I have also added reproducing steps in description of the PR.

Here is screenshot of tested resolution

image

**Comment by SatendraDiwakar** [comment]
Hi @Eceptonsu , cc: @williamjallen ,
Just a reminder, I think this PR was missed in the traffic, please review the new changes and also check my comment above, whenever you get chance.
Thanks in advance

**Review by jason490 — APPROVED** [review]
Looks good.
The functionality works as stated.

**Pull request merged**
