### PR TITLE
[UI/UX:InstructorUI] Grading page control button fixing

### LINKED ISSUE #10397: Grading details page control buttons are not consistent
**Describe the bug**
The control buttons on the grading details page have no padding between them, and are not styled consistently.
image

**Expected behavior**
The UI should be clean and consistent.

### PR DESCRIPTION
**Pull request by CCWizma99**
### What is the current behavior?
Controlling buttons in grading details page don't have a consistency in styles.

### What is the new behavior?
With the new updates, controlling will have a consistency and more responsive.
Here's how changes look like in different screen sizes.
Closes #10397 
.
.
.
**VW < 400px**
image
.
.
.
**400px <= VW < 541px**
image
.
.
.
**541px <= VW < 660px AND sidebar-not-collapsed**
image
.
.
.
**541px <= VW < 660px AND sidebar-collopsed**
image
.
.
.
**660px <= VW < 780px AND sidebar-not-collapsed**
image
.
.
.
**660px <= VW < 780px AND sidebar-collapsed**
image
.
.
.
**780px <= VW < 951px AND sidebar-not-collapsed**
image
.
.
.
**780px <= VW < 951px AND sidebar-collapsed**
image
.
.
.
**951px <= VW AND sidebar-not-collapsed**
image
.
.
.
**951px <= VW AND sidebar-not-collapsed**
image

### Other information?
Tested with Responsive design mode in Firefox.

### CODE REVIEW

**Review by justin-sadakhom — APPROVED** [review]
Looks good to me. Thank you for adding the screenshots.

**Review by micpap25 — APPROVED** [review]
Looks good to me. I was a bit concerned that the details-legend changes would cause issues in the other places that details-legend is present but it doesn't cause any new problems.

**Comment by IDzyre** [comment]
Is this the best change according to Shail in https://github.com/Submitty/Submitty/issues/7819

**Comment by micpap25** [comment]
@IDzyre I see the issue and agree. @CCWizma99 Any particular reason you changed from <button> to <a>?

**Comment by CCWizma99** [comment]
@IDzyre & @micpap25, I actually didn't knew that practice in this repository. I will change them back. But, then I will have to make a change with CSS. However, what encouraged me to use `<a>` instead of `<button>` was **Switch to random order/Switch to default order**. That was a part in the code before this change.

**Comment by micpap25** [comment]
@CCWizma99 Will you make the changes as requested? If not we can handle the PR.

**Comment by CCWizma99** [comment]
> @CCWizma99 Will you make the changes as requested? If not we can handle the PR.

I will start working on it right now. Sorry for the delay...

**Comment by CCWizma99** [comment]
@IDzyre @micpap25 I changed the `<a class="btn btn-default" href="" onclick="changeSortOrder()">` to `<button class="btn btn-default" onclick="changeSortOrder()">` as well. Is it okay or should I keep it as it is?

**Review by williamjallen — APPROVED** [review]
Code looks good to me.  I also tested locally and was satisfied with the UI.  Great work on this!

**Review by micpap25 — APPROVED** [review]
Approved! thank you!

**Pull request merged**
