### PR TITLE
[Bugfix:InstructorUI] Regular row insertion in table

### LINKED ISSUE #7040: Out of place white colored background in dark mode.
**Describe the bug**
The Numeric/Text gradeable table have an obnoxious white background when in dark mode.

**Expected behavior**
The background should fit the theme of dark mode. This can be done with `table-striped` class, or just giving it a transparent border.

**Configuration**
 - OS: [e.g. Windows, Linux, ...]

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Gulsonish**
**What is the current behavior?**

Currently, the rows get cloned when we try to create more rows. However, the count of the row also gets cloned and each row ends up having an "even" count and thus the background color is not properly alternated.

**What is the new behavior?**

Now, a new function creates a regular row insertion that gives the inserted row all the required classes and attributes. For that, I had to create a variable for new row insertion which can be appended in that table.

Fixes #7051 
Fixes #7040

### CODE REVIEW

**Comment by Gulsonish** [comment]
I don't know why error 404 is coming when open any commit in this PR.

**Comment by shailpatels** [comment]
@Gulsonish Please read the documentation on how to create a PR, the PR text body should be descriptive on what problem you are trying to fix and the purpose of your changes.

This is why when creating a new PR, a template is automatically created https://github.com/Submitty/Submitty/blob/master/.github/PULL_REQUEST_TEMPLATE.md

and act as sections that you fill out to help reviewers

**Review by HenrikLam — CHANGES_REQUESTED** [review]
Sorry for the late reply, been pretty busy myself. Tested your code and the index of the rows also appears to remain at 0 so the colors aren't changing between the rows. 
image

**Comment by immortalcodes** [comment]
I have run the local environment for the main branch and I don't see any cloning in the rows when I add new. Could you please elaborate how and where you see the issue?

**Comment by bmcutler** [comment]
closing in favor of PR #7964

**Pull request closed without merging**
