### PR TITLE
[UI/UX:SubminiPolls] Fix Checkmark In Dark Mode

### PR DESCRIPTION
**Pull request by BairongZhang1**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fix issue #9114

### What is the new behavior?
image
### Other information?
None

### CODE REVIEW

**Comment by williamjallen** [comment]
Attempting to add borders/backgrounds to FA icons generally doesn't result in a clean-looking UI, since you're applying CSS styling to a SVG image.  Unless FA releases bordered icons, I think any attempt to add an outline around the checkmark will look worse than the current state.  Just my thoughts--I'm open to other opinions here.

**Comment by hansongu123** [comment]
What would happen if I want to change into a different shape like a circle check or just simply adjusting the size? I doubt these changes in CSS would still work.

**Comment by hansongu123** [comment]
FA icons do support features like changing background colors or background shapes. There should be enough templates on the internet just by googling it. What would others do if they want to adjust a FA icons background color in the dark mode? 

@williamjallen I agree it is generally better not to add custom styling for a preset image especially if it's imported like this, but maybe some minimal shape and depth manipulation is good. It would be really cool if we can design our own check mark icon though, I can see it to be useful in many interactive interfaces within Submitty.

**Comment by hansongu123** [comment]
You can try to change it size and shape, and add paddings to see whether or not the changes would still work. Also, different browsers and different OS sometimes have different rendering for the icons.

**Comment by hansongu123** [comment]
@BairongZhang1 I'm going to close this PR now. Lets move to the other PR on the same issue, I've requested a review from you and please feel free to commit.

**Pull request closed without merging**
