### PR TITLE
[Testing:Submission] Add python bulk upload unit tests

### PR DESCRIPTION
**Pull request by shailpatels**
### Please check if the PR fulfills these requirements:

* [X] Tests for the changes have been added/updated (if possible)
* [X] Documentation has been updated/added if relevant (https://github.com/Submitty/submitty.github.io/pull/465)

### What is the current behavior?
There is no way to automatically test the bulk upload split python backend

### What is the new behavior?
The following PR adds python unit tests that run the the normal bulk upload split, qr split, and ocr split stand alone with the more autograding examples PDFs

### CODE REVIEW

**Comment by shailpatels** [comment]
@MasterOdin I added a try,except around the `__init__.py` in `submitty_daemon_jobs` since its looking the submitty.json config file that doesn't exist without a full environment setup 
https://github.com/Submitty/Submitty/pull/7775/files#diff-1e692a5b9b36bf156761f6e2ee12467956c08230133d767fb4c8f0dffac54e11R15-R34

I'm not sure if this is the best way around this - the unit tests don't require the path info collected from that config path but I couldn't find a way to prevent it from not running that init file when running the unittests

**Comment by MasterOdin** [comment]
@shailpatels In production, we definitely still want this to be a hard fail / exception as otherwise I feel like we might hit later on failures that would be harder to immediately debug if you don't notice the error print.

A common pattern to handle the case where we want one behavior in production vs test is to set an environment variable to indicate environment (jest sets `NODE_ENV=test`, rspec sets `RAILS_ENV=test`, etc.). For example, assuming we use `ENV=test`, then I'd make the `__init__.py` file do:

```python
try:
    # read from conf files
except OSError as err:
    if os.environ.get('ENV') != 'test':
        raise err
```

**Comment by shailpatels** [comment]
Ok perfect, I'll implement something like that, thanks!

**Comment by shailpatels** [comment]
@MasterOdin This also adds a new code coverage flag for the `submitty_daemon_jobs` dir - I think its setup correctly but let me know if there's anything that needs to be changed with it

**Comment by bmcutler** [comment]
@MasterOdin Is this ready to merge?

**Review by MasterOdin — CHANGES_REQUESTED** [review]
@shailpatels Could you fix these warnings that get printed on running the tests here?

```
.ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_00.pdf'> [bulk_upload_split.py:66]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_00_cover.pdf'> [bulk_upload_split.py:78]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_06.pdf'> [bulk_upload_split.py:66]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_06_cover.pdf'> [bulk_upload_split.py:78]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_12.pdf'> [bulk_upload_split.py:66]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_12_cover.pdf'> [bulk_upload_split.py:78]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_18.pdf'> [bulk_upload_split.py:66]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_18_cover.pdf'> [bulk_upload_split.py:78]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_[24](https://github.com/Submitty/Submitty/runs/6362488438?check_suite_focus=true#step:13:24).pdf'> [bulk_upload_split.py:66]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_24_cover.pdf'> [bulk_upload_split.py:78]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_30.pdf'> [bulk_upload_split.py:66]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page_[30](https://github.com/Submitty/Submitty/runs/6362488438?check_suite_focus=true#step:13:30)_cover.pdf'> [bulk_upload_split.py:78]
.ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [generic.py:484]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:[47](https://github.com/Submitty/Submitty/runs/6362488438?check_suite_focus=true#step:13:47)]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='01_qr_six_6page.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='04_numeric_id_scan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='04_numeric_id_scan.pdf'> [bulk_qr_split.py:47]
.ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
ResourceWarning: unclosed file <_io.BufferedReader name='03_qr_stress_test_colorscan.pdf'> [bulk_qr_split.py:47]
```

The problem looks to be that we're doing essentially:
```python
foo = open('file/path', 'rb').read()
```

in these different places and while python will eventually clean up the file handle that got created, there's no guarantee on when, and so python is now issuing warnings here (which is good as we don't want hanging handlers for some period of time as there is a max number we can have open on one time).

We need to replace these with context manager usage:
```python
with open('file/path', 'rb') as open_file:
  foo = open_file.read()
```

**Review by Eceptonsu — APPROVED** [review]

**Comment by bmcutler** [comment]
@MasterOdin 
Can you confirm your requested changes are finished?

**Pull request merged**
