### PR TITLE
Error messages test cases

### PR DESCRIPTION
**Pull request by sihsob**
- Small test cases for most of the generated errors that appear in execute.cpp
- Also includes a document of all the test cases and thoughts on why to keep or change a message

### CODE REVIEW

**Comment by inlinefan** [comment]
Looks good to me

**Comment by bmcutler** [comment]
discussed in group meeting yesterday.
looks good.
files will be relocated to the test suite directory tree and testing automated 
with help from @chameco

**Comment by sihsob** [comment]
I've added my changes where I moved the code out of execute into a new class and created a new file with information on what the replace the old messages with.  I'm not sure if my changes are exactly what we want to change them to, just my suggestions.

**Comment by sihsob** [comment]
Let me know if I can pull this in to master or if someone else will

**Comment by bmcutler** [comment]
let's get these files into the location for the test suite before completing the pull request

**Comment by chameco** [comment]
I'll put the files in place over the next few hours.

**Comment by bmcutler** [comment]
We can merge the pull request once the files are in the (probable) permanent location, and make them functional/active in a later pull request.

**Pull request merged**
