### PR TITLE
[UI/UX:Submission] Version Conflict Language for Students

### LINKED ISSUE #10793: Version Conflict Documentation for the student
Write version conflict message for the student and then link that to a documentation for the student side of the version conflict

### PR DESCRIPTION
**Pull request by williamschen23**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Student's will see the feedback but not know how to get the submissions to a valid state. There will be documentation coming to give a list of instructions 

Extension of the merged PR #10774 
Related to Issue #10569 
Closes #10793

### What is the new behavior?
Wording can be subjected to change.
image

### CODE REVIEW

**Comment by williamschen23** [comment]
Merge after https://github.com/Submitty/submitty.github.io/pull/630

**Comment by bmcutler** [comment]
@williamschen23 
please update the url (I changed it in the documentation PR)

**Comment by bmcutler** [comment]
(but the text is good)

**Review by ziesski — APPROVED** [review]
LGTM

**Review by bmcutler — APPROVED** [review]
thanks for the update!

**Pull request merged**
