### PR TITLE
[Bugfix:Forum] Remove OP for anonymous author

### LINKED ISSUE #10381: Discussion forum anonymized OP
**What problem are you trying to solve with Submitty**
If someone posts anonymously on the discussion forum, but responds to the comment non-anonymously, the post and comment are inconsistently anonymous.

**Describe the way you'd like to solve this problem**
The `OP` marker should be disabled for non-anonymous replies when the initial post is made anonymously in order to keep the post anonymized.

**Additional context**
An example post where the OP is anonymous but is de-anonymized by commenting:
non-anonymous op

### PR DESCRIPTION
**Pull request by Xiayucheng1212**
fixes #10381

### What is the new behavior?
Only show the "OP" marker when the author didn't post anonymously. 

### Other information?
Add a new variable 'first_post_anonymous' to judge whether the marker is available.

The edit icon shown in this image demonstrates the first and third author are the same person and there is no 'OP' marked.

截圖 2024-05-17 下午12 10 08

### CODE REVIEW

**Review by cjreed121 — COMMENTED** [review]
Don't forget this instance of createPost being called: https://github.com/Submitty/Submitty/blob/802ce7e74f3a686776be0fb521a949c41e065d61/site/app/controllers/forum/ForumController.php#L595-L614

**Review by justin-sadakhom — CHANGES_REQUESTED** [review]
Please fix the [failing Cypress tests](https://github.com/Submitty/Submitty/actions/runs/9122816284/job/25084230121?pr=10447#step:7:258).

**Review by justin-sadakhom — APPROVED** [review]

**Comment by williamschen23** [comment]
Should there be an option to prompt the original author if they want the OP tag? Sometimes it is useful to know that the person you are dealing with is the person who made the thread on the problem in the first place.

**Review by zacharymnp — CHANGES_REQUESTED** [review]
image
image
image

Most anticipated behavior works correctly as pictured above. However, when OP makes an anonymous reply to a non-anonymous post, their reply is marked with OP, which is not ideal.

image

**Review by zacharymnp — APPROVED** [review]
Requested change was implemented:

image

**Comment by bmcutler** [comment]
Thanks @zacharymnp for doing the 4 cases so clearly.

But, anonymous post + anonymous reply by same person SHOULD be labeled OP.  
That's the whole point of the original issue.  #10162 

The only time we don't want to label OP is when it deanonymizes a user because the user has inconsistent usage of the anonymous option.

**Review by bmcutler — CHANGES_REQUESTED** [review]
see note above

**Comment by ZheyuDeng** [comment]
Should be good now. Simplified condition.
is_OP = = ($post["author_user_id"] === $first_post_author_id) && ($first_post_anonymous === $post["anonymous"])
e234bbb64230e2c3814909915f5263e
134fa91b9c9425ce265f7013efd9246

**Review by zacharymnp — APPROVED** [review]
changes work

**Review by bmcutler — APPROVED** [review]

**Pull request merged**
