### PR TITLE
[TAGrading: Bugfix]Cancelled Submissions Inconsistently Counted in Stats

### PR DESCRIPTION
**Pull request by jchulton**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
If a submission is graded, then the submission is canceled by the student, the submission will count as graded in the numerator of the TA Grading by Section calculations, but not the denominator. This can lead to a numerator greater than the denominator.

### What is the new behavior?
The gradeable is counted in both the numerator and denominator. This prevents percentages greater than 100%

### CODE REVIEW

**Comment by emaicus** [comment]
@jchulton, let's approach this differently. Instead of counting canceled submissions, let's discount them all together.

**Review by bmcutler — CHANGES_REQUESTED** [review]
please see Evan's comment
the cancelled should not be in the numerator or the denominator.

**Comment by jchulton** [comment]
Cancelled submissions are no longer in the numerator or denominator, as above

**Review by emaicus — CHANGES_REQUESTED** [review]
This works well for standard (TA graded) gradeables.

At a glance, peer totals are incorrect. For the "Peer PDF Homework" in the sample course, I see `Students who have submitted: 180 / 101 (178.2%)`

Also, how should we be counting version conflicts? At the moment, they are counted towards completed grading. Perhaps we should list them separately?

**Review by emaicus — APPROVED** [review]
After a group conversation, it was agreed that peer stats are a separate issue and that version conflicts are being tallied correctly.

I have opened #6039, and approve this PR.

**Pull request merged**
