### PR TITLE
[Refactor:SampleData] Added sample TA/instructor notes for components

### PR DESCRIPTION
**Pull request by Fenn-CS**
Signed-off-by: fenn-cs <fenn25.fn@gmail.com>

### What is the current behavior?
Currently, Note to TA's and Students in the Rubrics section while creating or editing a gradeable are always blank. 

Fixes: #2171 

### What is the new behavior?
Generates random comments to supply as notes.
### Other information?
There's a file 'TAcomments.txt` that holds some example comments that are used randomly to generate TA comments there's no such file for student comments. Is it better to add such a file with a few comments or use `lipsum` (https://github.com/thanethomson/lipsum), possible for both TA and student comments eliminating the need for both files.

### CODE REVIEW

**Comment by Fenn-CS** [comment]
random_ta_notes

**Comment by bmcutler** [comment]
As we discussed in the meeting, component_comment is different than ta_comment (or ta_note).  component_comment is the individual feedback from a ta to a specific student about their work.  The ta_comment/ta_note is instructions on how to grade all students for this assignment from the instructor to the ta.  similarly the student_comment is general information from the instructor to the students about how the assignment will be graded.

Please make 3 separate functions.   (The messages for those functions should come from a short list of sample phrases, could be stored in a file, or directly in the function. ) .  I suggest renaming the existing ta comment function to use the word component.  There is also an (optional) 'overall comment' from the grader to the student with specific feedback for that student about their work.

**Comment by Fenn-CS** [comment]
Ok, Barb. I have made the requested changes in the last commit :

ta-student-note

However, I noticed no instructions are given for gradeables that have the "Checkpoints" type. Is this behavior ok?

checkpoint_gradeable

**Comment by MasterOdin** [comment]
Should the randomly selected output have some relation to each other? Right now, it's possible to end up with (for example) a student comment of `Code may make use of classes and methods or just a bunch of functions.` and a TA comment of `Deduct points if student makes use of tabs.`.

**Comment by Fenn-CS** [comment]
@MasterOdin  yeah thought of that. It's weird since some of the student notes actually fall in line with what is noted to instructors as well!
If this is important! I can add some code to ensure that the comments are related. @bmcutler

**Comment by bmcutler** [comment]
It is not necessary to add logic to meaningfully match up the comments.  One step up from lorem ipsum is fine.

**Pull request merged**
