### PR TITLE
[Bugfix:Submission] Hide Notebook Generated Submissions

### LINKED ISSUE #8659: Download submitted files & access prior versions options broken
**Describe the bug**
These settings:
Screen Shot 2022-12-12 at 4 28 07 PM
don't appear to be working.

**Expected behavior**
The "View and download  submitted files" should hide:
Screen Shot 2022-12-12 at 4 28 47 PM

And the "access prior versions" should hide
Screen Shot 2022-12-12 at 4 29 00 PM

I'm not sure if these options are doing anything right now.  BTW, I tested this using a notebook gradeable.  These settings are also useful for bulk upload, so maybe they currently only work for bulk upload -- which is an error.

### PR DESCRIPTION
**Pull request by jason490**
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Closes #8659
These options don't work properly for all cases
image

Notebook Downloads show submissions generated by the notebook (for multiple choice or text input questions) (this is undesired)
image

### What is the new behavior?
Verified these options work as desired

Notebook generated submissions hidden
image

### What to test for:
If view and download submitted files and make new submissions and access all prior versions work on each major type of gradeable:

- Student Submission
- VCS Submission
- Team Submission
- Bulk Upload Submission
- Notebook Submission

And if for notebook, the notebook-generated responses aren't visible in any case. It is okay if they are visible in the "download all" zip file, as that is being addressed separately in Issue https://github.com/Submitty/Submitty/issues/9481

### CODE REVIEW

**Review by tkoz0 — CHANGES_REQUESTED** [review]
I looked at the code and left a comment. Would you also be able to describe how to properly test it so I can do that?

**Comment by jason490** [comment]
> I looked at the code and left a comment. Would you also be able to describe how to properly test it so I can do that?

Test it using multiple different type of gradeables to make sure it throw an exception in those gradeables and test the notebook gradable to check if it functions based on what this PR is about.

**Review by AdamTuhacek — COMMENTED** [review]
The functionality of removing the student downloading options and hence hiding the download option seems to be working. Two things to clarify,
- Should this also hide the first access timestamp/related info?
- When downloading is enabled, this still allows students to download all files (not just submitted ones), is this expected?

**Comment by mahi-pas** [comment]
The next part, which is hiding notebook submissions from the download zip button, will be addressed in issue https://github.com/Submitty/Submitty/issues/9481

**Review by 04vmatsibekker — APPROVED** [review]

**Pull request merged**
