### PR TITLE
Fix undefined variable $show_deleted_thread_title

### LINKED ISSUE #3510: Undefined variable: show_deleted_thread_title when opening forum
## Description
When discussion forum is activated for a course, click a notification or the discussion forum link quickly drops an `undefined variable` error before opening forum....

```
Notice: Undefined variable: show_deleted_thread_title in /usr/local/submitty/site/app/views/forum/ForumThreadView.php on line 306
--
1 | 0.0014 | 454768 | {main}(  ) | .../index.php:0
2 | 0.2769 | 3594480 | app\controllers\forum\ForumController->run(  ) | .../index.php:270
3 | 0.2769 | 3594480 | app\controllers\forum\ForumController->showThreads(  ) | .../ForumController.php:97
4 | 0.3495 | 3607504 | app\libraries\Output->renderOutput(  ) | .../ForumController.php:726
5 | 0.3495 | 3608200 | call_user_func_array:{/usr/local/submitty/site/app/libraries/Output.php:111} (  ) | .../Output.php:111
6 | 0.3495 | 3608360 | app\libraries\Output->renderTemplate(  ) | .../Output.php:111
7 | 0.3543 | 3836744 | call_user_func_array:{/usr/local/submitty/site/app/libraries/Output.php:146} (  ) | .../Output.php:146
8 | 0.3543 | 3836872 | app\views\forum\ForumThreadView->showForumThreads(  ) | .../Output.php:146
```
forum-error

## Expected behavior
Forum should open without any errors

## How reproduce
I am only noticed the error after creating a post in the forum... The error was flashed before leading to the post page (post creation was successful). After that every click to forum yield the error.

### PR DESCRIPTION
**Pull request by zjxiaohan**
Closes #3510 

The changes were correct in https://github.com/Submitty/Submitty/commit/eb59f91c1452481afc1a1d442c09ce0a597a6639, but was somehow partially changed in later commits, leading to the error.

Thank @Fenn-CS for pointing it out.

### CODE REVIEW

**Comment by Fenn-CS** [comment]
Thanks for the quick fix @zjxiaohan . Even though the PR has  been approved, it will be cool if subsequently you try to  indent as much as possible.
```
//This lines are not aligned here
$show_deleted_action = '';
    $show_deleted_thread_title = '';
	if($this->core->getUser()->getGroup() <= 3){
	if($this->core->getUser()->getGroup() <= 3){
		if($show_deleted) {
		if($show_deleted) {
			$show_deleted_class = "active";
			$show_deleted_class = "active";
			$show_deleted_action = "alterShowDeletedStatus(0);";
			$show_deleted_action = "alterShowDeletedStatus(0);"; 
      //This lines are not aligned here too
      $show_deleted_thread_title = "Hide Deleted Threads";
            $show_deleted_thread_title = "Hide Deleted Threads";
		} else {
		} else {
			$show_deleted_class = "";
			$show_deleted_class = "";
			$show_deleted_action = "alterShowDeletedStatus(1);";
			$show_deleted_action = "alterShowDeletedStatus(1);";
      //This lines are not aligned here also
      $show_deleted_thread_title = "Show Deleted Threads";
            $show_deleted_thread_title = "Show Deleted Threads";
		}
		}
	}
	}
```

**Comment by zjxiaohan** [comment]
@Fenn-CS Thank you for your feedback. However, I am not sure what you are referring to. The indentation looks correct from my perspective of view. Would you mind providing more details?

indent

**Comment by Fenn-CS** [comment]
@zjxiaohan oh my bad... I just confirmed was looking (partly because I don't have review options yet) use the quick files changed section here which shifts updated lines. The full view is ok.

ref-diff-view

All good :).

**Comment by zjxiaohan** [comment]
@Fenn-CS I didn't know that there is a "split" option until now :laughing: 
Thank you anyway for reviewing!

**Pull request merged**
